#!/usr/bin/env python3
"""Generate the cuTensorNet dynamic-loading layer from the symbol manifest.

The manifest (``scripts/cutensornet-symbols.txt``) names every symbol the loader
resolves. The signatures are read from the checked-in bindings so a function
pointer can never disagree with the declaration it is resolved against; both
sides ultimately derive from the same pinned ``cutensornet.h``.

Unlike ``generate-bindings.sh`` this script needs no CUDA headers, no bindgen and
no pinned archive, so it runs on any development host.

Usage:
    generate-loader.py [--check]

``--check`` regenerates into a temporary directory and fails if the checked-in
files differ, which is what CI runs to prove the loader was not hand-edited.
"""

from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

CRATE_ROOT = Path(__file__).resolve().parent.parent
MANIFEST = CRATE_ROOT / "scripts" / "cutensornet-symbols.txt"
BINDINGS = CRATE_ROOT / "src" / "bindings" / "v2_13.rs"
SYMBOLS_RS = CRATE_ROOT / "src" / "library" / "symbols.rs"
SYMBOLS_DIR = CRATE_ROOT / "src" / "library" / "symbols"
RUST_EDITION = "2024"

BANNER = (
    "// @generated by scripts/generate-loader.py; do not edit.\n"
    "// Source: scripts/cutensornet-symbols.txt and src/bindings/v2_13.rs.\n"
)

# Families are emitted in this order so that adding a symbol produces a diff
# local to its family rather than reshuffling the whole file.
FAMILY_ORDER = [
    "context",
    "state",
    "workspace",
    "operator",
    "expectation",
    "sampler",
    "contraction",
]

DECLARED_TYPE_RE = re.compile(r"^pub (?:type|struct|enum|union) (\w+)", re.M)
FUNCTION_RE = re.compile(r"^\s*pub fn (\w+)\(([^()]*)\)\s*->\s*([^;]+);", re.M | re.S)
PARAM_RE = re.compile(r"^(\w+)\s*:\s*(.+)$", re.S)


class GenerationError(Exception):
    """A manifest or bindings inconsistency that must stop generation."""


def fail(message: str) -> None:
    raise GenerationError(message)


def read_manifest(path: Path) -> list[tuple[str, str, str, str]]:
    rows: list[tuple[str, str, str, str]] = []
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        if len(parts) != 4:
            fail(f"{path.name}:{number}: expected 4 columns, found {len(parts)}")
        symbol, field, family, requirement = parts
        if family not in FAMILY_ORDER:
            fail(f"{path.name}:{number}: unknown family {family!r}")
        if requirement not in ("required", "optional"):
            fail(f"{path.name}:{number}: unknown requirement {requirement!r}")
        rows.append((symbol, field, family, requirement))

    for column, label in ((0, "symbol"), (1, "field")):
        seen: dict[str, int] = {}
        for index, row in enumerate(rows):
            if row[column] in seen:
                fail(f"duplicate {label} {row[column]!r} in {path.name}")
            seen[row[column]] = index
    if not rows:
        fail(f"{path.name} declares no symbols")
    return rows


def parse_bindings(path: Path) -> tuple[dict[str, tuple[list[str], str]], set[str]]:
    source = path.read_text(encoding="utf-8")
    declared = set(DECLARED_TYPE_RE.findall(source))

    signatures: dict[str, tuple[list[str], str]] = {}
    for name, params, ret in FUNCTION_RE.findall(source):
        types: list[str] = []
        for chunk in params.split(","):
            chunk = chunk.strip()
            if not chunk:
                continue
            match = PARAM_RE.match(chunk)
            if match is None:
                fail(f"{path.name}: cannot parse parameter {chunk!r} of {name}")
            types.append(" ".join(match.group(2).split()))
        signatures[name] = (types, " ".join(ret.split()))
    if not signatures:
        fail(f"{path.name}: no function declarations found")
    return signatures, declared


def qualify(rust_type: str, declared: set[str]) -> str:
    """Prefix types declared by the bindings with their module path."""

    def replace(match: re.Match[str]) -> str:
        name = match.group(0)
        return f"v2_13::{name}" if name in declared else name

    return re.sub(r"\b\w+\b", replace, rust_type)


def alias_name(field: str) -> str:
    return "".join(part.title() for part in field.split("_")) + "Fn"


def render_family(family: str, rows: list[tuple[str, str, str, str]],
                  signatures: dict[str, tuple[list[str], str]],
                  declared: set[str]) -> str:
    lines = [BANNER, f"//! `{family}` cuTensorNet entry points.\n"]
    body: list[str] = []
    uses_bindings = False

    for symbol, field, _, _ in rows:
        params, ret = signatures[symbol]
        qualified = [qualify(param, declared) for param in params]
        qualified_ret = qualify(ret, declared)
        uses_bindings = uses_bindings or any(
            "v2_13::" in item for item in [*qualified, qualified_ret]
        )
        joined = ", ".join(qualified)
        body.append(
            f"/// Function pointer for `{symbol}`.\n"
            f"pub(crate) type {alias_name(field)} = "
            f"unsafe extern \"C\" fn({joined}) -> {qualified_ret};\n"
        )

    if uses_bindings:
        lines.append("\nuse crate::bindings::v2_13;\n")
    lines.append("\n")
    lines.append("\n".join(body))
    return "".join(lines)


def render_root(rows: list[tuple[str, str, str, str]]) -> str:
    lines = [BANNER, "//! The resolved cuTensorNet entry points.\n\n"]
    for family in FAMILY_ORDER:
        lines.append(f"pub(crate) mod {family};\n")
    lines.append(
        "\nuse super::{CUTENSORNET_NAME, SymbolResolver, resolve_optional, resolve_required};\n"
        "use crate::AvailabilityError;\n"
        "use std::path::Path;\n\n"
        "/// Every cuTensorNet entry point the loader resolves.\n"
        "#[allow(dead_code)]\n"
        "pub(crate) struct CuTensorNetFunctions {\n"
    )
    for symbol, field, family, requirement in rows:
        alias = f"{family}::{alias_name(field)}"
        if requirement == "optional":
            lines.append(
                f"    /// Optional diagnostic only; absence must never reject discovery.\n"
                f"    pub(crate) {field}: Option<{alias}>,\n"
            )
        else:
            lines.append(f"    pub(crate) {field}: {alias},\n")
    lines.append("}\n\n")

    lines.append(
        "#[allow(clippy::too_many_lines)]\n"
        "pub(crate) fn resolve_cutensornet_functions<R: SymbolResolver>(\n"
        "    resolver: &R,\n"
        "    path: &Path,\n"
        ") -> Result<CuTensorNetFunctions, AvailabilityError> {\n"
        "    Ok(CuTensorNetFunctions {\n"
    )
    for symbol, field, _, requirement in rows:
        if requirement == "optional":
            lines.append(
                f"        {field}: resolve_optional(resolver, b\"{symbol}\\0\"),\n"
            )
        else:
            lines.append(
                f"        {field}: resolve_required(\n"
                f"            resolver,\n"
                f"            CUTENSORNET_NAME,\n"
                f"            path,\n"
                f"            \"{symbol}\",\n"
                f"            b\"{symbol}\\0\",\n"
                f"        )?,\n"
            )
    lines.append("    })\n}\n")
    return "".join(lines)


def generate(root_path: Path, dir_path: Path) -> None:
    rows = read_manifest(MANIFEST)
    signatures, declared = parse_bindings(BINDINGS)

    missing = [symbol for symbol, *_ in rows if symbol not in signatures]
    if missing:
        fail(
            "manifest symbols are absent from the generated bindings "
            f"(regenerate bindings on a CUDA host first): {missing}"
        )

    dir_path.mkdir(parents=True, exist_ok=True)
    written = [root_path]
    root_path.write_text(render_root(rows), encoding="utf-8")
    for family in FAMILY_ORDER:
        members = [row for row in rows if row[2] == family]
        if not members:
            fail(f"family {family!r} has no symbols")
        target = dir_path / f"{family}.rs"
        target.write_text(
            render_family(family, members, signatures, declared), encoding="utf-8"
        )
        written.append(target)

    if shutil.which("rustfmt") is None:
        fail("rustfmt is not available")
    subprocess.run(
        ["rustfmt", "--edition", RUST_EDITION, *(str(item) for item in written)],
        check=True,
    )
    print(f"symbols={len(rows)} files={len(written)}")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the checked-in files differ from freshly generated output",
    )
    args = parser.parse_args()

    try:
        if not args.check:
            generate(SYMBOLS_RS, SYMBOLS_DIR)
            return 0

        with tempfile.TemporaryDirectory() as temp:
            staging = Path(temp)
            generate(staging / "symbols.rs", staging / "symbols")
            stale = []
            for candidate in [SYMBOLS_RS, *sorted(SYMBOLS_DIR.glob("*.rs"))]:
                relative = candidate.relative_to(SYMBOLS_RS.parent)
                fresh = staging / relative
                if not fresh.exists() or fresh.read_bytes() != candidate.read_bytes():
                    stale.append(str(relative))
            if stale:
                print(
                    "generated loader is out of date; run scripts/generate-loader.py: "
                    + ", ".join(stale),
                    file=sys.stderr,
                )
                return 1
        return 0
    except (GenerationError, subprocess.CalledProcessError) as error:
        print(f"generate-loader: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
