# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

from __future__ import annotations
import copy
from typing import TYPE_CHECKING

from abc import ABC, abstractmethod

from ._qre import ISA, _ProvenanceGraph, _Instruction

if TYPE_CHECKING:
    from ._instruction import ISATransform


class Architecture(ABC):
    @property
    @abstractmethod
    def provided_isa(self) -> ISA: ...

    def context(self) -> _Context:
        """Create a new enumeration context for this architecture."""
        return _Context(self)


class _Context:
    """
    Context passed through enumeration, holding shared state.
    """

    def __init__(self, arch: Architecture):
        self._provenance: _ProvenanceGraph = _ProvenanceGraph()

        def _mark_instruction(inst: _Instruction) -> _Instruction:
            node = self._provenance.add_node(inst.id, 0, [])
            inst.set_source(node)
            return inst

        self._isa = ISA([_mark_instruction(instr) for instr in arch.provided_isa])

        self._bindings: dict[str, ISA] = {}
        self._transforms: dict[int, Architecture | ISATransform] = {0: arch}

    def _with_binding(self, name: str, isa: ISA) -> _Context:
        """Return a new context with an additional binding (internal use)."""
        ctx = copy.copy(self)
        ctx._bindings = {**self._bindings, name: isa}
        return ctx

    def set_source(
        self,
        transform: ISATransform,
        instruction: _Instruction,
        source_instructions: list[_Instruction],
    ) -> _Instruction:
        """
        Record the provenance of an instruction generated by a transform, and
        return the instruction with its source set.

        Args:
            transform: The transform that generated the instruction.
            instruction: The instruction whose provenance is being recorded.
            source_instructions: The instructions that were used as input to the
                transform to generate this instruction.

        Returns:
            The input instruction with its source set to the provenance node.
        """

        source = self._provenance.add_node(
            instruction.id, id(transform), [inst.source for inst in source_instructions]
        )

        instruction.set_source(source)
        return instruction
