# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

DISTANCE: int
SURFACE_CODE_ONE_QUBIT_TIME_FACTOR: int
SURFACE_CODE_TWO_QUBIT_TIME_FACTOR: int
ACCELERATION: int
NUM_TS_PER_ROTATION: int
EXPECTED_SHOTS: int
RUNTIME_SINGLE_SHOT: int
EVALUATION_TIME: int
PHYSICAL_COMPUTE_QUBITS: int
PHYSICAL_FACTORY_QUBITS: int
PHYSICAL_MEMORY_QUBITS: int
MOLECULE: int
LOGICAL_COMPUTE_QUBITS: int
LOGICAL_MEMORY_QUBITS: int
ALGORITHM_COMPUTE_QUBITS: int
ALGORITHM_MEMORY_QUBITS: int
NAME: int
LOSS: int
LOGICAL_CYCLE_TIME: int
