[workspace]
members = [
    "compiler/qsc",
    "compiler/qsc_ast",
    "compiler/qsc_codegen",
    "compiler/qsc_eval",
    "compiler/qsc_frontend",
    "compiler/qsc_passes",
]

[workspace.package]
authors = ["Microsoft"]
homepage = "https://github.com/microsoft/qsharp"
repository = "https://github.com/microsoft/qsharp"
edition = "2021"
license = "MIT"

[profile.release]
debug = 1
