[workspace]
members = [
    "compiler/qsc",
    "compiler/qsc_ast",
    "compiler/qsc_codegen",
    "compiler/qsc_eval",
    "compiler/qsc_frontend",
    "compiler/qsc_passes",
]

[workspace.package]
authors = ["Microsoft"]
homepage = "https://github.com/microsoft/qsharp"
repository = "https://github.com/microsoft/qsharp"
edition = "2021"
license = "MIT"

[workspace.dependencies]
clap = "4.1.8"
criterion = { version = "0.4.0", default-features = false }
enum-iterator = "1.2.0"
expect-test = "1.4.0"
indoc = "2.0.0"
miette = "5.6.0"
thiserror = "1.0.39"
num-bigint = "0.4.3"
num-traits = "0.2.15"

[profile.release]
debug = 1
