[workspace]
members = [
    "compiler/qsc",
    "compiler/qsc_ast",
    "compiler/qsc_codegen",
    "compiler/qsc_eval",
    "compiler/qsc_frontend",
    "compiler/qsc_passes",
    "compiler/qsc_wasm",
    "compiler/qsi",
]

[profile.release]
debug = 1