[workspace]
members = [
    "compiler/qsc_ast",
    "compiler/qsc_codegen",
    "compiler/qsc_eval",
    "compiler/qsc_frontend",
    "compiler/qsc_passes",
    "compiler/qsc_wasm",
    "compiler/qtest_tool",
    "katas",
]

[workspace.package]
authors = ["Microsoft"]
homepage = "https://github.com/microsoft/qsharp"
repository = "https://github.com/microsoft/qsharp"
edition = "2021"
license = "MIT"

[workspace.dependencies]
clap = "4.1.8"
criterion = { version = "0.4.0", default-features = false }
enum-iterator = "1.2.0"
expect-test = "1.4.0"
getrandom = { version = "0.2" }
indoc = "2.0.0"
js-sys = "0.3.61"
miette = "5.6.0"
thiserror = "1.0.39"
num-bigint = "0.4.3"
num-complex = "0.4"
num-traits = "0.2.15"
once_cell = "1.17.1"
serde = "1.0"
serde-wasm-bindgen = "0.5"
wasm-bindgen = "0.2.84"

[profile.release]
debug = 1
