[package]
name = "qsc"
version = "0.0.0"
description = "Q# compiler"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clap = { workspace = true, features = ["derive"] }
miette = { workspace = true, features = ["fancy"] }
qsc_codegen = { path = "../qsc_codegen" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_hir = { path = "../qsc_hir" }
qsc_passes = { path = "../qsc_passes" }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["cargo_bench_support"] }

[[bench]]
name = "nqueens"
harness = false

[[bench]]
name = "library"
harness = false

[[bin]]
name = "qsc"
bench = false
