[package]
name = "qsc"
version = "0.0.0"
edition = "2021"

[dependencies]
qsc_ast = { path = "../qsc_ast" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_passes = { path = "../qsc_passes" }
qsc_codegen = { path = "../qsc_codegen" }
qsc_eval = { path = "../qsc_eval" }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "nqueens"
harness = false

[[bench]]
name = "library"
harness = false

[[bin]]
name = "qsc"
bench = false