//! Generation of the cuTensorNet dynamic-loading layer from the symbol manifest.
//!
//! The manifest (`scripts/cutensornet-symbols.txt`) names every symbol the
//! loader resolves. Signatures are read from the checked-in bindings so a
//! function pointer can never disagree with the declaration it is resolved
//! against; both sides ultimately derive from the same pinned `cutensornet.h`.
//!
//! [`render`] is deliberately pure: it takes the two input documents as text
//! and returns the generated files as text. Every failure mode is a typed
//! [`GenerationError`], so the whole contract is exercised by ordinary unit
//! tests without touching the filesystem. The binary in
//! `src/bin/generate-loader.rs` is the only part that does I/O.
//!
//! Output is *not* formatted here. The binary pipes it through `rustfmt`, and
//! the repository-wide `cargo fmt --all -- --check` independently guarantees
//! the checked-in files stay canonical, so this module never has to reproduce
//! rustfmt's line-wrapping heuristics.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

/// Families are emitted in this order so that adding a symbol produces a diff
/// local to its family rather than reshuffling the whole file.
pub const FAMILY_ORDER: [&str; 7] = [
    "context",
    "state",
    "workspace",
    "operator",
    "expectation",
    "sampler",
    "contraction",
];

const BANNER: &str = concat!(
    "// @generated by `cargo run --bin generate-loader`; do not edit.\n",
    "// Source: scripts/cutensornet-symbols.txt and src/bindings/v2_13.rs.\n"
);

/// A manifest or bindings inconsistency that must stop generation.
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum GenerationError {
    /// A manifest row did not have exactly the four expected columns.
    #[error("cutensornet-symbols.txt:{line}: expected 4 columns, found {found}")]
    ColumnCount { line: usize, found: usize },
    /// A manifest row named a family that has no generated file.
    #[error("cutensornet-symbols.txt:{line}: unknown family {family:?}")]
    UnknownFamily { line: usize, family: String },
    /// A manifest row was neither `required` nor `optional`.
    #[error("cutensornet-symbols.txt:{line}: unknown requirement {requirement:?}")]
    UnknownRequirement { line: usize, requirement: String },
    /// The same C symbol was listed twice.
    #[error("duplicate symbol {symbol:?} in cutensornet-symbols.txt")]
    DuplicateSymbol { symbol: String },
    /// Two rows would generate the same struct field.
    #[error("duplicate field {field:?} in cutensornet-symbols.txt")]
    DuplicateField { field: String },
    /// The manifest was empty, which would silently generate an empty loader.
    #[error("cutensornet-symbols.txt declares no symbols")]
    EmptyManifest,
    /// A parameter in the bindings did not look like `name: Type`.
    #[error("v2_13.rs: cannot parse parameter {chunk:?} of {function}")]
    UnparsableParameter { function: String, chunk: String },
    /// The bindings contained no `pub fn`, so they were probably truncated.
    #[error("v2_13.rs: no function declarations found")]
    NoFunctions,
    /// The manifest is ahead of the bindings.
    #[error(
        "manifest symbols are absent from the generated bindings \
         (regenerate bindings on a CUDA host first): {symbols:?}"
    )]
    MissingSymbols { symbols: Vec<String> },
    /// A family in [`FAMILY_ORDER`] had no manifest rows.
    #[error("family {family:?} has no symbols")]
    EmptyFamily { family: String },
}

/// Whether the loader may start without a symbol.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Requirement {
    /// Discovery fails if the symbol is absent.
    Required,
    /// Absence is tolerated and recorded as `None`.
    Optional,
}

/// One row of the symbol manifest.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ManifestRow {
    /// The C symbol resolved from the shared library.
    pub symbol: String,
    /// The field name on `CuTensorNetFunctions`.
    pub field: String,
    /// The family whose file declares the function pointer alias.
    pub family: String,
    /// Whether discovery may proceed without the symbol.
    pub requirement: Requirement,
}

/// A generated source file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedFile {
    /// Path relative to `src/library/`, using `/` separators.
    pub path: String,
    /// Unformatted Rust source.
    pub contents: String,
}

/// A function signature recovered from the bindings.
///
/// Types are kept exactly as the bindings spell them; the `v2_13::` module
/// prefix the loader needs is a serialization concern, applied by [`serialize`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Signature {
    /// Parameter types, in declaration order.
    pub params: Vec<String>,
    /// The return type.
    pub ret: String,
}

/// One entry point the loader will resolve.
///
/// This is the semantic content of the generated loader: a manifest row joined
/// to the signature the header declares for it. It carries no indentation, no
/// module paths and no file layout, so tests can assert on *what* the loader
/// does independently of *how* it is written out.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LoaderEntry {
    /// The C symbol resolved from the shared library.
    pub symbol: String,
    /// The field name on `CuTensorNetFunctions`.
    pub field: String,
    /// The family whose file declares the function pointer alias.
    pub family: String,
    /// Whether discovery may proceed without the symbol.
    pub requirement: Requirement,
    /// The function pointer alias derived from [`Self::field`].
    pub alias: String,
    /// The signature the loader must call through.
    pub signature: Signature,
}

/// The complete, validated description of the loader.
///
/// [`Loader::build`] is the only fallible step: it performs every consistency
/// check between the manifest and the bindings. [`serialize`] then turns a
/// `Loader` into source text and cannot fail.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Loader {
    entries: Vec<LoaderEntry>,
    declared: BTreeSet<String>,
}

impl Loader {
    /// Join the manifest to the bindings, validating both.
    pub fn build(manifest: &str, bindings: &str) -> Result<Self, GenerationError> {
        let rows = parse_manifest(manifest)?;
        let bindings = parse_bindings(bindings)?;

        let missing: Vec<String> = rows
            .iter()
            .filter(|row| !bindings.signatures.contains_key(&row.symbol))
            .map(|row| row.symbol.clone())
            .collect();
        if !missing.is_empty() {
            return Err(GenerationError::MissingSymbols { symbols: missing });
        }

        for family in FAMILY_ORDER {
            if !rows.iter().any(|row| row.family == family) {
                return Err(GenerationError::EmptyFamily {
                    family: family.to_owned(),
                });
            }
        }

        let entries = rows
            .into_iter()
            .map(|row| {
                let signature = bindings
                    .signatures
                    .get(&row.symbol)
                    .cloned()
                    .unwrap_or_else(|| unreachable!("absent symbols were rejected above"));
                LoaderEntry {
                    alias: alias_name(&row.field),
                    symbol: row.symbol,
                    field: row.field,
                    family: row.family,
                    requirement: row.requirement,
                    signature,
                }
            })
            .collect();

        Ok(Self {
            entries,
            declared: bindings.declared,
        })
    }

    /// Every entry, in manifest order.
    #[must_use]
    pub fn entries(&self) -> &[LoaderEntry] {
        &self.entries
    }

    /// The entry for a C symbol, if the manifest names it.
    #[must_use]
    pub fn entry(&self, symbol: &str) -> Option<&LoaderEntry> {
        self.entries.iter().find(|entry| entry.symbol == symbol)
    }

    /// The entries belonging to a family, in manifest order.
    #[must_use]
    pub fn family(&self, family: &str) -> Vec<&LoaderEntry> {
        self.entries
            .iter()
            .filter(|entry| entry.family == family)
            .collect()
    }
}

/// The declarations recovered from the generated bindings.
#[derive(Debug, Clone)]
struct Bindings {
    signatures: BTreeMap<String, Signature>,
    declared: BTreeSet<String>,
}

/// Parse the manifest, rejecting every malformed shape.
pub fn parse_manifest(text: &str) -> Result<Vec<ManifestRow>, GenerationError> {
    let mut rows: Vec<ManifestRow> = Vec::new();

    for (index, raw) in text.lines().enumerate() {
        let line = raw.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let number = index + 1;
        let parts: Vec<&str> = line.split_whitespace().collect();
        if parts.len() != 4 {
            return Err(GenerationError::ColumnCount {
                line: number,
                found: parts.len(),
            });
        }
        let (symbol, field, family, requirement) = (parts[0], parts[1], parts[2], parts[3]);
        if !FAMILY_ORDER.contains(&family) {
            return Err(GenerationError::UnknownFamily {
                line: number,
                family: family.to_owned(),
            });
        }
        let requirement = match requirement {
            "required" => Requirement::Required,
            "optional" => Requirement::Optional,
            other => {
                return Err(GenerationError::UnknownRequirement {
                    line: number,
                    requirement: other.to_owned(),
                });
            }
        };
        rows.push(ManifestRow {
            symbol: symbol.to_owned(),
            field: field.to_owned(),
            family: family.to_owned(),
            requirement,
        });
    }

    let mut symbols = BTreeSet::new();
    for row in &rows {
        if !symbols.insert(row.symbol.as_str()) {
            return Err(GenerationError::DuplicateSymbol {
                symbol: row.symbol.clone(),
            });
        }
    }
    let mut fields = BTreeSet::new();
    for row in &rows {
        if !fields.insert(row.field.as_str()) {
            return Err(GenerationError::DuplicateField {
                field: row.field.clone(),
            });
        }
    }
    if rows.is_empty() {
        return Err(GenerationError::EmptyManifest);
    }
    Ok(rows)
}

fn is_word(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || byte == b'_'
}

/// Collapse every run of whitespace to a single space.
fn normalize_whitespace(text: &str) -> String {
    text.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// Read the identifier starting at `from`, returning it and the index after it.
fn read_ident(source: &str, from: usize) -> (&str, usize) {
    let bytes = source.as_bytes();
    let mut end = from;
    while end < bytes.len() && is_word(bytes[end]) {
        end += 1;
    }
    (&source[from..end], end)
}

fn skip_whitespace(source: &str, from: usize) -> usize {
    let bytes = source.as_bytes();
    let mut index = from;
    while index < bytes.len() && bytes[index].is_ascii_whitespace() {
        index += 1;
    }
    index
}

/// True when only whitespace separates `index` from the start of its line.
fn at_line_start(source: &str, index: usize) -> bool {
    source[..index]
        .rsplit('\n')
        .next()
        .is_none_or(|prefix| prefix.trim().is_empty())
}

/// Collect the top-level type names the bindings declare.
fn declared_types(source: &str) -> BTreeSet<String> {
    let mut declared = BTreeSet::new();
    for line in source.lines() {
        for keyword in ["pub type ", "pub struct ", "pub enum ", "pub union "] {
            if let Some(rest) = line.strip_prefix(keyword) {
                let (name, _) = read_ident(rest, 0);
                if !name.is_empty() {
                    declared.insert(name.to_owned());
                }
            }
        }
    }
    declared
}

/// Recover every `pub fn NAME(..) -> RET;` declaration from the bindings.
fn parse_signatures(source: &str) -> Result<BTreeMap<String, Signature>, GenerationError> {
    const KEYWORD: &str = "pub fn ";
    let mut signatures = BTreeMap::new();
    let mut cursor = 0usize;

    while let Some(offset) = source[cursor..].find(KEYWORD) {
        let start = cursor + offset;
        cursor = start + KEYWORD.len();
        if !at_line_start(source, start) {
            continue;
        }

        let (name, after_name) = read_ident(source, cursor);
        if name.is_empty() {
            continue;
        }
        let open = skip_whitespace(source, after_name);
        if !source[open..].starts_with('(') {
            continue;
        }
        let Some(relative_close) = source[open + 1..].find(')') else {
            continue;
        };
        let close = open + 1 + relative_close;
        let params_text = &source[open + 1..close];
        // Mirrors the `[^()]*` guard: nested parentheses mean a function
        // pointer parameter, which this simple grammar does not model.
        if params_text.contains('(') {
            continue;
        }
        let arrow = skip_whitespace(source, close + 1);
        if !source[arrow..].starts_with("->") {
            continue;
        }
        let ret_start = skip_whitespace(source, arrow + 2);
        let Some(relative_semi) = source[ret_start..].find(';') else {
            continue;
        };
        let ret = normalize_whitespace(&source[ret_start..ret_start + relative_semi]);

        let mut params = Vec::new();
        for chunk in params_text.split(',') {
            let chunk = chunk.trim();
            if chunk.is_empty() {
                continue;
            }
            let (param_name, after) = read_ident(chunk, 0);
            let colon = skip_whitespace(chunk, after);
            if param_name.is_empty() || !chunk[colon..].starts_with(':') {
                return Err(GenerationError::UnparsableParameter {
                    function: name.to_owned(),
                    chunk: chunk.to_owned(),
                });
            }
            params.push(normalize_whitespace(&chunk[colon + 1..]));
        }

        signatures.insert(name.to_owned(), Signature { params, ret });
        cursor = ret_start + relative_semi;
    }

    if signatures.is_empty() {
        return Err(GenerationError::NoFunctions);
    }
    Ok(signatures)
}

fn parse_bindings(source: &str) -> Result<Bindings, GenerationError> {
    Ok(Bindings {
        signatures: parse_signatures(source)?,
        declared: declared_types(source),
    })
}

/// Prefix types declared by the bindings with their module path.
fn qualify(rust_type: &str, declared: &BTreeSet<String>) -> String {
    let bytes = rust_type.as_bytes();
    let mut out = String::with_capacity(rust_type.len());
    let mut index = 0usize;

    while index < bytes.len() {
        if is_word(bytes[index]) {
            let (word, end) = read_ident(rust_type, index);
            if declared.contains(word) {
                out.push_str("v2_13::");
            }
            out.push_str(word);
            index = end;
        } else {
            out.push(char::from(bytes[index]));
            index += 1;
        }
    }
    out
}

/// Derive the function pointer alias from a struct field name.
#[must_use]
pub fn alias_name(field: &str) -> String {
    let mut alias = String::new();
    for part in field.split('_') {
        let mut characters = part.chars();
        if let Some(first) = characters.next() {
            alias.extend(first.to_uppercase());
            alias.push_str(&characters.as_str().to_lowercase());
        }
    }
    alias.push_str("Fn");
    alias
}

fn render_family(family: &str, loader: &Loader) -> String {
    let mut aliases = Vec::new();
    let mut uses_bindings = false;

    for entry in loader.family(family) {
        let params: Vec<String> = entry
            .signature
            .params
            .iter()
            .map(|param| qualify(param, &loader.declared))
            .collect();
        let ret = qualify(&entry.signature.ret, &loader.declared);
        uses_bindings = uses_bindings
            || ret.contains("v2_13::")
            || params.iter().any(|param| param.contains("v2_13::"));

        let mut alias = String::new();
        let _ = write!(
            alias,
            "/// Function pointer for `{}`.\npub(crate) type {} = unsafe extern \"C\" fn({}) -> {};\n",
            entry.symbol,
            entry.alias,
            params.join(", "),
            ret,
        );
        aliases.push(alias);
    }

    let mut out = String::from(BANNER);
    let _ = writeln!(out, "//! `{family}` cuTensorNet entry points.");
    if uses_bindings {
        out.push_str("\nuse crate::bindings::v2_13;\n");
    }
    out.push('\n');
    out.push_str(&aliases.join("\n"));
    out
}

fn render_root(loader: &Loader) -> String {
    let mut out = String::from(BANNER);
    out.push_str("//! The resolved cuTensorNet entry points.\n\n");
    for family in FAMILY_ORDER {
        let _ = writeln!(out, "pub(crate) mod {family};");
    }
    out.push_str(
        "\nuse super::{CUTENSORNET_NAME, SymbolResolver, resolve_optional, resolve_required};\n\
         use crate::AvailabilityError;\n\
         use std::path::Path;\n\n\
         /// Every cuTensorNet entry point the loader resolves.\n\
         #[allow(dead_code)]\n\
         pub(crate) struct CuTensorNetFunctions {\n",
    );
    for entry in loader.entries() {
        let alias = format!("{}::{}", entry.family, entry.alias);
        match entry.requirement {
            Requirement::Optional => {
                let _ = write!(
                    out,
                    "    /// Optional diagnostic only; absence must never reject discovery.\n\
                     \x20   pub(crate) {}: Option<{alias}>,\n",
                    entry.field,
                );
            }
            Requirement::Required => {
                let _ = writeln!(out, "    pub(crate) {}: {alias},", entry.field);
            }
        }
    }
    out.push_str("}\n\n");

    out.push_str(
        "#[allow(clippy::too_many_lines)]\n\
         pub(crate) fn resolve_cutensornet_functions<R: SymbolResolver>(\n\
         \x20   resolver: &R,\n\
         \x20   path: &Path,\n\
         ) -> Result<CuTensorNetFunctions, AvailabilityError> {\n\
         \x20   Ok(CuTensorNetFunctions {\n",
    );
    for entry in loader.entries() {
        match entry.requirement {
            Requirement::Optional => {
                let _ = writeln!(
                    out,
                    "        {}: resolve_optional(resolver, b\"{}\\0\"),",
                    entry.field, entry.symbol,
                );
            }
            Requirement::Required => {
                let _ = write!(
                    out,
                    "        {}: resolve_required(\n\
                     \x20           resolver,\n\
                     \x20           CUTENSORNET_NAME,\n\
                     \x20           path,\n\
                     \x20           \"{}\",\n\
                     \x20           b\"{}\\0\",\n\
                     \x20       )?,\n",
                    entry.field, entry.symbol, entry.symbol,
                );
            }
        }
    }
    out.push_str("    })\n}\n");
    out
}

/// Serialize a validated [`Loader`] into unformatted source files.
///
/// This step is pure text assembly and cannot fail: every consistency check
/// already happened in [`Loader::build`]. The output is deliberately *not*
/// formatted, because reproducing rustfmt's line-wrapping and token placement
/// here would be a maintenance trap. Callers pipe the text through rustfmt.
#[must_use]
pub fn serialize(loader: &Loader) -> Vec<GeneratedFile> {
    let mut files = vec![GeneratedFile {
        path: "symbols.rs".to_owned(),
        contents: render_root(loader),
    }];
    files.extend(FAMILY_ORDER.into_iter().map(|family| GeneratedFile {
        path: format!("symbols/{family}.rs"),
        contents: render_family(family, loader),
    }));
    files
}

/// Build the loader from the manifest and bindings, then serialize it.
pub fn render(manifest: &str, bindings: &str) -> Result<Vec<GeneratedFile>, GenerationError> {
    Ok(serialize(&Loader::build(manifest, bindings)?))
}

#[cfg(test)]
mod tests {
    use super::{
        FAMILY_ORDER, GeneratedFile, GenerationError, Loader, Requirement, Signature, alias_name,
        parse_manifest, serialize,
    };
    use std::fmt::Write as _;

    /// A miniature `v2_13.rs`. `fnPlain` deliberately mentions no declared type
    /// so the import it does *not* need can be asserted on.
    const BINDINGS: &str = r#"
pub type cutensornetHandle_t = *mut ::std::os::raw::c_void;
pub type cutensornetStatus_t = ::std::os::raw::c_uint;
pub struct cutensornetState_t {
    _unused: [u8; 0],
}

unsafe extern "C" {
    pub fn fnContext(handle: cutensornetHandle_t) -> cutensornetStatus_t;
    pub fn fnState(handle: cutensornetHandle_t, state: *mut cutensornetState_t)
        -> cutensornetStatus_t;
    pub fn fnWorkspace(handle: cutensornetHandle_t) -> cutensornetStatus_t;
    pub fn fnOperator(handle: cutensornetHandle_t) -> cutensornetStatus_t;
    pub fn fnExpectation(handle: cutensornetHandle_t) -> cutensornetStatus_t;
    pub fn fnSampler(handle: cutensornetHandle_t) -> cutensornetStatus_t;
    pub fn fnContraction(handle: cutensornetHandle_t) -> cutensornetStatus_t;
    pub fn fnPlain(count: i32) -> i32;
}
"#;

    /// One row per family, which is the minimum [`Loader::build`] accepts.
    fn manifest() -> String {
        let mut out = String::new();
        for family in FAMILY_ORDER {
            let alias = alias_name(family);
            let suffix = alias.trim_end_matches("Fn");
            let _ = writeln!(out, "fn{suffix} do_{family} {family} required");
        }
        out
    }

    fn loader(extra: &str) -> Loader {
        Loader::build(&format!("{}{extra}", manifest()), BINDINGS).expect("fixture should build")
    }

    // -- the model ---------------------------------------------------------
    //
    // These assert on what the loader *means*: which symbols exist, what they
    // are called, and what signature they are called through. None of them
    // depend on how the loader is written out.

    #[test]
    fn joins_each_manifest_row_to_its_declared_signature() {
        let loader = loader("");
        let entry = loader.entry("fnState").expect("fnState should be an entry");

        assert_eq!(entry.field, "do_state");
        assert_eq!(entry.family, "state");
        assert_eq!(entry.requirement, Requirement::Required);
        assert_eq!(entry.alias, "DoStateFn");
        assert_eq!(
            entry.signature,
            Signature {
                params: vec![
                    "cutensornetHandle_t".to_owned(),
                    "*mut cutensornetState_t".to_owned(),
                ],
                ret: "cutensornetStatus_t".to_owned(),
            },
        );
    }

    /// Signatures come from the bindings, never from the manifest, so a
    /// function pointer cannot disagree with the header it is resolved against.
    ///
    /// The hand-written loader this generator replaced declared three
    /// parameters of `cutensornetNetworkOperatorAppendProduct` as
    /// `*const *const T` where the header says `*mut *const T`. Constness does
    /// not affect the ABI, so it never failed at runtime and nothing compared
    /// the two.
    #[test]
    fn preserves_pointer_mutability_exactly_as_declared() {
        let bindings = format!(
            "{BINDINGS}\nunsafe extern \"C\" {{\n    \
             pub fn fnPointers(a: *mut *const i32, b: *const *const ::std::os::raw::c_void) \
             -> cutensornetStatus_t;\n}}\n"
        );
        let loader = Loader::build(
            &format!("{}fnPointers do_pointers state required\n", manifest()),
            &bindings,
        )
        .expect("fixture should build");

        assert_eq!(
            loader
                .entry("fnPointers")
                .expect("fnPointers should be an entry")
                .signature
                .params,
            vec![
                "*mut *const i32".to_owned(),
                "*const *const ::std::os::raw::c_void".to_owned(),
            ],
        );
    }

    #[test]
    fn keeps_entries_in_manifest_order_and_groups_them_by_family() {
        let loader = loader("fnPlain do_plain state required\n");
        let symbols: Vec<&str> = loader
            .entries()
            .iter()
            .map(|entry| entry.symbol.as_str())
            .collect();
        assert_eq!(symbols.last(), Some(&"fnPlain"));

        let state: Vec<&str> = loader
            .family("state")
            .iter()
            .map(|entry| entry.field.as_str())
            .collect();
        assert_eq!(state, vec!["do_state", "do_plain"]);
        assert!(loader.family("nowhere").is_empty());
    }

    #[test]
    fn records_whether_a_symbol_is_optional() {
        let loader = loader("fnPlain do_plain sampler optional\n");
        assert_eq!(
            loader
                .entry("fnPlain")
                .expect("fnPlain should be an entry")
                .requirement,
            Requirement::Optional,
        );
    }

    #[test]
    fn derives_alias_names_from_field_names() {
        assert_eq!(alias_name("append_product"), "AppendProductFn");
        assert_eq!(alias_name("get_cudart_version"), "GetCudartVersionFn");
        assert_eq!(alias_name("finalize_mps"), "FinalizeMpsFn");
    }

    #[test]
    fn ignores_comments_and_blank_lines() {
        let source = format!("# leading comment\n\n{}   \n# trailing\n", manifest());
        let rows = parse_manifest(&source).expect("comments should be ignored");
        assert_eq!(rows.len(), FAMILY_ORDER.len());
        assert_eq!(rows[0].requirement, Requirement::Required);
    }

    // -- rejected inputs ---------------------------------------------------

    #[test]
    fn rejects_a_row_without_four_columns() {
        let source = format!("{}fnPlain do_plain sampler\n", manifest());
        assert_eq!(
            parse_manifest(&source),
            Err(GenerationError::ColumnCount { line: 8, found: 3 }),
        );
    }

    #[test]
    fn rejects_an_unknown_family() {
        let source = format!("{}fnPlain do_plain nowhere required\n", manifest());
        assert_eq!(
            parse_manifest(&source),
            Err(GenerationError::UnknownFamily {
                line: 8,
                family: "nowhere".to_owned(),
            }),
        );
    }

    #[test]
    fn rejects_an_unknown_requirement() {
        let source = format!("{}fnPlain do_plain sampler maybe\n", manifest());
        assert_eq!(
            parse_manifest(&source),
            Err(GenerationError::UnknownRequirement {
                line: 8,
                requirement: "maybe".to_owned(),
            }),
        );
    }

    #[test]
    fn rejects_a_duplicate_symbol() {
        let source = format!("{}fnContext do_other sampler required\n", manifest());
        assert_eq!(
            parse_manifest(&source),
            Err(GenerationError::DuplicateSymbol {
                symbol: "fnContext".to_owned(),
            }),
        );
    }

    #[test]
    fn rejects_a_duplicate_field() {
        let source = format!("{}fnPlain do_context sampler required\n", manifest());
        assert_eq!(
            parse_manifest(&source),
            Err(GenerationError::DuplicateField {
                field: "do_context".to_owned(),
            }),
        );
    }

    #[test]
    fn rejects_an_empty_manifest() {
        assert_eq!(
            parse_manifest("# nothing but a comment\n"),
            Err(GenerationError::EmptyManifest),
        );
    }

    #[test]
    fn rejects_a_symbol_the_bindings_do_not_declare() {
        let source = format!("{}fnAbsent do_absent sampler required\n", manifest());
        assert_eq!(
            Loader::build(&source, BINDINGS),
            Err(GenerationError::MissingSymbols {
                symbols: vec!["fnAbsent".to_owned()],
            }),
        );
    }

    #[test]
    fn rejects_a_family_with_no_symbols() {
        let mut source = String::new();
        for line in manifest()
            .lines()
            .filter(|line| !line.contains(" sampler "))
        {
            let _ = writeln!(source, "{line}");
        }
        assert_eq!(
            Loader::build(&source, BINDINGS),
            Err(GenerationError::EmptyFamily {
                family: "sampler".to_owned(),
            }),
        );
    }

    #[test]
    fn rejects_bindings_with_no_functions() {
        assert_eq!(
            Loader::build(&manifest(), "pub type cutensornetHandle_t = usize;\n"),
            Err(GenerationError::NoFunctions),
        );
    }

    #[test]
    fn rejects_a_parameter_that_is_not_named() {
        let bindings = "unsafe extern \"C\" {\n    \
                        pub fn fnContext(*mut cutensornetHandle_t) -> i32;\n}\n";
        assert_eq!(
            Loader::build(&manifest(), bindings),
            Err(GenerationError::UnparsableParameter {
                function: "fnContext".to_owned(),
                chunk: "*mut cutensornetHandle_t".to_owned(),
            }),
        );
    }

    // -- serialization -----------------------------------------------------
    //
    // A handful of tests for the text layer, kept separate from the model and
    // deliberately shallow: the authoritative check that the emitted text is
    // correct is the drift test in `lib.rs`, which formats this output with
    // rustfmt and compares it byte for byte against the checked-in loader.

    fn file<'a>(files: &'a [GeneratedFile], path: &str) -> &'a str {
        files
            .iter()
            .find(|file| file.path == path)
            .map_or("", |file| file.contents.as_str())
    }

    #[test]
    fn writes_one_file_per_family_plus_the_root() {
        let paths: Vec<String> = serialize(&loader(""))
            .into_iter()
            .map(|file| file.path)
            .collect();
        assert_eq!(
            paths,
            vec![
                "symbols.rs",
                "symbols/context.rs",
                "symbols/state.rs",
                "symbols/workspace.rs",
                "symbols/operator.rs",
                "symbols/expectation.rs",
                "symbols/sampler.rs",
                "symbols/contraction.rs",
            ],
        );
    }

    /// The module path is applied here, not in the model, and only to types the
    /// bindings actually declare.
    #[test]
    fn qualifies_only_the_types_the_bindings_declare() {
        let files = serialize(&loader(""));
        let state = file(&files, "symbols/state.rs");
        assert!(state.contains("use crate::bindings::v2_13;"));
        assert!(state.contains(
            "pub(crate) type DoStateFn = unsafe extern \"C\" fn(v2_13::cutensornetHandle_t, \
             *mut v2_13::cutensornetState_t) -> v2_13::cutensornetStatus_t;"
        ));
    }

    #[test]
    fn emits_a_field_and_a_resolve_call_for_every_entry() {
        let root = serialize(&loader("fnPlain do_plain sampler required\n"));
        let root = file(&root, "symbols.rs");
        assert!(root.contains("pub(crate) do_plain: sampler::DoPlainFn,"));
        assert!(root.contains(r#"b"fnPlain\0","#));
    }

    #[test]
    fn emits_optional_entries_as_options() {
        let root = serialize(&loader("fnPlain do_plain sampler optional\n"));
        let root = file(&root, "symbols.rs");
        assert!(root.contains("pub(crate) do_plain: Option<sampler::DoPlainFn>,"));
        assert!(root.contains(r#"do_plain: resolve_optional(resolver, b"fnPlain\0"),"#));
    }
}
