[package]
name = "qsc_qasm3"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bitflags = { workspace = true }
num-bigint = { workspace = true }
miette = { workspace = true }
qsc = { path = "../qsc" }
rustc-hash = { workspace = true }
thiserror = { workspace = true }
oq3_source_file = { workspace = true }
oq3_syntax = { workspace = true }
oq3_parser = { workspace = true }
oq3_lexer = { workspace = true }
oq3_semantics = { workspace = true }

[dev-dependencies]
difference = { workspace = true }
expect-test = { workspace = true }
indoc = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
# Self import adding fs feature so that we can test
# loading qasm from file.
qsc_qasm3 = { path = ".", features = ["fs"] }

[features]
fs = []

[lints]
workspace = true
