[package]
name = "qsc_frontend"
version = "0.0.0"
edition = "2021"

[dependencies]
enum-iterator = "1.2.0"
num-bigint = "0.4.3"
qsc_ast = { path = "../qsc_ast" }

[dev-dependencies]
expect-test = "1.4.0"
indoc = "2.0.0"
