[package]
name = "fuzz"
publish = false

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { workspace = true, optional = true }
qsc = { path = "../compiler/qsc" }

[features]
do_fuzz = [ "dep:libfuzzer-sys" ]

[lints]
workspace = true

[[bin]]
name = "compile"
path = "fuzz_targets/compile.rs"
test = false
doc = false
