[package]
name = "qsi"
version = "0.0.0"
description = "Q# Interactive"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
qsc_ast = { path = "../qsc_ast" }
qsc_eval = { path = "../qsc_eval" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_passes = { path = "../qsc_passes" }
clap = { workspace = true, features = ["derive"] }
miette = { workspace = true, features = ["fancy"] }
thiserror = { workspace = true }

[[bin]]
name = "qsi"
bench = false
