// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

import {
  KATEX_MAIN_REGULAR_WOFF2,
  KATEX_MATH_ITALIC_WOFF2,
} from "./circuitSvgFonts.js";
import {
  createSvgElement,
  removeSvgAttributes,
  removeSvgElements,
  serializeSvgElement,
  SvgElement,
} from "./svg.js";
import {
  type CircuitSvgDocumentOptions,
  type CircuitSvgFontMode,
  validateCircuitSvgDocumentOptions,
} from "./circuitSvgOptions.js";

const EXPORT_CLASS = "qdk-circuit-export";
const DEFAULT_TITLE = "Quantum circuit";
const DEFAULT_DESCRIPTION =
  "Quantum circuit diagram generated by Microsoft QDK.";

export function createStandaloneCircuitSvg(
  source: SvgElement,
  options: CircuitSvgDocumentOptions = {},
): string {
  validateCircuitSvgDocumentOptions(options);
  if (source.tagName !== "svg" || !source.classList.contains("qviz")) {
    throw new Error("Expected an SVG produced by the QDK circuit renderer.");
  }

  removeSvgElements(source, (element) =>
    element.classList.contains("gate-control"),
  );
  removeSvgAttributes(source, (name) => name.startsWith("data-"));

  const width = readDimension(source, "width");
  const height = readDimension(source, "height");
  const titleText = options.title?.trim() || DEFAULT_TITLE;
  const descriptionText = options.description?.trim() || DEFAULT_DESCRIPTION;
  const idPrefix = options.idPrefix ?? "qdk-circuit";
  const titleId = `${idPrefix}-title`;
  const descriptionId = `${idPrefix}-description`;
  const background = options.background ?? "transparent";
  const fontMode = options.fontMode ?? "embed";

  source.classList.add(EXPORT_CLASS);
  source.setAttribute("xmlns", "http://www.w3.org/2000/svg");
  source.setAttribute("version", "1.1");
  source.setAttribute("viewBox", `0 0 ${width} ${height}`);
  source.setAttribute("preserveAspectRatio", "xMinYMin meet");
  source.setAttribute("role", "img");
  source.setAttribute("aria-labelledby", `${titleId} ${descriptionId}`);

  const renderedChildren = [...source.children];
  source.replaceChildren();

  const title = createSvgElement("title", { id: titleId });
  title.appendText(titleText);
  source.appendChild(title);

  const description = createSvgElement("desc", { id: descriptionId });
  description.appendText(descriptionText);
  source.appendChild(description);

  const style = createSvgElement("style", { type: "text/css" });
  style.appendText(buildStyle(fontMode));
  source.appendChild(style);

  if (background === "solid") {
    source.appendChild(
      createSvgElement("rect", {
        class: "qdk-circuit-export-background",
        x: "0",
        y: "0",
        width: width.toString(),
        height: height.toString(),
      }),
    );
  }

  for (const child of renderedChildren) {
    if (typeof child !== "string") {
      source.appendChild(child);
    }
  }

  return `<?xml version="1.0" encoding="UTF-8"?>\n${serializeSvgElement(source)}\n`;
}

function readDimension(source: SvgElement, name: "width" | "height"): number {
  const raw = source.getAttribute(name);
  const value = raw === null ? Number.NaN : Number(raw);
  if (!Number.isFinite(value) || value < 0) {
    throw new Error(`Circuit SVG has an invalid ${name} "${raw ?? ""}".`);
  }
  return value;
}

function buildStyle(fontMode: CircuitSvgFontMode): string {
  const mainFont =
    fontMode === "embed" ? '"QDKCircuitMain"' : '"KaTeX_Main",serif';
  const mathFont =
    fontMode === "embed" ? '"QDKCircuitMath"' : '"KaTeX_Math",serif';
  const fontFaces =
    fontMode === "embed"
      ? `@font-face{font-family:"QDKCircuitMain";src:url(data:font/woff2;base64,${KATEX_MAIN_REGULAR_WOFF2}) format("woff2");font-style:normal;font-weight:400}` +
        `@font-face{font-family:"QDKCircuitMath";src:url(data:font/woff2;base64,${KATEX_MATH_ITALIC_WOFF2}) format("woff2");font-style:italic;font-weight:400}`
      : "";

  return (
    fontFaces +
    `.${EXPORT_CLASS}{color:#222}` +
    `.${EXPORT_CLASS} line,.${EXPORT_CLASS} circle,.${EXPORT_CLASS} rect{stroke:currentColor;stroke-width:1}` +
    `.${EXPORT_CLASS} text{fill:currentColor;text-anchor:middle;dominant-baseline:middle}` +
    `.${EXPORT_CLASS} .qs-maintext{font-family:${mainFont};font-style:normal;font-weight:400}` +
    `.${EXPORT_CLASS} .qs-mathtext{font-family:${mathFont};font-style:italic;font-weight:400}` +
    `.${EXPORT_CLASS} .hidden{display:none}` +
    `.${EXPORT_CLASS} .register-classical{stroke-width:.5}` +
    `.${EXPORT_CLASS} .arg-button{text-decoration:none;word-spacing:-.2em}` +
    `.${EXPORT_CLASS} .gate .qs-group-label{text-anchor:start}` +
    `.${EXPORT_CLASS} .control-line,.${EXPORT_CLASS} .control-dot{fill:currentColor}` +
    `.${EXPORT_CLASS} .anti-control-dot{fill:#fff;stroke:currentColor;stroke-width:2}` +
    `.${EXPORT_CLASS} .oplus>circle{fill:#fff;stroke:currentColor;stroke-width:2}` +
    `.${EXPORT_CLASS} .oplus>line{stroke:currentColor;stroke-width:2}` +
    `.${EXPORT_CLASS} rect.gate-swap{fill:transparent;stroke:transparent}` +
    `.${EXPORT_CLASS} .gate-unitary{fill:#fff;stroke:currentColor}` +
    `.${EXPORT_CLASS} .gate text{fill:#3b3b3b}` +
    `.${EXPORT_CLASS} .gate-measure{fill:#005fb8;stroke:currentColor}` +
    `.${EXPORT_CLASS} .arc-measure,.${EXPORT_CLASS} .qs-line-measure{fill:none;stroke:#fff}` +
    `.${EXPORT_CLASS} .gate-ket{fill:#005fb8;stroke:currentColor}` +
    `.${EXPORT_CLASS} text.ket-text{fill:#fff;stroke:none}` +
    `.${EXPORT_CLASS} .classically-controlled-btn circle{fill:#fff;stroke-width:1}` +
    `.${EXPORT_CLASS} .classically-controlled-btn text{font-family:${mainFont};fill:currentColor;stroke:none}` +
    `.${EXPORT_CLASS} .qdk-circuit-export-background{fill:#fff;stroke:none}`
  );
}
