[package]
name = "qdk_cutensornet"

version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libloading = { workspace = true }
num-complex = { workspace = true }
qdk_simulators = { path = "../simulators", default-features = false }
thiserror = { workspace = true }

[lints]
workspace = true

[lib]
doctest = false