// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Rich, read-only Python projections of the semantic `OpenQASM` AST.
//!
//! Where [`super::nodes`] projects the *syntactic* tree, this module projects
//! the *semantic* tree produced by [`qdk_openqasm::analyze_source`]. The
//! semantic tree carries resolved type and const-value information. Each class
//! keeps a `Sem`-prefixed Rust identifier but is presented to Python under a
//! clean, un-prefixed name inside the `qdk.openqasm.semantic` module (for
//! example Rust `SemGateCall` -> Python `QuantumGate`). Isolating the family in
//! a submodule lets it use the un-prefixed names without colliding with the
//! syntax layer's `openqasm3`-parity names in the flat `qdk._native` module.
//!
//! * [`SemExpr`] (Python `SemanticExpression`) is the base of every semantic
//!   expression. It extends [`Expression`] (and therefore `QASMNode`) and adds
//!   `ty`, `const_value`, and `symbol` accessors.
//! * [`SemStmt`] (Python `SemanticStatement`) is the base of every semantic
//!   statement. It extends [`Statement`] (and therefore `QASMNode`) and adds an
//!   `annotations` accessor. Annotations are also reported by `children()`,
//!   ahead of the statement's own children, so a generic walk reaches them.
//! * [`SemProgram`] (Python `Program`) is the root of a semantic program.
//!
//! Concrete per-variant leaf classes are generated by the [`qasm_node!`] macro
//! and expose *named*, typed accessors for their children (for example
//! `SemBinaryOpExpr.lhs` / `.rhs` / `.op`, presented to Python as
//! `BinaryExpression`) plus a uniform `children()` method for generic
//! traversal. There is intentionally no `kind` discriminant; callers dispatch
//! via `isinstance` and `type(node).__name__`.
//!
//! The resolved [`SymbolTable`] is projected as [`SemSymbolTable`], an iterable
//! collection of [`SemSymbol`] views, and types are projected as opaque
//! [`SemType`] values.
//!
//! All projections are eagerly materialized into owned, frozen values (scalars
//! plus `Py<PyAny>` references to already-built children), so they are
//! `Send + Sync` and hold no borrow into the Rust analysis result.
//!
//! ## Semantic name to variant table
//!
//! The mapping below is the single source of truth for the semantic AST
//! variants, their `Sem`-prefixed Rust identifiers, and the clean Python names
//! they present in the `qdk.openqasm.semantic` module. It is kept in sync
//! with `qdk_openqasm::semantic::ast`.
//!
//! Statements (`StmtKind` -> Rust ident -> Python name):
//! * `Alias` -> `SemAliasDecl` -> `AliasStatement`
//! * `Assign` -> `SemAssign` -> `ClassicalAssignment`
//! * `Barrier` -> `SemBarrier` -> `QuantumBarrier`
//! * `Box` -> `SemBox` -> `Box`
//! * `Block` -> `SemBlock` -> `CompoundStatement`
//! * `Break` -> `SemBreak` -> `BreakStatement`
//! * `Calibration` -> `SemCalibration` -> `CalibrationStatement`
//! * `CalibrationGrammar` -> `SemCalibrationGrammar` -> `CalibrationGrammarDeclaration`
//! * `ClassicalDecl` -> `SemClassicalDecl` -> `ClassicalDeclaration`
//! * `Continue` -> `SemContinue` -> `ContinueStatement`
//! * `Def` -> `SemDef` -> `SubroutineDefinition`
//! * `DefCal` -> `SemDefCal` -> `CalibrationDefinition`
//! * `Delay` -> `SemDelay` -> `DelayInstruction`
//! * `End` -> `SemEnd` -> `EndStatement`
//! * `ExprStmt` -> `SemExprStmt` -> `ExpressionStatement`
//! * `ExternDecl` -> `SemExternDecl` -> `ExternDeclaration`
//! * `For` -> `SemForLoop` -> `ForInLoop`
//! * `GateCall` -> `SemGateCall` -> `QuantumGate`
//! * `If` -> `SemIfStmt` -> `BranchingStatement`
//! * `IndexedAssign` -> `SemIndexedAssign` -> `IndexedClassicalAssignment`
//! * `InputDeclaration` -> `SemInputDeclaration` -> `InputDeclaration`
//! * `OutputDeclaration` -> `SemOutputDeclaration` -> `OutputDeclaration`
//! * `Pragma` -> `SemPragma` -> `Pragma`
//! * `QuantumGateDefinition` -> `SemGateDefinition` -> `QuantumGateDefinition`
//! * `QubitDecl` -> `SemQubitDecl` -> `QubitDeclaration`
//! * `QubitArrayDecl` -> `SemQubitArrayDecl` -> `QubitArrayDeclaration`
//! * `Reset` -> `SemReset` -> `QuantumReset`
//! * `Return` -> `SemReturn` -> `ReturnStatement`
//! * `Switch` -> `SemSwitch` -> `SwitchStatement`
//! * `WhileLoop` -> `SemWhileLoop` -> `WhileLoop`
//! * `Err` -> `SemErrStmt` -> `ErrorStatement`
//!
//! Expressions (`ExprKind` -> Rust ident -> Python name):
//! * `Err` -> `SemErrExpr` -> `ErrorExpression`
//! * `ResolvedIdent` -> `SemResolvedIdent` -> `Identifier`
//! * `CapturedResolvedIdent` -> `SemCapturedResolvedIdent` -> `CapturedIdentifier`
//! * `UnaryOp` -> `SemUnaryOpExpr` -> `UnaryExpression`
//! * `BinaryOp` -> `SemBinaryOpExpr` -> `BinaryExpression`
//! * `Lit` -> `SemLiteral` -> `LiteralExpression`
//! * `ResolvedFunctionCall` -> `SemFunctionCall` -> `FunctionCall`
//! * `BuiltinFunctionCall` -> `SemBuiltinFunctionCall` -> `BuiltinFunctionCall`
//! * `Cast` -> `SemCast` -> `Cast`
//! * `IndexedExpr` -> `SemIndexedExpr` -> `IndexExpression`
//! * `Paren` -> `SemParen` -> `ParenExpression`
//! * `Measure` -> `SemMeasure` -> `QuantumMeasurement`
//! * `RuntimeSizeof` -> `SemRuntimeSizeof` -> `RuntimeSizeof`
//! * `EvaluatedDurationof` -> `SemEvaluatedDurationof` -> `DurationOf`
//! * `Concat` -> `SemConcat` -> `Concatenation`
//!
//! The shared category bases and projections are `SemExpr` ->
//! `SemanticExpression`, `SemStmt` -> `SemanticStatement`, `SemProgram` ->
//! `Program`, `SemType` -> `Type`,
//! `SemSymbol` -> `Symbol`, and `SemSymbolTable` -> `SymbolTable`.
//!
//! Gate operands of the hardware-qubit form are projected as
//! [`SemHardwareQubit`] (Python `HardwareQubit`) so that no operand is silently
//! dropped.

use crate::openqasm::nodes::{Annotation, Expression, QASMNode, Statement};
use crate::openqasm::repr::{py_bool, py_float, py_items, py_str};
use crate::openqasm::source::SourceDocument;
use crate::openqasm::span::Span;
use crate::openqasm::syntax::{
    AccessControl, BinaryOperator, GateModifierName, TimeUnit, UnaryOperator,
};
use pyo3::IntoPyObjectExt;
use pyo3::exceptions::PyValueError;
use pyo3::prelude::*;
use pyo3::types::{PyComplex, PyList};
use qdk_openqasm::parser::ast::PathKind;
use qdk_openqasm::semantic::ast::{self as sem, ExprKind, LiteralKind, StmtKind};
use qdk_openqasm::semantic::broadcast::{ScalarGateCall, expand_gate_call};
use qdk_openqasm::semantic::symbols::{IOKind as CoreIOKind, Symbol, SymbolId, SymbolTable};
use qdk_openqasm::semantic::types::{ArrayDimensions, Type as CoreType};
use rustc_hash::FxHashMap;
use std::cell::RefCell;

/// State shared by every builder for the duration of one analysis projection.
///
/// The caches are the reason this exists. `build_type` and `build_sem_symbol`
/// are pure functions of the resolved data they project, and a program refers to
/// the same handful of types and symbols thousands of times, so without
/// interning a 320,000-node tree carried roughly 260,000 type objects for a
/// handful of distinct values and one symbol object per identifier occurrence.
pub(crate) struct BuildContext<'a> {
    symbols: &'a SymbolTable,
    types: RefCell<FxHashMap<CoreType, Py<PyAny>>>,
    symbol_nodes: RefCell<FxHashMap<u32, Py<SemSymbol>>>,
}

impl<'a> BuildContext<'a> {
    pub(crate) fn new(symbols: &'a SymbolTable) -> Self {
        Self {
            symbols,
            types: RefCell::new(FxHashMap::default()),
            symbol_nodes: RefCell::new(FxHashMap::default()),
        }
    }

    /// Returns the shared node for an already-projected type, if there is one.
    fn cached_type(&self, py: Python<'_>, ty: &CoreType) -> Option<Py<PyAny>> {
        self.types.borrow().get(ty).map(|node| node.clone_ref(py))
    }

    fn cache_type(&self, py: Python<'_>, ty: &CoreType, node: &Py<PyAny>) {
        self.types
            .borrow_mut()
            .insert(ty.clone(), node.clone_ref(py));
    }

    fn cached_symbol(&self, py: Python<'_>, id: u32) -> Option<Py<SemSymbol>> {
        self.symbol_nodes
            .borrow()
            .get(&id)
            .map(|node| node.clone_ref(py))
    }

    fn cache_symbol(&self, py: Python<'_>, id: u32, node: &Py<SemSymbol>) {
        self.symbol_nodes
            .borrow_mut()
            .insert(id, node.clone_ref(py));
    }
}

// ----------------------------------------------------------------------------
// Shared value enums
// ----------------------------------------------------------------------------

/// Whether a cast was written in the source or inserted by the analyzer.
#[pyclass(
    module = "qdk.openqasm.semantic",
    eq,
    eq_int,
    frozen,
    hash,
    from_py_object
)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub(crate) enum CastKind {
    #[pyo3(name = "EXPLICIT")]
    Explicit,
    #[pyo3(name = "IMPLICIT")]
    Implicit,
}

impl CastKind {
    fn variant_name(self) -> &'static str {
        match self {
            Self::Explicit => "EXPLICIT",
            Self::Implicit => "IMPLICIT",
        }
    }
}

impl From<sem::CastKind> for CastKind {
    fn from(kind: sem::CastKind) -> Self {
        match kind {
            sem::CastKind::Explicit => Self::Explicit,
            sem::CastKind::Implicit => Self::Implicit,
        }
    }
}

#[pymethods]
impl CastKind {
    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __str__(&self) -> &'static str {
        (*self).variant_name()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __repr__(&self) -> String {
        format!("CastKind.{}", (*self).variant_name())
    }
}

/// Whether a symbol is a program input, a program output, or neither.
#[pyclass(
    module = "qdk.openqasm.semantic",
    eq,
    eq_int,
    frozen,
    hash,
    from_py_object
)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub(crate) enum IOKind {
    #[pyo3(name = "DEFAULT")]
    Default,
    #[pyo3(name = "INPUT")]
    Input,
    #[pyo3(name = "OUTPUT")]
    Output,
}

impl IOKind {
    fn variant_name(self) -> &'static str {
        match self {
            Self::Default => "DEFAULT",
            Self::Input => "INPUT",
            Self::Output => "OUTPUT",
        }
    }
}

impl From<CoreIOKind> for IOKind {
    fn from(kind: CoreIOKind) -> Self {
        match kind {
            CoreIOKind::Default => Self::Default,
            CoreIOKind::Input => Self::Input,
            CoreIOKind::Output => Self::Output,
        }
    }
}

#[pymethods]
impl IOKind {
    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __str__(&self) -> &'static str {
        (*self).variant_name()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __repr__(&self) -> String {
        format!("IOKind.{}", (*self).variant_name())
    }
}

impl From<sem::BinOp> for BinaryOperator {
    fn from(op: sem::BinOp) -> Self {
        match op {
            sem::BinOp::Add => Self::Add,
            sem::BinOp::Sub => Self::Sub,
            sem::BinOp::Mul => Self::Mul,
            sem::BinOp::Div => Self::Div,
            sem::BinOp::Mod => Self::Mod,
            sem::BinOp::Exp => Self::Pow,
            sem::BinOp::Eq => Self::Eq,
            sem::BinOp::Neq => Self::Neq,
            sem::BinOp::Gt => Self::Gt,
            sem::BinOp::Gte => Self::Gte,
            sem::BinOp::Lt => Self::Lt,
            sem::BinOp::Lte => Self::Lte,
            sem::BinOp::AndL => Self::LogicAnd,
            sem::BinOp::OrL => Self::LogicOr,
            sem::BinOp::AndB => Self::BitAnd,
            sem::BinOp::OrB => Self::BitOr,
            sem::BinOp::XorB => Self::BitXor,
            sem::BinOp::Shl => Self::Shl,
            sem::BinOp::Shr => Self::Shr,
        }
    }
}

impl From<sem::UnaryOp> for UnaryOperator {
    fn from(op: sem::UnaryOp) -> Self {
        match op {
            sem::UnaryOp::Neg => Self::Neg,
            sem::UnaryOp::NotB => Self::BitNot,
            sem::UnaryOp::NotL => Self::LogicNot,
        }
    }
}

impl From<&sem::GateModifierKind> for GateModifierName {
    fn from(kind: &sem::GateModifierKind) -> Self {
        match kind {
            sem::GateModifierKind::Inv => Self::Inv,
            sem::GateModifierKind::Pow(_) => Self::Pow,
            sem::GateModifierKind::Ctrl(_) => Self::Ctrl,
            sem::GateModifierKind::NegCtrl(_) => Self::NegCtrl,
        }
    }
}

impl From<sem::TimeUnit> for TimeUnit {
    fn from(unit: sem::TimeUnit) -> Self {
        match unit {
            sem::TimeUnit::Dt => Self::Dt,
            sem::TimeUnit::Ns => Self::Ns,
            sem::TimeUnit::Us => Self::Us,
            sem::TimeUnit::Ms => Self::Ms,
            sem::TimeUnit::S => Self::S,
        }
    }
}

// ----------------------------------------------------------------------------
// Constant value projections
// ----------------------------------------------------------------------------

/// A constant angle value, stored as OpenQASM stores it: a fixed-point integer.
///
/// An `angle[n]` divides a full turn into `2 ** n` equal steps, so `value` counts
/// steps and `size` is `n`. This class is what a semantic `const_value` holds for
/// an angle literal. It carries no source position and is not part of the node
/// tree.
#[pyclass(
    name = "Angle",
    module = "qdk.openqasm.semantic",
    frozen,
    skip_from_py_object
)]
#[derive(Clone, Copy, Debug)]
pub(crate) struct Angle {
    /// The fixed-point numerator, in units of a full turn divided by `2 ** size`.
    #[pyo3(get)]
    value: u64,
    /// The number of bits `value` is expressed in.
    ///
    /// This is the precision the analyzer folded the constant at, not the width
    /// written in the source. A `const angle[4]` is folded at the full 53 bits a
    /// float carries; the declared width is on the expression's `ty`.
    #[pyo3(get)]
    size: u32,
    /// The angle in radians, in the range `[0, 2 * pi)`.
    ///
    /// Derived from `value` and `size` rather than stored by the analyzer, so it
    /// is lossy whenever `size` exceeds the 53 bits a Python float can hold. It
    /// is `nan` when `size` exceeds 64, which no representable angle reaches.
    #[pyo3(get)]
    radians: f64,
}

impl Angle {
    fn from_core(angle: qdk_openqasm::stdlib::angle::Angle) -> Self {
        Angle {
            value: angle.value,
            size: angle.size,
            radians: angle.try_into().unwrap_or(f64::NAN),
        }
    }
}

#[pymethods]
impl Angle {
    #[new]
    fn new(value: u64, size: u32) -> Self {
        Self::from_core(qdk_openqasm::stdlib::angle::Angle::new(value, size))
    }

    fn __repr__(&self) -> String {
        format!(
            "Angle(value={}, size={}, radians={})",
            self.value,
            self.size,
            py_float(self.radians)
        )
    }

    // `radians` is derived from the pair, and is `nan` for a size beyond 64,
    // which would make such an angle unequal to itself.
    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(slf.as_any(), other, &["value", "size"])
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(slf.as_any(), &["value", "size"])
    }
}

/// A constant duration value: a magnitude paired with the unit it was written in.
///
/// The unit is preserved rather than normalized, because `TimeUnit.DT` is a
/// backend-defined cycle time that cannot be converted without knowing the
/// target. This class is what a semantic `const_value` holds for a duration
/// literal. It carries no source position and is not part of the node tree.
#[pyclass(
    name = "Duration",
    module = "qdk.openqasm.semantic",
    frozen,
    skip_from_py_object
)]
#[derive(Clone, Copy, Debug)]
pub(crate) struct Duration {
    /// The magnitude, expressed in `unit`.
    #[pyo3(get)]
    value: f64,
    /// The unit the duration was written in.
    #[pyo3(get)]
    unit: TimeUnit,
}

#[pymethods]
impl Duration {
    #[new]
    fn new(value: f64, unit: TimeUnit) -> Self {
        Duration { value, unit }
    }

    fn __repr__(&self) -> String {
        format!(
            "Duration(value={}, unit={})",
            py_float(self.value),
            self.unit.py_repr()
        )
    }

    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(slf.as_any(), other, &["value", "unit"])
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(slf.as_any(), &["value", "unit"])
    }
}

// ----------------------------------------------------------------------------
// Type / Symbol / SymbolTable projections
// ----------------------------------------------------------------------------

/// The abstract base of every resolved semantic type.
///
/// A resolved type is analysis output, not syntax, so it carries no source
/// position and is not a `QASMNode`. Dispatch over the concrete subclasses with
/// `isinstance`; `name` remains available as the textual rendering.
#[pyclass(name = "Type", module = "qdk.openqasm.semantic", subclass, frozen)]
pub(crate) struct SemType {
    /// The type's textual rendering, for example `"int[32]"` or `"qubit"`.
    #[pyo3(get)]
    name: String,
    /// Whether the type is compile-time constant.
    #[pyo3(get)]
    is_const: bool,
}

/// Builds the initializer every concrete semantic type node extends.
fn sem_type_base(name: String, is_const: bool) -> PyClassInitializer<SemType> {
    PyClassInitializer::from(SemType { name, is_const })
}

#[pymethods]
impl SemType {
    /// The type's child types.
    #[allow(clippy::unused_self)]
    fn children(&self) -> Vec<Py<PyAny>> {
        Vec::new()
    }

    fn __str__(&self) -> String {
        self.name.clone()
    }

    fn __repr__(&self) -> String {
        format!(
            "Type({}, is_const={})",
            py_str(&self.name),
            py_bool(self.is_const)
        )
    }

    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(slf.as_any(), other, &["name", "is_const"])
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(slf.as_any(), &["name", "is_const"])
    }
}

// ----------------------------------------------------------------------------
// Resolved type nodes
// ----------------------------------------------------------------------------
//
// One class per variant of `qdk_openqasm::semantic::types::Type`. Names match
// the syntax layer's type nodes, because the two families live in separate
// modules and a reader moving between them should not have to learn two
// vocabularies for the same concept.

qasm_node!(@semtype SemIntType = "IntType" {
    /// The resolved bit width, when the type has one.
    size: val Option<u32>,
});
qasm_node!(@semtype SemUintType = "UintType" {
    /// The resolved bit width, when the type has one.
    size: val Option<u32>,
});
qasm_node!(@semtype SemFloatType = "FloatType" {
    /// The resolved bit width, when the type has one.
    size: val Option<u32>,
});
qasm_node!(@semtype SemAngleType = "AngleType" {
    /// The resolved bit width, when the type has one.
    size: val Option<u32>,
});
qasm_node!(@semtype SemComplexType = "ComplexType" {
    /// The resolved bit width of each component, when the type has one.
    ///
    /// A `complex[float[64]]` resolves to a size of 64, describing one
    /// component; the syntax layer instead carries the component type node.
    size: val Option<u32>,
});
qasm_node!(@semtype SemBitType = "BitType" {});
qasm_node!(@semtype SemBoolType = "BoolType" {});
qasm_node!(@semtype SemDurationType = "DurationType" {});
qasm_node!(@semtype SemStretchType = "StretchType" {});
qasm_node!(@semtype SemQubitType = "QubitType" {});
qasm_node!(@semtype SemHardwareQubitType = "HardwareQubitType" {});
qasm_node!(@semtype SemBitArrayType = "BitArrayType" {
    /// The register width.
    size: val u32,
});
qasm_node!(@semtype SemQubitArrayType = "QubitArrayType" {
    /// The register width.
    size: val u32,
});
qasm_node!(@semtype SemArrayType = "ArrayType" {
    /// The element type.
    base_type: node,
    /// The length of each dimension, outermost first.
    dimensions: val Vec<u32>,
});
qasm_node!(@semtype SemStaticArrayReferenceType = "StaticArrayReferenceType" {
    /// The element type.
    base_type: node,
    /// The length of each dimension, outermost first.
    dimensions: val Vec<u32>,
    /// Whether the referenced array is readonly or mutable.
    mutability: val AccessControl,
});
qasm_node!(@semtype SemDynArrayReferenceType = "DynArrayReferenceType" {
    /// The element type.
    base_type: node,
    /// The number of dimensions, which is known even though their lengths are not.
    num_dimensions: val u32,
    /// Whether the referenced array is readonly or mutable.
    mutability: val AccessControl,
});
qasm_node!(@semtype SemGateType = "GateType" {
    /// The number of classical parameters the gate declares.
    num_classical_args: val u32,
    /// The number of qubit parameters the gate declares.
    num_qubit_args: val u32,
});
qasm_node!(@semtype SemFunctionType = "FunctionType" {
    /// The parameter types, in declaration order.
    parameter_types: list,
    /// The return type, which is `VoidType` for a subroutine that returns nothing.
    return_type: node,
});
qasm_node!(@semtype SemRangeType = "RangeType" {});
qasm_node!(@semtype SemSetType = "SetType" {});
qasm_node!(@semtype SemVoidType = "VoidType" {});
qasm_node!(@semtype SemErrorType = "ErrorType" {});

/// Projects a resolved type onto its concrete Python node.
///
/// Nodes are interned per analysis. They are frozen and compare structurally, so
/// sharing one object across every occurrence of a type is unobservable.
fn build_type(py: Python<'_>, ctx: &BuildContext<'_>, ty: &CoreType) -> PyResult<Py<PyAny>> {
    if let Some(node) = ctx.cached_type(py, ty) {
        return Ok(node);
    }
    let node = project_type(py, ctx, ty)?;
    ctx.cache_type(py, ty, &node);
    Ok(node)
}

fn project_type(py: Python<'_>, ctx: &BuildContext<'_>, ty: &CoreType) -> PyResult<Py<PyAny>> {
    let name = ty.to_string();
    let is_const = ty.is_const();
    let node = match ty {
        CoreType::Int(size, _) => Py::new(py, SemIntType::init(name, is_const, *size))?.into_any(),
        CoreType::UInt(size, _) => {
            Py::new(py, SemUintType::init(name, is_const, *size))?.into_any()
        }
        CoreType::Float(size, _) => {
            Py::new(py, SemFloatType::init(name, is_const, *size))?.into_any()
        }
        CoreType::Angle(size, _) => {
            Py::new(py, SemAngleType::init(name, is_const, *size))?.into_any()
        }
        CoreType::Complex(size, _) => {
            Py::new(py, SemComplexType::init(name, is_const, *size))?.into_any()
        }
        CoreType::Bit(_) => Py::new(py, SemBitType::init(name, is_const))?.into_any(),
        CoreType::Bool(_) => Py::new(py, SemBoolType::init(name, is_const))?.into_any(),
        CoreType::Duration(_) => Py::new(py, SemDurationType::init(name, is_const))?.into_any(),
        CoreType::Stretch(_) => Py::new(py, SemStretchType::init(name, is_const))?.into_any(),
        CoreType::Qubit => Py::new(py, SemQubitType::init(name, is_const))?.into_any(),
        CoreType::HardwareQubit => {
            Py::new(py, SemHardwareQubitType::init(name, is_const))?.into_any()
        }
        CoreType::BitArray(size, _) => {
            Py::new(py, SemBitArrayType::init(name, is_const, *size))?.into_any()
        }
        CoreType::QubitArray(size) => {
            Py::new(py, SemQubitArrayType::init(name, is_const, *size))?.into_any()
        }
        CoreType::Array(array) => {
            let base_type = build_type(py, ctx, &array.base_ty.clone().into())?;
            let dimensions = array_dimensions(&array.dims);
            Py::new(
                py,
                SemArrayType::init(name, is_const, base_type, dimensions),
            )?
            .into_any()
        }
        CoreType::StaticArrayRef(array) => {
            let base_type = build_type(py, ctx, &array.base_ty.clone().into())?;
            let dimensions = array_dimensions(&array.dims);
            Py::new(
                py,
                SemStaticArrayReferenceType::init(
                    name,
                    is_const,
                    base_type,
                    dimensions,
                    access_control(array.is_mutable),
                ),
            )?
            .into_any()
        }
        CoreType::RankedArrayRef(array) => {
            let base_type = build_type(py, ctx, &array.base_ty.clone().into())?;
            Py::new(
                py,
                SemDynArrayReferenceType::init(
                    name,
                    is_const,
                    base_type,
                    array.rank as u32,
                    access_control(array.is_mutable),
                ),
            )?
            .into_any()
        }
        CoreType::Gate(classical, qubits) => {
            Py::new(py, SemGateType::init(name, is_const, *classical, *qubits))?.into_any()
        }
        CoreType::Function(params, ret) => {
            let mut parameter_types = Vec::with_capacity(params.len());
            for param in params.iter() {
                parameter_types.push(build_type(py, ctx, param)?);
            }
            let return_type = build_type(py, ctx, ret)?;
            Py::new(
                py,
                SemFunctionType::init(name, is_const, parameter_types, return_type),
            )?
            .into_any()
        }
        CoreType::Range => Py::new(py, SemRangeType::init(name, is_const))?.into_any(),
        CoreType::Set => Py::new(py, SemSetType::init(name, is_const))?.into_any(),
        CoreType::Void => Py::new(py, SemVoidType::init(name, is_const))?.into_any(),
        CoreType::Err => Py::new(py, SemErrorType::init(name, is_const))?.into_any(),
    };
    Ok(node)
}

fn array_dimensions(dims: &ArrayDimensions) -> Vec<u32> {
    dims.clone().into_iter().collect()
}

fn access_control(is_mutable: bool) -> AccessControl {
    if is_mutable {
        AccessControl::Mutable
    } else {
        AccessControl::ReadOnly
    }
}

/// A read-only view of a resolved symbol.
#[pyclass(name = "Symbol", module = "qdk.openqasm.semantic", frozen)]
pub(crate) struct SemSymbol {
    /// The symbol's unique id within the [`SemSymbolTable`].
    #[pyo3(get)]
    id: u32,
    /// The symbol's name.
    #[pyo3(get)]
    name: String,
    /// The span where the symbol is declared.
    #[pyo3(get)]
    span: Span,
    /// The symbol's resolved type.
    #[pyo3(get)]
    ty: Py<PyAny>,
    /// Whether the symbol is a program input, a program output, or neither.
    #[pyo3(get)]
    io_kind: IOKind,
    /// The symbol's const-evaluated value, if it is a constant.
    #[pyo3(get)]
    const_value: Option<Py<PyAny>>,
}

#[pymethods]
impl SemSymbol {
    fn __repr__(&self) -> String {
        format!("Symbol(id={}, name={})", self.id, py_str(&self.name))
    }

    // A symbol participates in expression equality, so it needs structural
    // equality of its own or two parses of one source would compare unequal.
    //
    // `id` is excluded for the same reason the node-level `symbol_id` accessor
    // was removed: it is a position in the analysis table, so including it
    // would make two structurally identical subtrees compare unequal whenever
    // the declarations preceding them differ. `span` is excluded for the
    // matching reason: it is a source position, not structure.
    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(
            slf.as_any(),
            other,
            &["name", "ty", "io_kind", "const_value"],
        )
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(
            slf.as_any(),
            &["name", "ty", "io_kind", "const_value"],
        )
    }
}

/// An iterable, read-only projection of the resolved symbol table.
#[pyclass(name = "SymbolTable", module = "qdk.openqasm.semantic", frozen)]
pub(crate) struct SemSymbolTable {
    symbols: Vec<Py<SemSymbol>>,
}

#[pymethods]
impl SemSymbolTable {
    /// The number of symbols in the table.
    fn __len__(&self) -> usize {
        self.symbols.len()
    }
    /// Iterates over the [`SemSymbol`] views in the table.
    fn __iter__(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {
        let list = PyList::new(py, self.symbols.iter().map(|symbol| symbol.clone_ref(py)))?;
        Ok(list.as_any().try_iter()?.into_any().unbind())
    }

    /// Returns the symbol with the given id, or `None`.
    fn get(&self, py: Python<'_>, id: u32) -> Option<Py<SemSymbol>> {
        self.symbols
            .iter()
            .find(|symbol| symbol.borrow(py).id == id)
            .map(|symbol| symbol.clone_ref(py))
    }

    /// Returns the first symbol with the given name, or `None`.
    fn lookup(&self, py: Python<'_>, name: &str) -> Option<Py<SemSymbol>> {
        self.symbols
            .iter()
            .find(|symbol| symbol.borrow(py).name == name)
            .map(|symbol| symbol.clone_ref(py))
    }

    /// All [`SemSymbol`] views in the table, in id order.
    fn symbols(&self, py: Python<'_>) -> Vec<Py<SemSymbol>> {
        self.symbols
            .iter()
            .map(|symbol| symbol.clone_ref(py))
            .collect()
    }

    fn __repr__(&self) -> String {
        format!("SymbolTable({})", py_items(self.symbols.len()))
    }
}

fn build_sem_symbol(
    py: Python<'_>,
    ctx: &BuildContext<'_>,
    id: u32,
    symbol: &Symbol,
) -> PyResult<Py<SemSymbol>> {
    if let Some(node) = ctx.cached_symbol(py, id) {
        return Ok(node);
    }
    let node = Py::new(
        py,
        SemSymbol {
            id,
            name: symbol.name.clone(),
            span: symbol.span.into(),
            ty: build_type(py, ctx, &symbol.ty)?,
            io_kind: IOKind::from(symbol.io_kind),
            const_value: literal_value(py, symbol.get_const_value().as_ref())?,
        },
    )?;
    ctx.cache_symbol(py, id, &node);
    Ok(node)
}

/// Builds the iterable [`SemSymbolTable`] projection from the resolved table.
///
/// Symbol ids are assigned sequentially as symbols are inserted, and the
/// underlying storage never leaves gaps, so a symbol's insertion index equals
/// its id.
pub(crate) fn build_symbol_table(
    py: Python<'_>,
    ctx: &BuildContext<'_>,
) -> PyResult<Py<SemSymbolTable>> {
    let mut entries = Vec::new();
    for (index, symbol) in ctx.symbols.symbols().enumerate() {
        let id = u32::try_from(index).expect("symbol id should fit into u32");
        entries.push(build_sem_symbol(py, ctx, id, symbol.as_ref())?);
    }
    Py::new(py, SemSymbolTable { symbols: entries })
}

fn build_symbol(py: Python<'_>, ctx: &BuildContext<'_>, id: SymbolId) -> PyResult<Py<SemSymbol>> {
    build_sem_symbol(py, ctx, id.into(), ctx.symbols[id].as_ref())
}

fn symbol_name(ctx: &BuildContext<'_>, id: SymbolId) -> Option<String> {
    Some(ctx.symbols[id].name.clone())
}

/// Projects a gate definition's formal parameters as span-carrying nodes.
///
/// The crate stores them as `SymbolId`s, so each node's span is the symbol's
/// own declaration span, which is where the parameter is written.
fn gate_parameter_list(
    py: Python<'_>,
    ctx: &BuildContext<'_>,
    ids: &[SymbolId],
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(ids.len());
    for id in ids {
        let symbol = ctx.symbols[*id].as_ref();
        out.push(
            Py::new(
                py,
                SemGateParameter::init(
                    symbol.span.into(),
                    symbol_name(ctx, *id),
                    build_symbol(py, ctx, *id)?,
                    symbol_type(py, ctx, *id)?,
                ),
            )?
            .into_any(),
        );
    }
    Ok(out)
}

/// Projects the resolved type a declaration bound to its symbol.
fn symbol_type(py: Python<'_>, ctx: &BuildContext<'_>, id: SymbolId) -> PyResult<Py<PyAny>> {
    build_type(py, ctx, &ctx.symbols[id].ty)
}

/// Projects a subroutine's return type out of the `Function` type on its symbol.
fn subroutine_return_type(
    py: Python<'_>,
    ctx: &BuildContext<'_>,
    id: SymbolId,
) -> PyResult<Py<PyAny>> {
    match &ctx.symbols[id].ty {
        CoreType::Function(_, return_ty) => build_type(py, ctx, return_ty),
        other => build_type(py, ctx, other),
    }
}

// ----------------------------------------------------------------------------
// Category bases
// ----------------------------------------------------------------------------

/// The abstract base of every semantic expression node.
///
/// This class has no Python constructor; it exists for `isinstance` dispatch and
/// to carry the resolved `ty`, `const_value`, and (for resolved identifiers)
/// `symbol` shared by all semantic expressions.
#[pyclass(
    extends = Expression,
    subclass,
    frozen,
    name = "SemanticExpression",
    module = "qdk.openqasm.semantic"
)]
pub(crate) struct SemExpr {
    /// The resolved type of the expression.
    #[pyo3(get)]
    ty: Py<PyAny>,
    /// The const-evaluated value of the expression, if any.
    #[pyo3(get)]
    const_value: Option<Py<PyAny>>,
    /// The resolved symbol for identifier expressions, if any.
    #[pyo3(get)]
    symbol: Option<Py<SemSymbol>>,
}

/// The abstract base of every semantic statement node.
///
/// This class has no Python constructor; it exists for `isinstance` dispatch and
/// to carry the `annotations` shared by all semantic statements.
#[pyclass(
    extends = Statement,
    subclass,
    frozen,
    name = "SemanticStatement",
    module = "qdk.openqasm.semantic"
)]
pub(crate) struct SemStmt {}

/// Builds the initializer chain `QASMNode -> Expression -> SemExpr`.
fn sem_expr_base(
    span: Span,
    ty: Py<PyAny>,
    const_value: Option<Py<PyAny>>,
    symbol: Option<Py<SemSymbol>>,
) -> PyClassInitializer<SemExpr> {
    PyClassInitializer::from(QASMNode { span })
        .add_subclass(Expression)
        .add_subclass(SemExpr {
            ty,
            const_value,
            symbol,
        })
}

/// Builds the initializer chain `QASMNode -> Statement -> SemStmt`.
fn sem_stmt_base(span: Span, annotations: Vec<Py<Annotation>>) -> PyClassInitializer<SemStmt> {
    PyClassInitializer::from(QASMNode { span })
        .add_subclass(Statement { annotations })
        .add_subclass(SemStmt {})
}

// ----------------------------------------------------------------------------
// Program root
// ----------------------------------------------------------------------------

/// The root of a semantic `OpenQASM` program.
#[pyclass(extends = QASMNode, frozen, name = "Program", module = "qdk.openqasm.semantic")]
pub(crate) struct SemProgram {
    /// The declared `OpenQASM` version, if any (for example `"3.0"`).
    #[pyo3(get)]
    version: Option<String>,
    /// The program's top-level pragmas, in source order.
    #[pyo3(get)]
    pragmas: Vec<Py<PyAny>>,
    /// The program's top-level statements, in source order.
    #[pyo3(get)]
    statements: Vec<Py<PyAny>>,
    document: Py<SourceDocument>,
}

#[pymethods]
impl SemProgram {
    /// The immutable source document for this analysis snapshot.
    #[getter]
    fn document(&self, py: Python<'_>) -> Py<SourceDocument> {
        self.document.clone_ref(py)
    }

    /// The program's child nodes: pragmas followed by statements.
    fn children(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        let mut out = Vec::with_capacity(self.pragmas.len() + self.statements.len());
        out.extend(self.pragmas.iter().map(|node| node.clone_ref(py)));
        out.extend(self.statements.iter().map(|node| node.clone_ref(py)));
        out
    }

    fn __repr__(&self) -> String {
        format!("Program(statements={})", py_items(self.statements.len()))
    }

    // `document` is excluded: `SourceDocument` is `eq` without `hash`, so
    // including it would make every program unhashable.
    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(
            slf.as_any(),
            other,
            &["version", "pragmas", "statements"],
        )
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(slf.as_any(), &["version", "pragmas", "statements"])
    }
}

/// A hardware-qubit gate operand (for example `$0`).
///
/// This extends [`SemExpr`] so that an operand answers `ty` whether it was
/// written as a declared qubit or as a hardware qubit. It carries no const value
/// and no symbol, because a hardware qubit is a physical reference rather than a
/// declaration.
///
/// The Rust identifier stays `SemHardwareQubit`, but the class is presented to
/// Python as `HardwareQubit` in the `qdk.openqasm.semantic` module so the
/// semantic family can use clean, un-prefixed names without colliding with the
/// syntax layer in `qdk._native`.
#[pyclass(
    extends = SemExpr,
    frozen,
    name = "HardwareQubit",
    module = "qdk.openqasm.semantic"
)]
pub(crate) struct SemHardwareQubit {
    /// The hardware qubit's identifier text (for example `"$0"`).
    #[pyo3(get)]
    name: String,
}

#[pymethods]
impl SemHardwareQubit {
    #[allow(clippy::unused_self)]
    fn children(&self) -> Vec<Py<PyAny>> {
        Vec::new()
    }

    fn __repr__(&self) -> String {
        format!("HardwareQubit(name={})", py_str(&self.name))
    }

    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(
            slf.as_any(),
            other,
            &["ty", "const_value", "symbol", "name"],
        )
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(slf.as_any(), &["ty", "const_value", "symbol", "name"])
    }
}

qasm_node!(@aux SemQuantumGateModifier = "QuantumGateModifier", doc = "A semantic quantum gate modifier." {
    /// The modifier keyword.
    modifier: val GateModifierName,
    /// The modifier's argument, such as a `pow` exponent or a control count.
    argument: opt,
});
qasm_node!(@aux SemRangeDefinition = "RangeDefinition", doc = "A semantic range, as written in a slice or ``for`` loop." {
    /// The range's resolved type, which is always `RangeType`.
    ty: val Py<PyAny>,
    /// The inclusive start of the range, when written.
    start: opt,
    /// The step between values, when written.
    step: opt,
    /// The inclusive end of the range, when written.
    end: opt,
});
qasm_node!(@aux SemDiscreteSet = "DiscreteSet", doc = "A semantic brace-delimited set of values." {
    /// The set's resolved type, which is always `SetType`.
    ty: val Py<PyAny>,
    /// The set's members, in source order.
    values: list,
});
qasm_node!(@aux SemSwitchCase = "SwitchCase", doc = "A semantic ``case`` branch of a ``switch`` statement." {
    /// The case labels this branch matches.
    labels: list,
    /// The statements run when a label matches.
    body: list,
});
qasm_node!(@aux SemSubroutineParameter = "SubroutineParameter", doc = "A semantic subroutine parameter declaration." {
    /// The parameter's name, when analysis resolved one.
    name: val Option<String>,
    /// The parameter's resolved symbol.
    symbol: val Py<SemSymbol>,
    /// The parameter's resolved type.
    r#type: val Py<PyAny>,
});
qasm_node!(@aux SemGateParameter = "GateParameter", doc = "A semantic gate parameter declaration." {
    /// The parameter's name, when analysis resolved one.
    name: val Option<String>,
    /// The parameter's resolved symbol.
    symbol: val Py<SemSymbol>,
    /// The parameter's resolved type.
    r#type: val Py<PyAny>,
});

// ----------------------------------------------------------------------------
// Expression leaf nodes
// ----------------------------------------------------------------------------

qasm_node!(@expr SemErrExpr = "ErrorExpression" {});
qasm_node!(@expr SemResolvedIdent = "Identifier" {
    /// The identifier's name, when analysis resolved one.
    name: val Option<String>,
});
qasm_node!(@expr SemCapturedResolvedIdent = "CapturedIdentifier" {
    /// The identifier's name, when analysis resolved one.
    name: val Option<String>,
});
qasm_node!(@expr SemUnaryOpExpr = "UnaryExpression" {
    /// The unary operator applied to the operand.
    op: val UnaryOperator,
    /// The expression the operator is applied to.
    operand: node,
});
qasm_node!(@expr SemBinaryOpExpr = "BinaryExpression" {
    /// The binary operator joining the two operands.
    op: val BinaryOperator,
    /// The left operand.
    lhs: node,
    /// The right operand.
    rhs: node,
});
qasm_node!(@expr SemLiteral = "LiteralExpression" {
    /// The literal's value, or `None` for an array literal.
    value: val Option<Py<PyAny>>,
    /// The element expressions, for an array literal.
    elements: list,
});
qasm_node!(@expr SemFunctionCall = "FunctionCall" {
    /// The callee's name, when analysis resolved one.
    name: val Option<String>,
    /// The call arguments, in source order.
    args: list,
});
qasm_node!(@expr SemBuiltinFunctionCall = "BuiltinFunctionCall" {
    /// The built-in function's name.
    name: val String,
    /// The call arguments, in source order.
    args: list,
});
qasm_node!(@expr SemCast = "Cast" {
    /// The expression being cast.
    operand: node,
    /// Whether the cast was written in the source or inserted by analysis.
    kind: val CastKind,
});
qasm_node!(@expr SemIndexedExpr = "IndexExpression" {
    /// The expression being indexed.
    collection: node,
    /// The indices applied to the collection, outermost first.
    indices: list,
});
qasm_node!(@expr SemParen = "ParenExpression" {
    /// The expression inside the parentheses.
    operand: node,
});
qasm_node!(@expr SemMeasure = "QuantumMeasurement" {
    /// The qubits being measured.
    qubits: list,
});
qasm_node!(@expr SemRuntimeSizeof = "RuntimeSizeof" {
    /// The array whose size is being taken.
    array: node,
    /// The dimension being measured.
    dimension: node,
    /// The array's number of dimensions.
    array_rank: val u32,
});
qasm_node!(@expr SemEvaluatedDurationof = "DurationOf" {
    /// The statements whose duration was measured.
    body: list,
});
qasm_node!(@expr SemConcat = "Concatenation" {
    /// The operands joined by `++`, in source order.
    operands: list,
});

// ----------------------------------------------------------------------------
// Statement leaf nodes
// ----------------------------------------------------------------------------

qasm_node!(@stmt SemAliasDecl = "AliasStatement" {
    /// The alias's name, when analysis resolved one.
    name: val Option<String>,
    /// The expressions the alias refers to, joined by `++` when several.
    exprs: list,
});
qasm_node!(@stmt SemAssign = "ClassicalAssignment" {
    /// The assignment target.
    lhs: node,
    /// The assigned value, cast to the target's type when needed.
    rhs: node,
});
qasm_node!(@stmt SemBarrier = "QuantumBarrier" {
    /// The qubits the barrier applies to.
    qubits: list,
});
qasm_node!(@stmt SemBox = "Box" {
    /// The box's declared duration, when written.
    duration: opt,
    /// The statements inside the box.
    body: list,
});
qasm_node!(@stmt SemBlock = "CompoundStatement" {
    /// The statements inside the block, in source order.
    statements: list,
});
qasm_node!(@stmt SemBreak = "BreakStatement" {});
qasm_node!(@stmt SemCalibration = "CalibrationStatement" {
    /// The calibration block's raw text, which analysis does not interpret.
    content: val String,
});
qasm_node!(@stmt SemCalibrationGrammar = "CalibrationGrammarDeclaration" {
    /// The named calibration grammar, for example `openpulse`.
    name: val String,
});
qasm_node!(@stmt SemClassicalDecl = "ClassicalDeclaration" {
    /// The declared name, when analysis resolved one.
    name: val Option<String>,
    /// The declared, resolved type.
    r#type: val Py<PyAny>,
    /// The initializer, defaulted by analysis when the source omitted one.
    init_expr: node,
});
qasm_node!(@stmt SemContinue = "ContinueStatement" {});
qasm_node!(@stmt SemDef = "SubroutineDefinition" {
    /// The subroutine's name, when analysis resolved one.
    name: val Option<String>,
    /// The declared parameters, in source order.
    params: list,
    /// The resolved return type, which is `VoidType` when the subroutine returns nothing.
    return_type: val Py<PyAny>,
    /// The statements making up the subroutine body.
    body: list,
});
qasm_node!(@stmt SemDefCal = "CalibrationDefinition" {
    /// The `defcal` block's raw text, which analysis does not interpret.
    content: val String,
});
qasm_node!(@stmt SemDelay = "DelayInstruction" {
    /// The delay's duration.
    duration: node,
    /// The qubits the delay applies to.
    qubits: list,
});
qasm_node!(@stmt SemEnd = "EndStatement" {});
qasm_node!(@stmt SemExprStmt = "ExpressionStatement" {
    /// The evaluated expression.
    expr: node,
});
qasm_node!(@stmt SemExternDecl = "ExternDeclaration" {
    /// The external subroutine's name, when analysis resolved one.
    name: val Option<String>,
    /// The resolved signature, whose `parameter_types` and `return_type` describe the call.
    r#type: val Py<PyAny>,
});
qasm_node!(@stmt SemForLoop = "ForInLoop" {
    /// The loop variable's name, when analysis resolved one.
    name: val Option<String>,
    /// The loop variable's resolved type.
    r#type: val Py<PyAny>,
    /// The range, set, or expression being iterated.
    iterable: node,
    /// The loop body.
    body: node,
});
qasm_node!(@stmt SemGateCall = "QuantumGate" {
    /// The gate's name, when analysis resolved one.
    name: val Option<String>,
    /// The modifiers applied to the gate, such as `ctrl` or `inv`.
    modifiers: list,
    /// The classical arguments, such as a rotation angle.
    args: list,
    /// The qubit operands the gate acts on.
    qubits: list,
    /// The gate's declared duration, when written.
    duration: opt,
});
qasm_node!(@stmt SemIfStmt = "BranchingStatement" {
    /// The branch condition.
    condition: node,
    /// The block run when the condition holds.
    then_block: node,
    /// The `else` block, when written.
    else_block: opt,
});
qasm_node!(@stmt SemIndexedAssign = "IndexedClassicalAssignment" {
    /// The base expression being assigned into.
    lhs: node,
    /// The indices selecting the assigned element, outermost first.
    indices: list,
    /// The assigned value, cast to the element's type when needed.
    rhs: node,
});
qasm_node!(@stmt SemInputDeclaration = "InputDeclaration" {
    /// The input's name, when analysis resolved one.
    name: val Option<String>,
    /// The declared, resolved type.
    r#type: val Py<PyAny>,
});
qasm_node!(@stmt SemOutputDeclaration = "OutputDeclaration" {
    /// The output's name, when analysis resolved one.
    name: val Option<String>,
    /// The declared, resolved type.
    r#type: val Py<PyAny>,
    /// The default value analysis assigned to the output.
    init_expr: node,
});
qasm_node!(@stmt SemPragma = "Pragma" {
    /// The pragma's full text after the keyword.
    command: val String,
    /// The leading dotted identifier, when the pragma has one.
    name: val Option<String>,
    /// The remaining text after the identifier, when present.
    value: val Option<String>,
});
qasm_node!(@stmt SemGateDefinition = "QuantumGateDefinition" {
    /// The gate's name, when analysis resolved one.
    name: val Option<String>,
    /// The classical parameters, in source order.
    params: list,
    /// The qubit parameters, in source order.
    qubits: list,
    /// The statements making up the gate body.
    body: list,
});
qasm_node!(@stmt SemQubitDecl = "QubitDeclaration" {
    /// The qubit's name, when analysis resolved one.
    name: val Option<String>,
});
qasm_node!(@stmt SemQubitArrayDecl = "QubitArrayDeclaration" {
    /// The register's name, when analysis resolved one.
    name: val Option<String>,
    /// The register width.
    size: node,
});
qasm_node!(@stmt SemReset = "QuantumReset" {
    /// The qubits being reset.
    qubits: list,
});
qasm_node!(@stmt SemReturn = "ReturnStatement" {
    /// The returned expression, when the subroutine returns a value.
    value: opt,
});
/// A read-only OpenQASM `SwitchStatement` node.
#[pyclass(
    extends = SemStmt,
    frozen,
    name = "SwitchStatement",
    module = "qdk.openqasm.semantic"
)]
pub(crate) struct SemSwitch {
    /// The expression being switched on.
    #[pyo3(get)]
    target: Py<PyAny>,
    /// The `case` branches, in source order.
    #[pyo3(get)]
    cases: Vec<Py<PyAny>>,
    default: Option<Vec<Py<PyAny>>>,
}

#[pymethods]
impl SemSwitch {
    /// The `default` branch's statements, or `None` when there is no `default`.
    #[getter]
    fn default(&self, py: Python<'_>) -> Option<Vec<Py<PyAny>>> {
        self.default
            .as_ref()
            .map(|body| body.iter().map(|stmt| stmt.clone_ref(py)).collect())
    }

    /// The node's child nodes: the annotations, the target, then the cases,
    /// then any default body.
    // `PyRef` is the receiver form PyO3 requires to reach the base class.
    #[allow(clippy::needless_pass_by_value)]
    fn children(slf: PyRef<'_, Self>) -> Vec<Py<PyAny>> {
        let py = slf.py();
        let annotations = &slf.as_super().as_super().annotations;
        let default_len = slf.default.as_ref().map_or(0, Vec::len);
        let mut children =
            Vec::with_capacity(annotations.len() + 1 + slf.cases.len() + default_len);
        children.extend(
            annotations
                .iter()
                .map(|annotation| annotation.clone_ref(py).into_any()),
        );
        children.push(slf.target.clone_ref(py));
        children.extend(slf.cases.iter().map(|case| case.clone_ref(py)));
        if let Some(default) = &slf.default {
            children.extend(default.iter().map(|stmt| stmt.clone_ref(py)));
        }
        children
    }

    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(
            slf.as_any(),
            other,
            &["annotations", "target", "cases", "default"],
        )
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(
            slf.as_any(),
            &["annotations", "target", "cases", "default"],
        )
    }
}

impl SemSwitch {
    fn init(
        span: Span,
        annotations: Vec<Py<Annotation>>,
        target: Py<PyAny>,
        cases: Vec<Py<PyAny>>,
        default: Option<Vec<Py<PyAny>>>,
    ) -> PyClassInitializer<Self> {
        sem_stmt_base(span, annotations).add_subclass(Self {
            target,
            cases,
            default,
        })
    }
}
qasm_node!(@stmt SemWhileLoop = "WhileLoop" {
    /// The loop condition, tested before each iteration.
    condition: node,
    /// The loop body.
    body: node,
});
qasm_node!(@stmt SemErrStmt = "ErrorStatement" {});

// ----------------------------------------------------------------------------
// Registration
// ----------------------------------------------------------------------------

macro_rules! register_semantic_nodes {
    ($m:ident; $($ty:ty),* $(,)?) => {
        $($m.add_class::<$ty>()?;)*
    };
}

/// Registers all semantic node classes with the given module.
///
/// The classes are stored in the private native semantic namespace (not
/// the flat `qdk._native` module), so their clean, un-prefixed Python names do
/// not collide with the syntax layer.
pub(crate) fn register_semantic_nodes(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<CastKind>()?;
    m.add_class::<IOKind>()?;
    m.add_class::<Angle>()?;
    m.add_class::<Duration>()?;
    register_semantic_nodes!(m;
        SemType,
        SemIntType,
        SemUintType,
        SemFloatType,
        SemAngleType,
        SemComplexType,
        SemBitType,
        SemBoolType,
        SemDurationType,
        SemStretchType,
        SemQubitType,
        SemHardwareQubitType,
        SemBitArrayType,
        SemQubitArrayType,
        SemArrayType,
        SemStaticArrayReferenceType,
        SemDynArrayReferenceType,
        SemGateType,
        SemFunctionType,
        SemRangeType,
        SemSetType,
        SemVoidType,
        SemErrorType,
        SemSymbol,
        SemSymbolTable,
        SemExpr,
        SemStmt,
        SemProgram,
        SemHardwareQubit,
        SemQuantumGateModifier,
        SemRangeDefinition,
        SemDiscreteSet,
        SemSwitchCase,
        SemSubroutineParameter,
        SemGateParameter,
        SemErrExpr,
        SemResolvedIdent,
        SemCapturedResolvedIdent,
        SemUnaryOpExpr,
        SemBinaryOpExpr,
        SemLiteral,
        SemFunctionCall,
        SemBuiltinFunctionCall,
        SemCast,
        SemIndexedExpr,
        SemParen,
        SemMeasure,
        SemRuntimeSizeof,
        SemEvaluatedDurationof,
        SemConcat,
        SemAliasDecl,
        SemAssign,
        SemBarrier,
        SemBox,
        SemBlock,
        SemBreak,
        SemCalibration,
        SemCalibrationGrammar,
        SemClassicalDecl,
        SemContinue,
        SemDef,
        SemDefCal,
        SemDelay,
        SemEnd,
        SemExprStmt,
        SemExternDecl,
        SemForLoop,
        SemGateCall,
        SemIfStmt,
        SemIndexedAssign,
        SemInputDeclaration,
        SemOutputDeclaration,
        SemPragma,
        SemGateDefinition,
        SemQubitDecl,
        SemQubitArrayDecl,
        SemReset,
        SemReturn,
        SemSwitch,
        SemWhileLoop,
        SemErrStmt,
    );
    Ok(())
}

// ----------------------------------------------------------------------------
// Semantic AST -> Python node tree
// ----------------------------------------------------------------------------

/// Builds the semantic [`SemProgram`] root from an analyzed program.
pub(crate) fn build_program(
    py: Python<'_>,
    program: &sem::Program,
    ctx: &BuildContext<'_>,
    document: Py<SourceDocument>,
) -> PyResult<Py<SemProgram>> {
    let statements = stmt_list(py, &program.statements, ctx)?;
    let mut pragmas = Vec::with_capacity(program.pragmas.len());
    for pragma in &program.pragmas {
        pragmas.push(build_pragma(py, pragma)?);
    }
    let version = program.version.map(|version| version.to_string());
    let init = PyClassInitializer::from(QASMNode {
        span: Span::from(program.span),
    })
    .add_subclass(SemProgram {
        version,
        pragmas,
        statements,
        document,
    });
    Py::new(py, init)
}

fn build_pragma(py: Python<'_>, pragma: &sem::Pragma) -> PyResult<Py<PyAny>> {
    let command = pragma.command.to_string();
    let name = pragma.identifier.as_ref().map(PathKind::as_string);
    let value = pragma.value.as_ref().map(ToString::to_string);
    let init = SemPragma::init(Span::from(pragma.span), Vec::new(), command, name, value);
    Ok(Py::new(py, init)?.into_any())
}

#[allow(clippy::too_many_lines)]
fn build_stmt(py: Python<'_>, stmt: &sem::Stmt, ctx: &BuildContext<'_>) -> PyResult<Py<PyAny>> {
    let span = Span::from(stmt.span);
    let annotations = build_annotations(py, &stmt.annotations)?;

    let obj: Py<PyAny> = match stmt.kind.as_ref() {
        StmtKind::Alias(s) => {
            let exprs = expr_list(py, &s.exprs, ctx)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(py, SemAliasDecl::init(span, annotations, name, exprs))?.into_any()
        }
        StmtKind::Assign(s) => {
            let lhs = build_expr(py, &s.lhs, ctx)?;
            let rhs = build_expr(py, &s.rhs, ctx)?;
            Py::new(py, SemAssign::init(span, annotations, lhs, rhs))?.into_any()
        }
        StmtKind::Barrier(s) => {
            let qubits = gate_operand_list(py, &s.qubits, ctx)?;
            Py::new(py, SemBarrier::init(span, annotations, qubits))?.into_any()
        }
        StmtKind::Box(s) => {
            let duration = build_opt_expr(py, s.duration.as_deref(), ctx)?;
            let body = stmt_list(py, &s.body, ctx)?;
            Py::new(py, SemBox::init(span, annotations, duration, body))?.into_any()
        }
        StmtKind::Block(s) => {
            let statements = stmt_list(py, &s.stmts, ctx)?;
            Py::new(py, SemBlock::init(span, annotations, statements))?.into_any()
        }
        StmtKind::Break(_) => Py::new(py, SemBreak::init(span, annotations))?.into_any(),
        StmtKind::Calibration(s) => Py::new(
            py,
            SemCalibration::init(span, annotations, s.content.to_string()),
        )?
        .into_any(),
        StmtKind::CalibrationGrammar(s) => Py::new(
            py,
            SemCalibrationGrammar::init(span, annotations, s.name.to_string()),
        )?
        .into_any(),
        StmtKind::ClassicalDecl(s) => {
            let r#type = symbol_type(py, ctx, s.symbol_id)?;
            let init_expr = build_expr(py, &s.init_expr, ctx)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(
                py,
                SemClassicalDecl::init(span, annotations, name, r#type, init_expr),
            )?
            .into_any()
        }
        StmtKind::Continue(_) => Py::new(py, SemContinue::init(span, annotations))?.into_any(),
        StmtKind::Def(s) => {
            let mut params = Vec::with_capacity(s.params.len());
            for param in &s.params {
                let r#type = symbol_type(py, ctx, param.symbol_id)?;
                let symbol = build_symbol(py, ctx, param.symbol_id)?;
                params.push(
                    Py::new(
                        py,
                        SemSubroutineParameter::init(
                            Span::from(param.span),
                            symbol_name(ctx, param.symbol_id),
                            symbol,
                            r#type,
                        ),
                    )?
                    .into_any(),
                );
            }
            let return_type = subroutine_return_type(py, ctx, s.symbol_id)?;
            let body = stmt_list(py, &s.body.stmts, ctx)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(
                py,
                SemDef::init(span, annotations, name, params, return_type, body),
            )?
            .into_any()
        }
        StmtKind::DefCal(s) => Py::new(
            py,
            SemDefCal::init(span, annotations, s.content.to_string()),
        )?
        .into_any(),
        StmtKind::Delay(s) => {
            let duration = build_expr(py, &s.duration, ctx)?;
            let qubits = gate_operand_list(py, &s.qubits, ctx)?;
            Py::new(py, SemDelay::init(span, annotations, duration, qubits))?.into_any()
        }
        StmtKind::End(_) => Py::new(py, SemEnd::init(span, annotations))?.into_any(),
        StmtKind::ExprStmt(s) => {
            let expr = build_expr(py, &s.expr, ctx)?;
            Py::new(py, SemExprStmt::init(span, annotations, expr))?.into_any()
        }
        StmtKind::ExternDecl(s) => {
            let r#type = symbol_type(py, ctx, s.symbol_id)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(py, SemExternDecl::init(span, annotations, name, r#type))?.into_any()
        }
        StmtKind::For(s) => {
            let r#type = symbol_type(py, ctx, s.loop_variable)?;
            let iterable = build_enumerable_set(py, &s.set_declaration, ctx)?;
            let body = build_stmt(py, &s.body, ctx)?;
            let name = symbol_name(ctx, s.loop_variable);
            Py::new(
                py,
                SemForLoop::init(span, annotations, name, r#type, iterable, body),
            )?
            .into_any()
        }
        StmtKind::GateCall(s) => {
            let mut modifiers = Vec::with_capacity(s.modifiers.len());
            for modifier in s.modifiers.iter().rev() {
                modifiers.push(build_modifier(py, modifier, ctx)?);
            }
            let args = expr_list(py, &s.args, ctx)?;
            let qubits = gate_operand_list(py, &s.qubits, ctx)?;
            let duration = build_opt_expr(py, s.duration.as_deref(), ctx)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(
                py,
                SemGateCall::init(span, annotations, name, modifiers, args, qubits, duration),
            )?
            .into_any()
        }
        StmtKind::If(s) => {
            let condition = build_expr(py, &s.condition, ctx)?;
            let then_block = build_stmt(py, &s.if_body, ctx)?;
            let else_block = match &s.else_body {
                Some(else_body) => Some(build_stmt(py, else_body, ctx)?),
                None => None,
            };
            Py::new(
                py,
                SemIfStmt::init(span, annotations, condition, then_block, else_block),
            )?
            .into_any()
        }
        StmtKind::IndexedAssign(s) => {
            let lhs = build_expr(py, &s.lhs, ctx)?;
            let mut indices = Vec::with_capacity(s.indices.len());
            for index in &s.indices {
                indices.push(build_index(py, index, ctx)?);
            }
            let rhs = build_expr(py, &s.rhs, ctx)?;
            Py::new(
                py,
                SemIndexedAssign::init(span, annotations, lhs, indices, rhs),
            )?
            .into_any()
        }
        StmtKind::InputDeclaration(s) => {
            let r#type = symbol_type(py, ctx, s.symbol_id)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(
                py,
                SemInputDeclaration::init(span, annotations, name, r#type),
            )?
            .into_any()
        }
        StmtKind::OutputDeclaration(s) => {
            let r#type = symbol_type(py, ctx, s.symbol_id)?;
            let init_expr = build_expr(py, &s.init_expr, ctx)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(
                py,
                SemOutputDeclaration::init(span, annotations, name, r#type, init_expr),
            )?
            .into_any()
        }
        StmtKind::Pragma(s) => {
            let command = s.command.to_string();
            let name = s.identifier.as_ref().map(PathKind::as_string);
            let value = s.value.as_ref().map(ToString::to_string);
            Py::new(py, SemPragma::init(span, annotations, command, name, value))?.into_any()
        }
        StmtKind::QuantumGateDefinition(s) => {
            let params = gate_parameter_list(py, ctx, &s.params)?;
            let qubits = gate_parameter_list(py, ctx, &s.qubits)?;
            let body = stmt_list(py, &s.body.stmts, ctx)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(
                py,
                SemGateDefinition::init(span, annotations, name, params, qubits, body),
            )?
            .into_any()
        }
        StmtKind::QubitDecl(s) => {
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(py, SemQubitDecl::init(span, annotations, name))?.into_any()
        }
        StmtKind::QubitArrayDecl(s) => {
            let size = build_expr(py, &s.size, ctx)?;
            let name = symbol_name(ctx, s.symbol_id);
            Py::new(py, SemQubitArrayDecl::init(span, annotations, name, size))?.into_any()
        }
        StmtKind::Reset(s) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &s.operand, ctx)?;
            Py::new(py, SemReset::init(span, annotations, qubits))?.into_any()
        }
        StmtKind::Return(s) => {
            let value = build_opt_expr(py, s.expr.as_deref(), ctx)?;
            Py::new(py, SemReturn::init(span, annotations, value))?.into_any()
        }
        StmtKind::Switch(s) => {
            let target = build_expr(py, &s.target, ctx)?;
            let mut cases = Vec::with_capacity(s.cases.len());
            for case in &s.cases {
                let labels = expr_list(py, &case.labels, ctx)?;
                let body = stmt_list(py, &case.block.stmts, ctx)?;
                cases.push(
                    Py::new(py, SemSwitchCase::init(Span::from(case.span), labels, body))?
                        .into_any(),
                );
            }
            let default = s
                .default
                .as_ref()
                .map(|block| stmt_list(py, &block.stmts, ctx))
                .transpose()?;
            Py::new(
                py,
                SemSwitch::init(span, annotations, target, cases, default),
            )?
            .into_any()
        }
        StmtKind::WhileLoop(s) => {
            let condition = build_expr(py, &s.condition, ctx)?;
            let body = build_stmt(py, &s.body, ctx)?;
            Py::new(py, SemWhileLoop::init(span, annotations, condition, body))?.into_any()
        }
        // Includes are inlined by `lower_source` and rejected outside global scope, so the
        // variant never reaches the projection. Surface it as a recovery node, not a panic.
        StmtKind::Err => Py::new(py, SemErrStmt::init(span, annotations))?.into_any(),
    };
    Ok(obj)
}

fn build_annotations(
    py: Python<'_>,
    annotations: &[sem::Annotation],
) -> PyResult<Vec<Py<Annotation>>> {
    annotations
        .iter()
        .map(|annotation| {
            Py::new(
                py,
                Annotation::init(
                    Span::from(annotation.span),
                    annotation.identifier.as_string(),
                    annotation.value.as_ref().map(ToString::to_string),
                    annotation.value_span.map(Span::from),
                ),
            )
        })
        .collect()
}

#[allow(clippy::too_many_lines)]
fn build_expr(py: Python<'_>, expr: &sem::Expr, ctx: &BuildContext<'_>) -> PyResult<Py<PyAny>> {
    let span = Span::from(expr.span);
    let ty = build_type(py, ctx, &expr.ty)?;
    let const_value = literal_value(py, expr.const_value.as_ref())?;

    let obj: Py<PyAny> = match expr.kind.as_ref() {
        ExprKind::Err => Py::new(py, SemErrExpr::init(span, ty, const_value, None))?.into_any(),
        ExprKind::ResolvedIdent(id) => {
            let symbol = Some(build_symbol(py, ctx, *id)?);
            let name = symbol_name(ctx, *id);
            Py::new(
                py,
                SemResolvedIdent::init(span, ty, const_value, symbol, name),
            )?
            .into_any()
        }
        ExprKind::CapturedResolvedIdent(id) => {
            let symbol = Some(build_symbol(py, ctx, *id)?);
            let name = symbol_name(ctx, *id);
            Py::new(
                py,
                SemCapturedResolvedIdent::init(span, ty, const_value, symbol, name),
            )?
            .into_any()
        }
        ExprKind::UnaryOp(e) => {
            let operand = build_expr(py, &e.expr, ctx)?;
            Py::new(
                py,
                SemUnaryOpExpr::init(span, ty, const_value, None, e.op.into(), operand),
            )?
            .into_any()
        }
        ExprKind::BinaryOp(e) => {
            let lhs = build_expr(py, &e.lhs, ctx)?;
            let rhs = build_expr(py, &e.rhs, ctx)?;
            Py::new(
                py,
                SemBinaryOpExpr::init(span, ty, const_value, None, e.op.into(), lhs, rhs),
            )?
            .into_any()
        }
        ExprKind::Lit(lit) => {
            let (value, elements) = literal_expr_parts(py, lit, ctx)?;
            Py::new(
                py,
                SemLiteral::init(span, ty, const_value, None, value, elements),
            )?
            .into_any()
        }
        ExprKind::ResolvedFunctionCall(e) => {
            let args = expr_list(py, &e.args, ctx)?;
            let symbol = Some(build_symbol(py, ctx, e.callee_id)?);
            let name = symbol_name(ctx, e.callee_id);
            Py::new(
                py,
                SemFunctionCall::init(span, ty, const_value, symbol, name, args),
            )?
            .into_any()
        }
        ExprKind::BuiltinFunctionCall(e) => {
            let args = expr_list(py, &e.args, ctx)?;
            Py::new(
                py,
                SemBuiltinFunctionCall::init(span, ty, const_value, None, e.name.to_string(), args),
            )?
            .into_any()
        }
        ExprKind::Cast(e) => {
            let operand = build_expr(py, &e.expr, ctx)?;
            Py::new(
                py,
                SemCast::init(span, ty, const_value, None, operand, e.kind.into()),
            )?
            .into_any()
        }
        ExprKind::IndexedExpr(e) => {
            let collection = build_expr(py, &e.collection, ctx)?;
            let indices = vec![build_index(py, &e.index, ctx)?];
            Py::new(
                py,
                SemIndexedExpr::init(span, ty, const_value, None, collection, indices),
            )?
            .into_any()
        }
        ExprKind::Paren(inner) => {
            let operand = build_expr(py, inner, ctx)?;
            Py::new(py, SemParen::init(span, ty, const_value, None, operand))?.into_any()
        }
        ExprKind::Measure(e) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &e.operand, ctx)?;
            Py::new(py, SemMeasure::init(span, ty, const_value, None, qubits))?.into_any()
        }
        ExprKind::RuntimeSizeof(e) => {
            let array = build_expr(py, &e.array, ctx)?;
            let dimension = build_expr(py, &e.dimension, ctx)?;
            Py::new(
                py,
                SemRuntimeSizeof::init(span, ty, const_value, None, array, dimension, e.array_rank),
            )?
            .into_any()
        }
        ExprKind::EvaluatedDurationof(e) => {
            let body = stmt_list(py, &e.scope.stmts, ctx)?;
            Py::new(
                py,
                SemEvaluatedDurationof::init(span, ty, const_value, None, body),
            )?
            .into_any()
        }
        ExprKind::Concat(e) => {
            let operands = expr_list(py, &e.operands, ctx)?;
            Py::new(py, SemConcat::init(span, ty, const_value, None, operands))?.into_any()
        }
    };
    Ok(obj)
}

// ----------------------------------------------------------------------------
// Child-collection helpers
// ----------------------------------------------------------------------------

fn expr_list(
    py: Python<'_>,
    exprs: &[sem::Expr],
    ctx: &BuildContext<'_>,
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(exprs.len());
    for expr in exprs {
        out.push(build_expr(py, expr, ctx)?);
    }
    Ok(out)
}

fn stmt_list(
    py: Python<'_>,
    stmts: &[sem::Stmt],
    ctx: &BuildContext<'_>,
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(stmts.len());
    for stmt in stmts {
        if let StmtKind::GateCall(call) = stmt.kind.as_ref() {
            let expansion =
                expand_gate_call(call).map_err(|error| PyValueError::new_err(error.to_string()))?;
            for scalar in expansion {
                out.push(build_scalar_gate_call(py, stmt, &scalar, ctx)?);
            }
        } else {
            out.push(build_stmt(py, stmt, ctx)?);
        }
    }
    Ok(out)
}

fn build_scalar_gate_call(
    py: Python<'_>,
    stmt: &sem::Stmt,
    scalar: &ScalarGateCall<'_>,
    ctx: &BuildContext<'_>,
) -> PyResult<Py<PyAny>> {
    let call = scalar.source();
    let span = Span::from(stmt.span);
    let annotations = build_annotations(py, &stmt.annotations)?;
    let mut modifiers = Vec::with_capacity(call.modifiers.len());
    for modifier in call.modifiers.iter().rev() {
        modifiers.push(build_modifier(py, modifier, ctx)?);
    }
    let args = expr_list(py, &call.args, ctx)?;
    let qubits = gate_operand_list(py, scalar.qubits(), ctx)?;
    let duration = build_opt_expr(py, call.duration.as_deref(), ctx)?;
    let name = symbol_name(ctx, call.symbol_id);
    Ok(Py::new(
        py,
        SemGateCall::init(span, annotations, name, modifiers, args, qubits, duration),
    )?
    .into_any())
}

fn build_opt_expr(
    py: Python<'_>,
    expr: Option<&sem::Expr>,
    ctx: &BuildContext<'_>,
) -> PyResult<Option<Py<PyAny>>> {
    match expr {
        Some(expr) => Ok(Some(build_expr(py, expr, ctx)?)),
        None => Ok(None),
    }
}

fn gate_operand_list(
    py: Python<'_>,
    operands: &[sem::GateOperand],
    ctx: &BuildContext<'_>,
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(operands.len());
    for operand in operands {
        collect_gate_operand(py, &mut out, operand, ctx)?;
    }
    Ok(out)
}

fn collect_gate_operand(
    py: Python<'_>,
    out: &mut Vec<Py<PyAny>>,
    operand: &sem::GateOperand,
    ctx: &BuildContext<'_>,
) -> PyResult<()> {
    match &operand.kind {
        sem::GateOperandKind::Expr(expr) => out.push(build_expr(py, expr, ctx)?),
        sem::GateOperandKind::HardwareQubit(hw) => out.push(build_hardware_qubit(py, ctx, hw)?),
        sem::GateOperandKind::Err => {}
    }
    Ok(())
}

fn build_hardware_qubit(
    py: Python<'_>,
    ctx: &BuildContext<'_>,
    hw: &sem::HardwareQubit,
) -> PyResult<Py<PyAny>> {
    let init = sem_expr_base(
        Span::from(hw.span),
        build_type(py, ctx, &hw.ty)?,
        None,
        None,
    )
    .add_subclass(SemHardwareQubit {
        name: hw.name.to_string(),
    });
    Ok(Py::new(py, init)?.into_any())
}

fn build_index(py: Python<'_>, index: &sem::Index, ctx: &BuildContext<'_>) -> PyResult<Py<PyAny>> {
    match index {
        sem::Index::Expr(expr) => build_expr(py, expr, ctx),
        sem::Index::Range(range) => build_range(py, range, ctx),
    }
}

fn build_range(py: Python<'_>, range: &sem::Range, ctx: &BuildContext<'_>) -> PyResult<Py<PyAny>> {
    let start = build_opt_expr(py, range.start.as_ref(), ctx)?;
    let step = build_opt_expr(py, range.step.as_ref(), ctx)?;
    let end = build_opt_expr(py, range.end.as_ref(), ctx)?;
    Ok(Py::new(
        py,
        SemRangeDefinition::init(
            Span::from(range.span),
            build_type(py, ctx, &range.ty)?,
            start,
            step,
            end,
        ),
    )?
    .into_any())
}

fn build_enumerable_set(
    py: Python<'_>,
    set: &sem::EnumerableSet,
    ctx: &BuildContext<'_>,
) -> PyResult<Py<PyAny>> {
    match set {
        sem::EnumerableSet::Set(set) => {
            let values = expr_list(py, &set.values, ctx)?;
            Ok(Py::new(
                py,
                SemDiscreteSet::init(Span::from(set.span), build_type(py, ctx, &set.ty)?, values),
            )?
            .into_any())
        }
        sem::EnumerableSet::Range(range) => build_range(py, range, ctx),
        sem::EnumerableSet::Expr(expr) => build_expr(py, expr, ctx),
    }
}

fn build_modifier(
    py: Python<'_>,
    modifier: &sem::QuantumGateModifier,
    ctx: &BuildContext<'_>,
) -> PyResult<Py<PyAny>> {
    let (name, argument) = match &modifier.kind {
        sem::GateModifierKind::Inv => (GateModifierName::Inv, None),
        sem::GateModifierKind::Pow(expr) => {
            (GateModifierName::Pow, Some(build_expr(py, expr, ctx)?))
        }
        sem::GateModifierKind::Ctrl(expr) => {
            (GateModifierName::Ctrl, Some(build_expr(py, expr, ctx)?))
        }
        sem::GateModifierKind::NegCtrl(expr) => {
            (GateModifierName::NegCtrl, Some(build_expr(py, expr, ctx)?))
        }
    };
    Ok(Py::new(
        py,
        SemQuantumGateModifier::init(Span::from(modifier.span), name, argument),
    )?
    .into_any())
}

// ----------------------------------------------------------------------------
// Literal-value projection
// ----------------------------------------------------------------------------

/// The projected value and element children of a literal expression.
///
/// Scalar literals carry a Python value and no elements; array literals carry no
/// scalar value and expose their element expressions as children.
type LiteralParts = (Option<Py<PyAny>>, Vec<Py<PyAny>>);

fn literal_expr_parts(
    py: Python<'_>,
    lit: &LiteralKind,
    ctx: &BuildContext<'_>,
) -> PyResult<LiteralParts> {
    match lit {
        LiteralKind::Array(array) => {
            let mut elements = Vec::with_capacity(array.data.len());
            for item in &array.data {
                elements.push(build_expr(py, item, ctx)?);
            }
            Ok((None, elements))
        }
        other => Ok((literal_kind_value(py, other)?, Vec::new())),
    }
}

fn literal_value(py: Python<'_>, lit: Option<&LiteralKind>) -> PyResult<Option<Py<PyAny>>> {
    match lit {
        Some(lit) => literal_kind_value(py, lit),
        None => Ok(None),
    }
}

fn literal_kind_value(py: Python<'_>, lit: &LiteralKind) -> PyResult<Option<Py<PyAny>>> {
    let value: Py<PyAny> = match lit {
        LiteralKind::Array(_) => return Ok(None),
        LiteralKind::Bool(b) | LiteralKind::Bit(b) => (*b).into_py_any(py)?,
        LiteralKind::Int(i) => (*i).into_py_any(py)?,
        LiteralKind::Float(f) => (*f).into_py_any(py)?,
        LiteralKind::Complex(value) => PyComplex::from_doubles(py, value.real, value.imag)
            .into_any()
            .unbind(),
        LiteralKind::Angle(angle) => Angle::from_core(*angle).into_py_any(py)?,
        LiteralKind::Duration(duration) => {
            Duration::new(duration.value, duration.unit.into()).into_py_any(py)?
        }
        LiteralKind::Bitstring(value, width) => {
            let width = *width as usize;
            format!("{:0>width$}", value.to_str_radix(2)).into_py_any(py)?
        }
        LiteralKind::BigInt(value) => bigint_to_py(py, &value.to_str_radix(10))?,
    };
    Ok(Some(value))
}

fn bigint_to_py(py: Python<'_>, decimal: &str) -> PyResult<Py<PyAny>> {
    Ok(py
        .import("builtins")?
        .getattr("int")?
        .call1((decimal,))?
        .unbind())
}
