// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Rich, read-only Python projections of the *syntactic* `OpenQASM` AST.
//!
//! Where [`super::semantic`] projects the resolved semantic tree, this module
//! projects the raw parse tree produced by [`qdk_openqasm::parse_source`]. The
//! syntactic tree carries no resolved type, const-value, or symbol information,
//! so its nodes extend [`Expression`] / [`Statement`] directly (a three-level
//! `QASMNode -> Expression|Statement -> concrete` chain) rather than through the
//! semantic `SemExpr` / `SemStmt` bases.
//!
//! Concrete per-variant leaf classes are generated by the [`qasm_node!`] macro
//! (`@sexpr` / `@sstmt` categories) and expose *named*, typed accessors for
//! their children (for example `BinaryExpression.lhs` / `.rhs` / `.op`) plus a
//! uniform `children()` method for generic traversal. There is intentionally no
//! `kind` discriminant; callers dispatch via `isinstance` and
//! `type(node).__name__`.
//!
//! Class names follow the [`openqasm3` reference AST][openqasm3] wherever an
//! equivalent class exists (for example `BinaryExpression`, `QuantumGate`,
//! `ClassicalDeclaration`, `ForInLoop`, `Box`, `SwitchStatement`). Variants with
//! no `openqasm3` equivalent take a descriptive QDK name (for example
//! `ErrorExpression`, `ErrorStatement`, `ParenExpression`, `CompoundAssignment`).
//!
//! All projections are eagerly materialized into owned, frozen values (scalars
//! plus `Py<PyAny>` references to already-built children), so they are
//! `Send + Sync` and hold no borrow into the Rust parse result.
//!
//! [openqasm3]: https://github.com/openqasm/openqasm/tree/main/source/openqasm
//!
//! ## Syntactic name to variant table
//!
//! The mapping below is the single source of truth for the Python class names
//! and the syntactic AST variants they project. It is kept in sync with
//! `qdk_openqasm::parser::ast`.
//!
//! Statements (`StmtKind` -> class):
//! * `Alias` -> `AliasStatement`
//! * `Assign` -> `ClassicalAssignment`
//! * `AssignOp` -> `CompoundAssignment`
//! * `Barrier` -> `QuantumBarrier`
//! * `Box` -> `Box`
//! * `Break` -> `BreakStatement`
//! * `Block` -> `CompoundStatement`
//! * `Cal` -> `CalibrationStatement`
//! * `CalibrationGrammar` -> `CalibrationGrammarDeclaration`
//! * `ClassicalDecl` -> `ClassicalDeclaration`
//! * `ConstDecl` -> `ConstantDeclaration`
//! * `Continue` -> `ContinueStatement`
//! * `Def` -> `SubroutineDefinition`
//! * `DefCal` -> `CalibrationDefinition`
//! * `Delay` -> `DelayInstruction`
//! * `End` -> `EndStatement`
//! * `ExprStmt` -> `ExpressionStatement`
//! * `ExternDecl` -> `ExternDeclaration`
//! * `For` -> `ForInLoop`
//! * `If` -> `BranchingStatement`
//! * `GateCall` -> `QuantumGate`
//! * `GPhase` -> `QuantumPhase`
//! * `Include` -> `Include`
//! * `IODeclaration` -> `IODeclaration`
//! * `Measure` -> `QuantumMeasurementStatement`
//! * `Pragma` -> `Pragma`
//! * `QuantumGateDefinition` -> `QuantumGateDefinition`
//! * `QuantumDecl` -> `QubitDeclaration`
//! * `Reset` -> `QuantumReset`
//! * `Return` -> `ReturnStatement`
//! * `Switch` -> `SwitchStatement`
//! * `WhileLoop` -> `WhileLoop`
//! * `Err` -> `ErrorStatement`
//!
//! Expressions (`ExprKind` -> class):
//! * `Err` -> `ErrorExpression`
//! * `Ident` -> `Identifier`
//! * `UnaryOp` -> `UnaryExpression`
//! * `BinaryOp` -> `BinaryExpression`
//! * `Lit` -> `IntegerLiteral`, `FloatLiteral`, `ImaginaryLiteral`,
//!   `BooleanLiteral`, `BitstringLiteral`, `DurationLiteral`, `ArrayLiteral`,
//!   or the QDK-specific `StringLiteral`
//! * `FunctionCall` -> `FunctionCall`
//! * `Cast` -> `Cast`
//! * `IndexExpr` -> `IndexExpression`
//! * `Paren` -> `ParenExpression`
//! * `DurationOf` -> `DurationOf`
//!
//! Auxiliary syntactic nodes with no direct `ExprKind` / `StmtKind` variant:
//! * An indexed identifier (`a[i]` in an l-value position) -> `IndexedIdentifier`
//! * A hardware-qubit gate operand (`$0`) -> `HardwareQubit`
//! * A concatenation r-value (`a ++ b`) -> `Concatenation`
//! * A measurement r-value (`measure q`) -> `QuantumMeasurement`
//! * A gate modifier (`ctrl @`, `pow(2) @`) -> `QuantumGateModifier`

use crate::openqasm::nodes::{Annotation, ClassicalType, Expression, QASMNode, Statement};
use crate::openqasm::repr::{py_items, py_opt_str};
use crate::openqasm::source::SourceDocument;
use crate::openqasm::span::Span;
use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use qdk_openqasm::parser::ast::{self, PathKind, Program as SyntaxProgram};

// ----------------------------------------------------------------------------
// Category bases
// ----------------------------------------------------------------------------

/// Builds the initializer chain `QASMNode -> Expression`.
fn syntax_expr_base(span: Span) -> PyClassInitializer<Expression> {
    PyClassInitializer::from(QASMNode { span }).add_subclass(Expression)
}

/// Builds the initializer chain `QASMNode -> Statement`.
fn syntax_stmt_base(span: Span, annotations: Vec<Py<Annotation>>) -> PyClassInitializer<Statement> {
    PyClassInitializer::from(QASMNode { span }).add_subclass(Statement { annotations })
}

/// Builds the initializer chain `QASMNode -> ClassicalType`.
fn syntax_type_base(span: Span) -> PyClassInitializer<ClassicalType> {
    PyClassInitializer::from(QASMNode { span }).add_subclass(ClassicalType)
}

/// A binary operator.
///
/// Member names are descriptive because the `openqasm3` reference enum names
/// its members by symbol, which are not Python identifiers. The OpenQASM
/// spelling is available as `value`.
#[pyclass(
    module = "qdk.openqasm.parser",
    eq,
    eq_int,
    frozen,
    hash,
    from_py_object
)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub(crate) enum BinaryOperator {
    #[pyo3(name = "ADD")]
    Add,
    #[pyo3(name = "SUB")]
    Sub,
    #[pyo3(name = "MUL")]
    Mul,
    #[pyo3(name = "DIV")]
    Div,
    #[pyo3(name = "MOD")]
    Mod,
    #[pyo3(name = "POW")]
    Pow,
    #[pyo3(name = "EQ")]
    Eq,
    #[pyo3(name = "NEQ")]
    Neq,
    #[pyo3(name = "GT")]
    Gt,
    #[pyo3(name = "GTE")]
    Gte,
    #[pyo3(name = "LT")]
    Lt,
    #[pyo3(name = "LTE")]
    Lte,
    #[pyo3(name = "LOGIC_AND")]
    LogicAnd,
    #[pyo3(name = "LOGIC_OR")]
    LogicOr,
    #[pyo3(name = "BIT_AND")]
    BitAnd,
    #[pyo3(name = "BIT_OR")]
    BitOr,
    #[pyo3(name = "BIT_XOR")]
    BitXor,
    #[pyo3(name = "SHL")]
    Shl,
    #[pyo3(name = "SHR")]
    Shr,
}

impl BinaryOperator {
    fn symbol(self) -> &'static str {
        match self {
            Self::Add => "+",
            Self::Sub => "-",
            Self::Mul => "*",
            Self::Div => "/",
            Self::Mod => "%",
            Self::Pow => "**",
            Self::Eq => "==",
            Self::Neq => "!=",
            Self::Gt => ">",
            Self::Gte => ">=",
            Self::Lt => "<",
            Self::Lte => "<=",
            Self::LogicAnd => "&&",
            Self::LogicOr => "||",
            Self::BitAnd => "&",
            Self::BitOr => "|",
            Self::BitXor => "^",
            Self::Shl => "<<",
            Self::Shr => ">>",
        }
    }

    fn variant_name(self) -> &'static str {
        match self {
            Self::Add => "ADD",
            Self::Sub => "SUB",
            Self::Mul => "MUL",
            Self::Div => "DIV",
            Self::Mod => "MOD",
            Self::Pow => "POW",
            Self::Eq => "EQ",
            Self::Neq => "NEQ",
            Self::Gt => "GT",
            Self::Gte => "GTE",
            Self::Lt => "LT",
            Self::Lte => "LTE",
            Self::LogicAnd => "LOGIC_AND",
            Self::LogicOr => "LOGIC_OR",
            Self::BitAnd => "BIT_AND",
            Self::BitOr => "BIT_OR",
            Self::BitXor => "BIT_XOR",
            Self::Shl => "SHL",
            Self::Shr => "SHR",
        }
    }
}

impl From<ast::BinOp> for BinaryOperator {
    fn from(op: ast::BinOp) -> Self {
        match op {
            ast::BinOp::Add => Self::Add,
            ast::BinOp::Sub => Self::Sub,
            ast::BinOp::Mul => Self::Mul,
            ast::BinOp::Div => Self::Div,
            ast::BinOp::Mod => Self::Mod,
            ast::BinOp::Exp => Self::Pow,
            ast::BinOp::Eq => Self::Eq,
            ast::BinOp::Neq => Self::Neq,
            ast::BinOp::Gt => Self::Gt,
            ast::BinOp::Gte => Self::Gte,
            ast::BinOp::Lt => Self::Lt,
            ast::BinOp::Lte => Self::Lte,
            ast::BinOp::AndL => Self::LogicAnd,
            ast::BinOp::OrL => Self::LogicOr,
            ast::BinOp::AndB => Self::BitAnd,
            ast::BinOp::OrB => Self::BitOr,
            ast::BinOp::XorB => Self::BitXor,
            ast::BinOp::Shl => Self::Shl,
            ast::BinOp::Shr => Self::Shr,
        }
    }
}

#[pymethods]
impl BinaryOperator {
    /// The OpenQASM spelling of the operator, for example `">="`.
    #[getter]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn value(&self) -> &'static str {
        (*self).symbol()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __str__(&self) -> &'static str {
        (*self).symbol()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __repr__(&self) -> String {
        format!("BinaryOperator.{}", (*self).variant_name())
    }
}

/// A unary operator.
#[pyclass(
    module = "qdk.openqasm.parser",
    eq,
    eq_int,
    frozen,
    hash,
    from_py_object
)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub(crate) enum UnaryOperator {
    #[pyo3(name = "NEG")]
    Neg,
    #[pyo3(name = "BIT_NOT")]
    BitNot,
    #[pyo3(name = "LOGIC_NOT")]
    LogicNot,
}

impl UnaryOperator {
    fn symbol(self) -> &'static str {
        match self {
            Self::Neg => "-",
            Self::BitNot => "~",
            Self::LogicNot => "!",
        }
    }

    fn variant_name(self) -> &'static str {
        match self {
            Self::Neg => "NEG",
            Self::BitNot => "BIT_NOT",
            Self::LogicNot => "LOGIC_NOT",
        }
    }
}

impl From<ast::UnaryOp> for UnaryOperator {
    fn from(op: ast::UnaryOp) -> Self {
        match op {
            ast::UnaryOp::Neg => Self::Neg,
            ast::UnaryOp::NotB => Self::BitNot,
            ast::UnaryOp::NotL => Self::LogicNot,
        }
    }
}

#[pymethods]
impl UnaryOperator {
    /// The OpenQASM spelling of the operator, for example `"~"`.
    #[getter]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn value(&self) -> &'static str {
        (*self).symbol()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __str__(&self) -> &'static str {
        (*self).symbol()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __repr__(&self) -> String {
        format!("UnaryOperator.{}", (*self).variant_name())
    }
}

/// The time unit of a duration literal.
#[pyclass(
    module = "qdk.openqasm.parser",
    eq,
    eq_int,
    frozen,
    hash,
    from_py_object
)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub(crate) enum TimeUnit {
    #[pyo3(name = "DT")]
    Dt,
    #[pyo3(name = "NS")]
    Ns,
    #[pyo3(name = "US")]
    Us,
    #[pyo3(name = "MS")]
    Ms,
    #[pyo3(name = "S")]
    S,
}

impl TimeUnit {
    fn variant_name(self) -> &'static str {
        match self {
            Self::Dt => "DT",
            Self::Ns => "NS",
            Self::Us => "US",
            Self::Ms => "MS",
            Self::S => "S",
        }
    }

    /// The Python spelling of this unit, reusable by other `__repr__` bodies.
    pub(crate) fn py_repr(self) -> String {
        format!("TimeUnit.{}", self.variant_name())
    }
}

impl From<&ast::TimeUnit> for TimeUnit {
    fn from(unit: &ast::TimeUnit) -> Self {
        match unit {
            ast::TimeUnit::Dt => Self::Dt,
            ast::TimeUnit::Ns => Self::Ns,
            ast::TimeUnit::Us => Self::Us,
            ast::TimeUnit::Ms => Self::Ms,
            ast::TimeUnit::S => Self::S,
        }
    }
}

#[pymethods]
impl TimeUnit {
    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __str__(&self) -> &'static str {
        (*self).variant_name()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __repr__(&self) -> String {
        (*self).py_repr()
    }
}

/// Whether an array reference parameter may be written through.
#[pyclass(
    module = "qdk.openqasm.parser",
    eq,
    eq_int,
    frozen,
    hash,
    from_py_object
)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub(crate) enum AccessControl {
    #[pyo3(name = "READONLY")]
    ReadOnly,
    #[pyo3(name = "MUTABLE")]
    Mutable,
}

impl AccessControl {
    fn variant_name(self) -> &'static str {
        match self {
            Self::ReadOnly => "READONLY",
            Self::Mutable => "MUTABLE",
        }
    }
}

impl From<&ast::AccessControl> for AccessControl {
    fn from(access: &ast::AccessControl) -> Self {
        match access {
            ast::AccessControl::ReadOnly => Self::ReadOnly,
            ast::AccessControl::Mutable => Self::Mutable,
        }
    }
}

#[pymethods]
impl AccessControl {
    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __str__(&self) -> &'static str {
        (*self).variant_name()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __repr__(&self) -> String {
        format!("AccessControl.{}", (*self).variant_name())
    }
}

/// The direction of an `input` or `output` declaration.
#[pyclass(
    module = "qdk.openqasm.parser",
    eq,
    eq_int,
    frozen,
    hash,
    from_py_object
)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub(crate) enum IOKeyword {
    #[pyo3(name = "INPUT")]
    Input,
    #[pyo3(name = "OUTPUT")]
    Output,
}

impl IOKeyword {
    fn keyword(self) -> &'static str {
        match self {
            Self::Input => "input",
            Self::Output => "output",
        }
    }

    fn variant_name(self) -> &'static str {
        match self {
            Self::Input => "INPUT",
            Self::Output => "OUTPUT",
        }
    }
}

impl From<ast::IOKeyword> for IOKeyword {
    fn from(keyword: ast::IOKeyword) -> Self {
        match keyword {
            ast::IOKeyword::Input => Self::Input,
            ast::IOKeyword::Output => Self::Output,
        }
    }
}

#[pymethods]
impl IOKeyword {
    /// The `OpenQASM` keyword, either `"input"` or `"output"`.
    #[getter]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn value(&self) -> &'static str {
        (*self).keyword()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __str__(&self) -> &'static str {
        (*self).keyword()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __repr__(&self) -> String {
        format!("IOKeyword.{}", (*self).variant_name())
    }
}

/// The keyword naming a quantum gate modifier.
#[pyclass(
    module = "qdk.openqasm.parser",
    eq,
    eq_int,
    frozen,
    hash,
    from_py_object
)]
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub(crate) enum GateModifierName {
    #[pyo3(name = "INV")]
    Inv,
    #[pyo3(name = "POW")]
    Pow,
    #[pyo3(name = "CTRL")]
    Ctrl,
    #[pyo3(name = "NEGCTRL")]
    NegCtrl,
}

impl GateModifierName {
    fn keyword(self) -> &'static str {
        match self {
            Self::Inv => "inv",
            Self::Pow => "pow",
            Self::Ctrl => "ctrl",
            Self::NegCtrl => "negctrl",
        }
    }

    fn variant_name(self) -> &'static str {
        match self {
            Self::Inv => "INV",
            Self::Pow => "POW",
            Self::Ctrl => "CTRL",
            Self::NegCtrl => "NEGCTRL",
        }
    }
}

impl From<&ast::GateModifierKind> for GateModifierName {
    fn from(kind: &ast::GateModifierKind) -> Self {
        match kind {
            ast::GateModifierKind::Inv => Self::Inv,
            ast::GateModifierKind::Pow(_) => Self::Pow,
            ast::GateModifierKind::Ctrl(_) => Self::Ctrl,
            ast::GateModifierKind::NegCtrl(_) => Self::NegCtrl,
        }
    }
}

#[pymethods]
impl GateModifierName {
    /// The `OpenQASM` keyword, for example `"negctrl"`.
    #[getter]
    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn value(&self) -> &'static str {
        (*self).keyword()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __str__(&self) -> &'static str {
        (*self).keyword()
    }

    #[allow(clippy::trivially_copy_pass_by_ref)]
    fn __repr__(&self) -> String {
        format!("GateModifierName.{}", (*self).variant_name())
    }
}

// ----------------------------------------------------------------------------
// Program root
// ----------------------------------------------------------------------------

/// The root of a parsed `OpenQASM` program.
#[pyclass(extends = QASMNode, frozen, module = "qdk.openqasm.parser")]
pub(crate) struct Program {
    statements: Vec<Py<PyAny>>,
    version: Option<String>,
    document: Py<SourceDocument>,
}

impl Program {
    pub(crate) fn source_document(&self, py: Python<'_>) -> Py<SourceDocument> {
        self.document.clone_ref(py)
    }
}

#[pymethods]
impl Program {
    /// The top-level statements of the program, in source order.
    #[getter]
    fn statements(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        self.statements
            .iter()
            .map(|stmt| stmt.clone_ref(py))
            .collect()
    }

    /// The declared `OpenQASM` version, if any (for example `"3.0"`).
    #[getter]
    fn version(&self) -> Option<String> {
        self.version.clone()
    }

    /// The immutable source document for this parse snapshot.
    #[getter]
    fn document(&self, py: Python<'_>) -> Py<SourceDocument> {
        self.document.clone_ref(py)
    }

    /// The program's child nodes: its top-level statements.
    fn children(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        self.statements
            .iter()
            .map(|stmt| stmt.clone_ref(py))
            .collect()
    }

    fn __repr__(&self) -> String {
        format!(
            "Program(statements={}, version={})",
            py_items(self.statements.len()),
            py_opt_str(self.version.as_deref())
        )
    }

    // `document` is excluded: `SourceDocument` is `eq` without `hash`, so
    // including it would make every program unhashable.
    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(slf.as_any(), other, &["statements", "version"])
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(slf.as_any(), &["statements", "version"])
    }
}

/// A quantum gate modifier (for example `ctrl @`, `inv @`, or `pow(2) @`).
///
/// This extends [`QASMNode`] directly, mirroring the `openqasm3`
/// `QuantumGateModifier` node, which is neither an expression nor a statement.
#[pyclass(extends = QASMNode, frozen, module = "qdk.openqasm.parser")]
pub(crate) struct QuantumGateModifier {
    /// The modifier keyword.
    #[pyo3(get)]
    modifier: GateModifierName,
    /// The modifier's argument expression, if any (the exponent for `pow` or the
    /// optional control count for `ctrl` / `negctrl`).
    #[pyo3(get)]
    argument: Option<Py<PyAny>>,
}

#[pymethods]
impl QuantumGateModifier {
    /// The modifier's child nodes: its argument expression, if present.
    fn children(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        match &self.argument {
            Some(argument) => vec![argument.clone_ref(py)],
            None => Vec::new(),
        }
    }

    fn __repr__(&self) -> String {
        format!("QuantumGateModifier(modifier={})", self.modifier.__repr__())
    }

    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(slf.as_any(), other, &["modifier", "argument"])
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(slf.as_any(), &["modifier", "argument"])
    }
}

impl QuantumGateModifier {
    fn build(
        py: Python<'_>,
        span: Span,
        modifier: GateModifierName,
        argument: Option<Py<PyAny>>,
    ) -> PyResult<Py<PyAny>> {
        let init = PyClassInitializer::from(QASMNode { span })
            .add_subclass(QuantumGateModifier { modifier, argument });
        Ok(Py::new(py, init)?.into_any())
    }
}

// ----------------------------------------------------------------------------
// Expression leaf nodes
// ----------------------------------------------------------------------------

qasm_node!(@sexpr Identifier {
    /// The identifier's source text.
    name: val String,
});
qasm_node!(@sexpr IndexedIdentifier {
    /// The identifier being indexed.
    name: node,
    /// The index lists applied to the identifier, outermost first.
    indices: list,
});
qasm_node!(@sexpr HardwareQubit {
    /// The hardware qubit's identifier text, including the leading `$`.
    name: val String,
});
qasm_node!(@sexpr ErrorExpression {});
qasm_node!(@sexpr UnaryExpression {
    /// The unary operator applied to the operand.
    op: val UnaryOperator,
    /// The expression the operator is applied to.
    operand: node,
});
qasm_node!(@sexpr BinaryExpression {
    /// The binary operator joining the two operands.
    op: val BinaryOperator,
    /// The left operand.
    lhs: node,
    /// The right operand.
    rhs: node,
});
qasm_node!(@sexpr IntegerLiteral {
    /// The literal's value as a Python `int`, of unbounded width.
    value: val Py<PyAny>,
});
qasm_node!(@sexpr FloatLiteral {
    /// The literal's value.
    value: val f64,
});
qasm_node!(@sexpr ImaginaryLiteral {
    /// The imaginary coefficient, so `2.0im` carries `2.0`.
    value: val f64,
});
qasm_node!(@sexpr BooleanLiteral {
    /// The literal's value.
    value: val bool,
});
qasm_node!(@sexpr BitstringLiteral {
    /// The bit pattern as a Python `int`, with the leftmost bit most significant.
    value: val Py<PyAny>,
    /// The number of bits written in the source, including leading zeros.
    width: val u32,
});
qasm_node!(@sexpr DurationLiteral {
    /// The numeric part of the duration.
    value: val f64,
    /// The time unit the value is expressed in.
    unit: val TimeUnit,
});
qasm_node!(@sexpr ArrayLiteral {
    /// The literal's elements, in source order.
    values: list,
});
qasm_node!(@sexpr StringLiteral {
    /// The string's contents, with the surrounding quotes removed.
    value: val String,
});
qasm_node!(@sexpr FunctionCall {
    /// The identifier naming the callee.
    name: node,
    /// The call arguments, in source order.
    args: list,
});
qasm_node!(@sexpr Cast {
    /// The type the operand is cast to.
    r#type: node,
    /// The expression being cast.
    operand: node,
});
qasm_node!(@sexpr IndexExpression {
    /// The expression being indexed.
    collection: node,
    /// The index lists applied to the collection, outermost first.
    indices: list,
});
qasm_node!(@sexpr ParenExpression {
    /// The expression inside the parentheses.
    operand: node,
});
qasm_node!(@sexpr DurationOf {
    /// The statements whose duration is being measured.
    body: list,
});
qasm_node!(@sexpr Concatenation {
    /// The operands joined by `++`, in source order.
    operands: list,
});
qasm_node!(@sexpr QuantumMeasurement {
    /// The qubits being measured.
    qubits: list,
});
qasm_node!(@saux RangeDefinition, doc = "A range used in an index or a `for` loop." {
    /// The inclusive start of the range, when written.
    start: opt,
    /// The step between values, when written.
    step: opt,
    /// The inclusive end of the range, when written.
    end: opt,
});
qasm_node!(@saux DiscreteSet, doc = "A brace-enclosed set of values." {
    /// The set's members, in source order.
    values: list,
});
qasm_node!(@saux IndexList, doc = "The entries of one index bracket." {
    /// The entries of one index bracket, in source order.
    values: list,
});
qasm_node!(@saux SwitchCase, doc = "One `case` branch of a switch statement." {
    /// The case labels this branch matches.
    labels: list,
    /// The statements run when a label matches.
    body: list,
});
qasm_node!(@saux SubroutineParameter, doc = "One declared parameter of a subroutine." {
    /// The parameter's name.
    identifier: node,
    /// The parameter's declared type.
    r#type: node,
});

// ----------------------------------------------------------------------------
// Type nodes
// ----------------------------------------------------------------------------

qasm_node!(@stype IntType {
    /// The declared bit width, when written.
    size: opt,
});
qasm_node!(@stype UintType {
    /// The declared bit width, when written.
    size: opt,
});
qasm_node!(@stype FloatType {
    /// The declared bit width, when written.
    size: opt,
});
qasm_node!(@stype AngleType {
    /// The declared bit width, when written.
    size: opt,
});
qasm_node!(@stype BitType {
    /// The declared register width, when written.
    size: opt,
});
qasm_node!(@stype ComplexType {
    /// The component type of the real and imaginary parts, when written.
    base_type: opt,
});
qasm_node!(@stype BoolType {});
qasm_node!(@stype DurationType {});
qasm_node!(@stype StretchType {});
qasm_node!(@stype QubitType {
    /// The declared register width, when written.
    size: opt,
});
qasm_node!(@stype ErrorType {});
qasm_node!(@stype ArrayType {
    /// The element type.
    base_type: node,
    /// The length of each dimension, outermost first.
    dimensions: list,
});
qasm_node!(@stype StaticArrayReferenceType {
    /// The element type.
    base_type: node,
    /// The length of each dimension, outermost first.
    dimensions: list,
    /// Whether the referenced array is readonly or mutable.
    mutability: val AccessControl,
});
qasm_node!(@stype DynArrayReferenceType {
    /// The element type.
    base_type: node,
    /// The expression giving the number of dimensions.
    num_dimensions: node,
    /// Whether the referenced array is readonly or mutable.
    mutability: val AccessControl,
});

// ----------------------------------------------------------------------------
// Statement leaf nodes
// ----------------------------------------------------------------------------

qasm_node!(@sstmt QubitDeclaration {
    /// The identifier naming the declared qubit or register.
    qubit: node,
    /// The register width, when the declaration is an array.
    size: opt,
});
qasm_node!(@sstmt AliasStatement {
    /// The identifier the alias binds.
    target: node,
    /// The expressions the alias refers to, joined by `++` when several.
    exprs: list,
});
qasm_node!(@sstmt ClassicalAssignment {
    /// The assignment target.
    lhs: node,
    /// The assigned value.
    rhs: node,
});
qasm_node!(@sstmt CompoundAssignment {
    /// The underlying operator, so `+=` reports addition.
    op: val BinaryOperator,
    /// The assignment target.
    lhs: node,
    /// The right operand of the compound operation.
    rhs: node,
});
qasm_node!(@sstmt QuantumBarrier {
    /// The qubits the barrier applies to.
    qubits: list,
});
qasm_node!(@sstmt Box {
    /// The box's declared duration, when written.
    duration: opt,
    /// The statements inside the box.
    body: list,
});
qasm_node!(@sstmt BreakStatement {});
qasm_node!(@sstmt CompoundStatement {
    /// The statements inside the block, in source order.
    statements: list,
});
qasm_node!(@sstmt CalibrationStatement {
    /// The calibration block's raw text, which this parser does not interpret.
    body: val String,
});
qasm_node!(@sstmt CalibrationGrammarDeclaration {
    /// The named calibration grammar, for example `openpulse`.
    name: val String,
});
qasm_node!(@sstmt ClassicalDeclaration {
    /// The declared type.
    r#type: node,
    /// The identifier being declared.
    identifier: node,
    /// The initializer, when the declaration has one.
    init_expr: opt,
});
qasm_node!(@sstmt ConstantDeclaration {
    /// The declared type.
    r#type: node,
    /// The identifier being declared.
    identifier: node,
    /// The initializer, which a constant always has.
    init_expr: node,
});
qasm_node!(@sstmt ContinueStatement {});
qasm_node!(@sstmt SubroutineDefinition {
    /// The identifier naming the subroutine.
    name: node,
    /// The declared parameters, in source order.
    params: list,
    /// The declared return type, when the subroutine returns a value.
    return_type: opt,
    /// The statements making up the subroutine body.
    body: list,
});
qasm_node!(@sstmt CalibrationDefinition {
    /// The `defcal` block's raw text, which this parser does not interpret.
    body: val String,
});
qasm_node!(@sstmt DelayInstruction {
    /// The delay's duration.
    duration: node,
    /// The qubits the delay applies to.
    qubits: list,
});
qasm_node!(@sstmt EndStatement {});
qasm_node!(@sstmt ExpressionStatement {
    /// The evaluated expression.
    expr: node,
});
qasm_node!(@sstmt ExternDeclaration {
    /// The identifier naming the external subroutine.
    name: node,
    /// The declared parameter types, in source order.
    param_types: list,
    /// The declared return type, when the subroutine returns a value.
    return_type: opt,
});
qasm_node!(@sstmt ForInLoop {
    /// The loop variable's declared type.
    r#type: node,
    /// The loop variable.
    identifier: node,
    /// The range, set, or expression being iterated.
    iterable: node,
    /// The loop body.
    body: node,
});
qasm_node!(@sstmt BranchingStatement {
    /// The branch condition.
    condition: node,
    /// The statement run when the condition holds.
    if_body: node,
    /// The `else` branch, when written.
    else_body: opt,
});
qasm_node!(@sstmt QuantumGate {
    /// The identifier naming the gate.
    name: node,
    /// The modifiers applied to the gate, such as `ctrl` or `inv`.
    modifiers: list,
    /// The classical arguments, such as a rotation angle.
    args: list,
    /// The qubit operands the gate acts on.
    qubits: list,
    /// The gate's declared duration, when written.
    duration: opt,
});
qasm_node!(@sstmt QuantumPhase {
    /// The modifiers applied to the phase, such as `ctrl`.
    modifiers: list,
    /// The phase arguments.
    args: list,
    /// The qubit operands, present only when the phase is controlled.
    qubits: list,
    /// The declared duration, when written.
    duration: opt,
});
qasm_node!(@sstmt Include {
    /// The included file's path as written in the source.
    filename: val String,
});
qasm_node!(@sstmt IODeclaration {
    /// Whether the declaration is an `input` or an `output`.
    io_keyword: val IOKeyword,
    /// The declared type.
    r#type: node,
    /// The identifier being declared.
    identifier: node,
});
qasm_node!(@sstmt QuantumMeasurementStatement {
    /// The qubits being measured.
    qubits: list,
    /// The classical target the result is written to, when written.
    target: opt,
});
qasm_node!(@sstmt Pragma {
    /// The pragma's full text after the keyword.
    command: val String,
    /// The leading dotted identifier, when the pragma has one.
    name: val Option<String>,
    /// The remaining text after the identifier, when present.
    value: val Option<String>,
});
qasm_node!(@sstmt QuantumGateDefinition {
    /// The identifier naming the gate.
    name: node,
    /// The classical parameters, in source order.
    params: list,
    /// The qubit parameters, in source order.
    qubits: list,
    /// The statements making up the gate body.
    body: list,
});
qasm_node!(@sstmt QuantumReset {
    /// The qubits being reset.
    qubits: list,
});
qasm_node!(@sstmt ReturnStatement {
    /// The returned expression, when the subroutine returns a value.
    value: opt,
});
/// A read-only OpenQASM `SwitchStatement` node.
#[pyclass(extends = Statement, frozen, module = "qdk.openqasm.parser")]
pub(crate) struct SwitchStatement {
    /// The expression being switched on.
    #[pyo3(get)]
    target: Py<PyAny>,
    /// The `case` branches, in source order.
    #[pyo3(get)]
    cases: Vec<Py<PyAny>>,
    default: Option<Vec<Py<PyAny>>>,
}

#[pymethods]
impl SwitchStatement {
    /// The `default` branch's statements, or `None` when there is no `default`.
    #[getter]
    fn default(&self, py: Python<'_>) -> Option<Vec<Py<PyAny>>> {
        self.default
            .as_ref()
            .map(|body| body.iter().map(|stmt| stmt.clone_ref(py)).collect())
    }

    /// The node's child nodes: the annotations, the target, then the cases,
    /// then any default body.
    // `PyRef` is the receiver form PyO3 requires to reach the base class.
    #[allow(clippy::needless_pass_by_value)]
    fn children(slf: PyRef<'_, Self>) -> Vec<Py<PyAny>> {
        let py = slf.py();
        let annotations = &slf.as_super().annotations;
        let default_len = slf.default.as_ref().map_or(0, Vec::len);
        let mut children =
            Vec::with_capacity(annotations.len() + 1 + slf.cases.len() + default_len);
        children.extend(
            annotations
                .iter()
                .map(|annotation| annotation.clone_ref(py).into_any()),
        );
        children.push(slf.target.clone_ref(py));
        children.extend(slf.cases.iter().map(|case| case.clone_ref(py)));
        if let Some(default) = &slf.default {
            children.extend(default.iter().map(|stmt| stmt.clone_ref(py)));
        }
        children
    }

    fn __eq__(slf: &Bound<'_, Self>, other: &Bound<'_, PyAny>) -> PyResult<bool> {
        crate::openqasm::eq::structural_eq(
            slf.as_any(),
            other,
            &["annotations", "target", "cases", "default"],
        )
    }

    fn __hash__(slf: &Bound<'_, Self>) -> PyResult<isize> {
        crate::openqasm::eq::structural_hash(
            slf.as_any(),
            &["annotations", "target", "cases", "default"],
        )
    }
}

impl SwitchStatement {
    fn init(
        span: Span,
        annotations: Vec<Py<Annotation>>,
        target: Py<PyAny>,
        cases: Vec<Py<PyAny>>,
        default: Option<Vec<Py<PyAny>>>,
    ) -> PyClassInitializer<Self> {
        syntax_stmt_base(span, annotations).add_subclass(Self {
            target,
            cases,
            default,
        })
    }
}
qasm_node!(@sstmt WhileLoop {
    /// The loop condition, tested before each iteration.
    condition: node,
    /// The loop body.
    body: node,
});
qasm_node!(@sstmt ErrorStatement {});

// ----------------------------------------------------------------------------
// Registration
// ----------------------------------------------------------------------------

macro_rules! register_syntax_nodes {
    ($m:ident; $($ty:ty),* $(,)?) => {
        $($m.add_class::<$ty>()?;)*
    };
}

/// Registers all syntactic node classes with the native module.
pub(crate) fn register_syntax_nodes(m: &Bound<'_, PyModule>) -> PyResult<()> {
    m.add_class::<AccessControl>()?;
    m.add_class::<BinaryOperator>()?;
    m.add_class::<UnaryOperator>()?;
    m.add_class::<TimeUnit>()?;
    m.add_class::<IOKeyword>()?;
    m.add_class::<GateModifierName>()?;
    register_syntax_nodes!(m;
        Program,
        QuantumGateModifier,
        IntType,
        UintType,
        FloatType,
        AngleType,
        BitType,
        ComplexType,
        BoolType,
        DurationType,
        StretchType,
        QubitType,
        ErrorType,
        ArrayType,
        StaticArrayReferenceType,
        DynArrayReferenceType,
        Identifier,
        IndexedIdentifier,
        HardwareQubit,
        ErrorExpression,
        UnaryExpression,
        BinaryExpression,
        IntegerLiteral,
        FloatLiteral,
        ImaginaryLiteral,
        BooleanLiteral,
        BitstringLiteral,
        DurationLiteral,
        ArrayLiteral,
        StringLiteral,
        FunctionCall,
        Cast,
        IndexExpression,
        ParenExpression,
        DurationOf,
        Concatenation,
        QuantumMeasurement,
        RangeDefinition,
        DiscreteSet,
        IndexList,
        SwitchCase,
        SubroutineParameter,
        QubitDeclaration,
        AliasStatement,
        ClassicalAssignment,
        CompoundAssignment,
        QuantumBarrier,
        Box,
        BreakStatement,
        CompoundStatement,
        CalibrationStatement,
        CalibrationGrammarDeclaration,
        ClassicalDeclaration,
        ConstantDeclaration,
        ContinueStatement,
        SubroutineDefinition,
        CalibrationDefinition,
        DelayInstruction,
        EndStatement,
        ExpressionStatement,
        ExternDeclaration,
        ForInLoop,
        BranchingStatement,
        QuantumGate,
        QuantumPhase,
        Include,
        IODeclaration,
        QuantumMeasurementStatement,
        Pragma,
        QuantumGateDefinition,
        QuantumReset,
        ReturnStatement,
        SwitchStatement,
        WhileLoop,
        ErrorStatement,
    );
    Ok(())
}

// ----------------------------------------------------------------------------
// Syntax AST -> Python node tree
// ----------------------------------------------------------------------------

/// Builds the Python [`Program`] root from a parsed syntax program.
///
/// When `program` is `None` (for example when the source failed to parse into a
/// tree at all), an empty program is returned so callers still receive a
/// well-formed root alongside the diagnostics.
pub(crate) fn build_program(
    py: Python<'_>,
    program: Option<&SyntaxProgram>,
    document: Py<SourceDocument>,
) -> PyResult<Py<Program>> {
    let (span, statements, version) = match program {
        Some(program) => {
            let mut statements = Vec::with_capacity(program.statements.len());
            for stmt in &program.statements {
                statements.push(build_stmt(py, stmt)?);
            }
            let version = program.version.as_ref().map(ToString::to_string);
            (Span::from(program.span), statements, version)
        }
        None => (Span { lo: 0, hi: 0 }, Vec::new(), None),
    };

    let init = PyClassInitializer::from(QASMNode { span }).add_subclass(Program {
        statements,
        version,
        document,
    });
    Py::new(py, init)
}

#[allow(clippy::too_many_lines)]
fn build_stmt(py: Python<'_>, stmt: &ast::Stmt) -> PyResult<Py<PyAny>> {
    let span = Span::from(stmt.span);
    let annotations = build_annotations(py, &stmt.annotations)?;
    let obj: Py<PyAny> = match stmt.kind.as_ref() {
        ast::StmtKind::Alias(s) => {
            let target = build_ident_or_indexed(py, &s.ident)?;
            let exprs = expr_list(py, &s.exprs)?;
            Py::new(py, AliasStatement::init(span, annotations, target, exprs))?.into_any()
        }
        ast::StmtKind::Assign(s) => {
            let lhs = build_ident_or_indexed(py, &s.lhs)?;
            let rhs = build_value_expr(py, &s.rhs)?;
            Py::new(py, ClassicalAssignment::init(span, annotations, lhs, rhs))?.into_any()
        }
        ast::StmtKind::AssignOp(s) => {
            let lhs = build_ident_or_indexed(py, &s.lhs)?;
            let rhs = build_value_expr(py, &s.rhs)?;
            Py::new(
                py,
                CompoundAssignment::init(span, annotations, s.op.into(), lhs, rhs),
            )?
            .into_any()
        }
        ast::StmtKind::Barrier(s) => {
            let qubits = gate_operand_list(py, &s.qubits)?;
            Py::new(py, QuantumBarrier::init(span, annotations, qubits))?.into_any()
        }
        ast::StmtKind::Box(s) => {
            let duration = opt_expr(py, s.duration.as_ref())?;
            let body = stmt_list(py, &s.body)?;
            Py::new(py, Box::init(span, annotations, duration, body))?.into_any()
        }
        ast::StmtKind::Break(_) => Py::new(py, BreakStatement::init(span, annotations))?.into_any(),
        ast::StmtKind::Block(s) => {
            let statements = stmt_list(py, &s.stmts)?;
            Py::new(py, CompoundStatement::init(span, annotations, statements))?.into_any()
        }
        ast::StmtKind::Cal(s) => Py::new(
            py,
            CalibrationStatement::init(span, annotations, s.content.to_string()),
        )?
        .into_any(),
        ast::StmtKind::CalibrationGrammar(s) => Py::new(
            py,
            CalibrationGrammarDeclaration::init(span, annotations, s.name.to_string()),
        )?
        .into_any(),
        ast::StmtKind::ClassicalDecl(s) => {
            let ty = build_type_definition(py, &s.ty)?;
            let identifier = build_identifier(py, &s.identifier)?;
            let init_expr = match s.init_expr.as_deref() {
                Some(init) => Some(build_value_expr(py, init)?),
                None => None,
            };
            Py::new(
                py,
                ClassicalDeclaration::init(span, annotations, ty, identifier, init_expr),
            )?
            .into_any()
        }
        ast::StmtKind::ConstDecl(s) => {
            let ty = build_type_definition(py, &s.ty)?;
            let identifier = build_identifier(py, &s.identifier)?;
            let init_expr = build_value_expr(py, &s.init_expr)?;
            Py::new(
                py,
                ConstantDeclaration::init(span, annotations, ty, identifier, init_expr),
            )?
            .into_any()
        }
        ast::StmtKind::Continue(_) => {
            Py::new(py, ContinueStatement::init(span, annotations))?.into_any()
        }
        ast::StmtKind::Def(s) => {
            let name = build_identifier(py, &s.name)?;
            let mut params = Vec::with_capacity(s.params.len());
            for param in &s.params {
                let identifier = build_identifier(py, &param.ident)?;
                let ty = build_def_parameter_type(py, param.ty.as_ref())?;
                params.push(
                    Py::new(
                        py,
                        SubroutineParameter::init(Span::from(param.span), identifier, ty),
                    )?
                    .into_any(),
                );
            }
            let return_type = s
                .return_type
                .as_ref()
                .map(|ty| build_scalar_type(py, ty))
                .transpose()?;
            let body = stmt_list(py, &s.body.stmts)?;
            Py::new(
                py,
                SubroutineDefinition::init(span, annotations, name, params, return_type, body),
            )?
            .into_any()
        }
        ast::StmtKind::DefCal(s) => Py::new(
            py,
            CalibrationDefinition::init(span, annotations, s.content.to_string()),
        )?
        .into_any(),
        ast::StmtKind::Delay(s) => {
            let duration = build_expr(py, &s.duration)?;
            let qubits = gate_operand_list(py, &s.qubits)?;
            Py::new(
                py,
                DelayInstruction::init(span, annotations, duration, qubits),
            )?
            .into_any()
        }
        ast::StmtKind::End(_) => Py::new(py, EndStatement::init(span, annotations))?.into_any(),
        ast::StmtKind::ExprStmt(s) => {
            let expr = build_expr(py, &s.expr)?;
            Py::new(py, ExpressionStatement::init(span, annotations, expr))?.into_any()
        }
        ast::StmtKind::ExternDecl(s) => {
            let name = build_identifier(py, &s.ident)?;
            let mut param_types = Vec::with_capacity(s.params.len());
            for param in &s.params {
                param_types.push(build_extern_parameter_type(py, param)?);
            }
            let return_type = s
                .return_type
                .as_ref()
                .map(|ty| build_scalar_type(py, ty))
                .transpose()?;
            Py::new(
                py,
                ExternDeclaration::init(span, annotations, name, param_types, return_type),
            )?
            .into_any()
        }
        ast::StmtKind::For(s) => {
            let ty = build_scalar_type(py, &s.ty)?;
            let identifier = build_identifier(py, &s.ident)?;
            let iterable = build_enumerable_set(py, &s.set_declaration)?;
            let body = build_stmt(py, &s.body)?;
            Py::new(
                py,
                ForInLoop::init(span, annotations, ty, identifier, iterable, body),
            )?
            .into_any()
        }
        ast::StmtKind::If(s) => {
            let condition = build_expr(py, &s.condition)?;
            let if_body = build_stmt(py, &s.if_body)?;
            let else_body = match &s.else_body {
                Some(else_body) => Some(build_stmt(py, else_body)?),
                None => None,
            };
            Py::new(
                py,
                BranchingStatement::init(span, annotations, condition, if_body, else_body),
            )?
            .into_any()
        }
        ast::StmtKind::GateCall(s) => {
            let name = build_identifier(py, &s.name)?;
            let modifiers = modifier_list(py, &s.modifiers)?;
            let args = expr_list(py, &s.args)?;
            let qubits = gate_operand_list(py, &s.qubits)?;
            let duration = opt_expr(py, s.duration.as_ref())?;
            Py::new(
                py,
                QuantumGate::init(span, annotations, name, modifiers, args, qubits, duration),
            )?
            .into_any()
        }
        ast::StmtKind::GPhase(s) => {
            let modifiers = modifier_list(py, &s.modifiers)?;
            let args = expr_list(py, &s.args)?;
            let qubits = gate_operand_list(py, &s.qubits)?;
            let duration = opt_expr(py, s.duration.as_ref())?;
            Py::new(
                py,
                QuantumPhase::init(span, annotations, modifiers, args, qubits, duration),
            )?
            .into_any()
        }
        ast::StmtKind::Include(s) => {
            Py::new(py, Include::init(span, annotations, s.filename.to_string()))?.into_any()
        }
        ast::StmtKind::IODeclaration(s) => {
            let ty = build_type_definition(py, &s.ty)?;
            let identifier = build_identifier(py, &s.ident)?;
            Py::new(
                py,
                IODeclaration::init(
                    span,
                    annotations,
                    IOKeyword::from(s.io_identifier),
                    ty,
                    identifier,
                ),
            )?
            .into_any()
        }
        ast::StmtKind::Measure(s) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &s.measurement.operand)?;
            let target = match &s.target {
                Some(target) => Some(build_ident_or_indexed(py, target)?),
                None => None,
            };
            Py::new(
                py,
                QuantumMeasurementStatement::init(span, annotations, qubits, target),
            )?
            .into_any()
        }
        ast::StmtKind::Pragma(s) => {
            let command = s.command.to_string();
            let name = s.identifier.as_ref().map(PathKind::as_string);
            let value = s.value.as_ref().map(ToString::to_string);
            Py::new(py, Pragma::init(span, annotations, command, name, value))?.into_any()
        }
        ast::StmtKind::QuantumGateDefinition(s) => {
            let name = build_identifier(py, &s.ident)?;
            let params = gate_ident_list(py, &s.params)?;
            let qubits = gate_ident_list(py, &s.qubits)?;
            let body = stmt_list(py, &s.body.stmts)?;
            Py::new(
                py,
                QuantumGateDefinition::init(span, annotations, name, params, qubits, body),
            )?
            .into_any()
        }
        ast::StmtKind::QuantumDecl(s) => {
            let qubit = build_identifier(py, &s.qubit)?;
            let size = opt_expr(py, s.ty.size.as_ref())?;
            Py::new(py, QubitDeclaration::init(span, annotations, qubit, size))?.into_any()
        }
        ast::StmtKind::Reset(s) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &s.operand)?;
            Py::new(py, QuantumReset::init(span, annotations, qubits))?.into_any()
        }
        ast::StmtKind::Return(s) => {
            let value = match s.expr.as_deref() {
                Some(expr) => Some(build_value_expr(py, expr)?),
                None => None,
            };
            Py::new(py, ReturnStatement::init(span, annotations, value))?.into_any()
        }
        ast::StmtKind::Switch(s) => {
            let target = build_expr(py, &s.target)?;
            let mut cases = Vec::with_capacity(s.cases.len());
            for case in &s.cases {
                let labels = expr_list(py, &case.labels)?;
                let body = stmt_list(py, &case.block.stmts)?;
                cases.push(
                    Py::new(py, SwitchCase::init(Span::from(case.span), labels, body))?.into_any(),
                );
            }
            let default = s
                .default
                .as_ref()
                .map(|block| stmt_list(py, &block.stmts))
                .transpose()?;
            Py::new(
                py,
                SwitchStatement::init(span, annotations, target, cases, default),
            )?
            .into_any()
        }
        ast::StmtKind::WhileLoop(s) => {
            let condition = build_expr(py, &s.while_condition)?;
            let body = build_stmt(py, &s.body)?;
            Py::new(py, WhileLoop::init(span, annotations, condition, body))?.into_any()
        }
        ast::StmtKind::Err => Py::new(py, ErrorStatement::init(span, annotations))?.into_any(),
    };
    Ok(obj)
}

fn build_annotations(
    py: Python<'_>,
    annotations: &[ast::Annotation],
) -> PyResult<Vec<Py<Annotation>>> {
    annotations
        .iter()
        .map(|annotation| {
            Py::new(
                py,
                Annotation::init(
                    Span::from(annotation.span),
                    annotation.identifier.as_string(),
                    annotation.value.as_ref().map(ToString::to_string),
                    annotation.value_span.map(Span::from),
                ),
            )
        })
        .collect()
}

fn build_expr(py: Python<'_>, expr: &ast::Expr) -> PyResult<Py<PyAny>> {
    let span = Span::from(expr.span);
    let obj: Py<PyAny> = match expr.kind.as_ref() {
        ast::ExprKind::Err => Py::new(py, ErrorExpression::init(span))?.into_any(),
        ast::ExprKind::Ident(ident) => build_identifier(py, ident)?,
        ast::ExprKind::UnaryOp(e) => {
            let operand = build_expr(py, &e.expr)?;
            Py::new(py, UnaryExpression::init(span, e.op.into(), operand))?.into_any()
        }
        ast::ExprKind::BinaryOp(e) => {
            let lhs = build_expr(py, &e.lhs)?;
            let rhs = build_expr(py, &e.rhs)?;
            Py::new(py, BinaryExpression::init(span, e.op.into(), lhs, rhs))?.into_any()
        }
        ast::ExprKind::Lit(lit) => build_literal(py, span, &lit.kind)?,
        ast::ExprKind::FunctionCall(e) => {
            let name = build_identifier(py, &e.name)?;
            let args = expr_list(py, &e.args)?;
            Py::new(py, FunctionCall::init(span, name, args))?.into_any()
        }
        ast::ExprKind::Cast(e) => {
            let ty = build_type_definition(py, &e.ty)?;
            let operand = build_expr(py, &e.arg)?;
            Py::new(py, Cast::init(span, ty, operand))?.into_any()
        }
        ast::ExprKind::IndexExpr(e) => {
            let collection = build_expr(py, &e.collection)?;
            let indices = vec![build_index(py, &e.index)?];
            Py::new(py, IndexExpression::init(span, collection, indices))?.into_any()
        }
        ast::ExprKind::Paren(inner) => {
            let operand = build_expr(py, inner)?;
            Py::new(py, ParenExpression::init(span, operand))?.into_any()
        }
        ast::ExprKind::DurationOf(d) => {
            let body = stmt_list(py, &d.scope.stmts)?;
            Py::new(py, DurationOf::init(span, body))?.into_any()
        }
    };
    Ok(obj)
}

/// Builds an [`Identifier`] expression node as an owned `Py<PyAny>`.
fn build_identifier(py: Python<'_>, ident: &ast::Ident) -> PyResult<Py<PyAny>> {
    let init = Identifier::init(Span::from(ident.span), ident.name.to_string());
    Ok(Py::new(py, init)?.into_any())
}

/// Builds either an [`Identifier`] or an [`IndexedIdentifier`] node.
fn build_ident_or_indexed(py: Python<'_>, ident: &ast::IdentOrIndexedIdent) -> PyResult<Py<PyAny>> {
    match ident {
        ast::IdentOrIndexedIdent::Ident(ident) => build_identifier(py, ident),
        ast::IdentOrIndexedIdent::IndexedIdent(indexed) => {
            let name = build_identifier(py, &indexed.ident)?;
            let mut indices = Vec::with_capacity(indexed.indices.len());
            for index in &indexed.indices {
                indices.push(build_index(py, index)?);
            }
            let init = IndexedIdentifier::init(Span::from(indexed.span), name, indices);
            Ok(Py::new(py, init)?.into_any())
        }
    }
}

/// Builds the r-value of an alias, declaration, assignment, or return statement.
fn build_value_expr(py: Python<'_>, value: &ast::ValueExpr) -> PyResult<Py<PyAny>> {
    match value {
        ast::ValueExpr::Expr(expr) => build_expr(py, expr),
        ast::ValueExpr::Concat(concat) => {
            let operands = expr_list(py, &concat.operands)?;
            let init = Concatenation::init(Span::from(concat.span), operands);
            Ok(Py::new(py, init)?.into_any())
        }
        ast::ValueExpr::Measurement(measure) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &measure.operand)?;
            let init = QuantumMeasurement::init(Span::from(measure.span), qubits);
            Ok(Py::new(py, init)?.into_any())
        }
    }
}

/// Builds a [`HardwareQubit`] gate-operand node as an owned `Py<PyAny>`.
fn build_hardware_qubit(py: Python<'_>, hw: &ast::HardwareQubit) -> PyResult<Py<PyAny>> {
    let init = HardwareQubit::init(Span::from(hw.span), hw.name.to_string());
    Ok(Py::new(py, init)?.into_any())
}

// ----------------------------------------------------------------------------
// Child-collection helpers
// ----------------------------------------------------------------------------

fn expr_list(py: Python<'_>, exprs: &[ast::Expr]) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(exprs.len());
    for expr in exprs {
        out.push(build_expr(py, expr)?);
    }
    Ok(out)
}

/// Projects a gate-definition parameter list, keeping recovery gaps visible.
///
/// A missing item becomes an `ErrorExpression` at the span it would have
/// occupied, so a caller can see the hole instead of a silently shorter list.
fn gate_ident_list(py: Python<'_>, items: &[ast::SeqItem<ast::Ident>]) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(items.len());
    for item in items {
        let node = if let Some(ident) = item.item_as_ref() {
            build_identifier(py, ident)?
        } else {
            let span = item.missing_span().unwrap_or_default();
            Py::new(py, ErrorExpression::init(Span::from(span)))?.into_any()
        };
        out.push(node);
    }
    Ok(out)
}

fn stmt_list(py: Python<'_>, stmts: &[ast::Stmt]) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(stmts.len());
    for stmt in stmts {
        out.push(build_stmt(py, stmt)?);
    }
    Ok(out)
}

fn opt_expr(py: Python<'_>, expr: Option<&ast::Expr>) -> PyResult<Option<Py<PyAny>>> {
    match expr {
        Some(expr) => Ok(Some(build_expr(py, expr)?)),
        None => Ok(None),
    }
}

fn build_type_definition(py: Python<'_>, ty: &ast::TypeDef) -> PyResult<Py<PyAny>> {
    match ty {
        ast::TypeDef::Scalar(ty) => build_scalar_type(py, ty),
        ast::TypeDef::Array(ty) => {
            let base_type = build_array_base_type(py, &ty.base_type, ty.span)?;
            let dimensions = expr_list(py, &ty.dimensions)?;
            let init = ArrayType::init(Span::from(ty.span), base_type, dimensions);
            Ok(Py::new(py, init)?.into_any())
        }
        ast::TypeDef::ArrayReference(ty) => build_array_reference_type(py, ty),
    }
}

fn build_extern_parameter_type(py: Python<'_>, ty: &ast::ExternParameter) -> PyResult<Py<PyAny>> {
    match ty {
        ast::ExternParameter::Scalar(ty, _) => build_scalar_type(py, ty),
        ast::ExternParameter::ArrayReference(ty, _) => build_array_reference_type(py, ty),
    }
}

fn build_def_parameter_type(py: Python<'_>, ty: &ast::DefParameterType) -> PyResult<Py<PyAny>> {
    match ty {
        ast::DefParameterType::Qubit(ty) => {
            let size = opt_expr(py, ty.size.as_ref())?;
            let init = QubitType::init(Span::from(ty.span), size);
            Ok(Py::new(py, init)?.into_any())
        }
        ast::DefParameterType::Scalar(ty) => build_scalar_type(py, ty),
        ast::DefParameterType::ArrayReference(ty) => build_array_reference_type(py, ty),
    }
}

fn build_scalar_type(py: Python<'_>, ty: &ast::ScalarType) -> PyResult<Py<PyAny>> {
    let span = Span::from(ty.span);
    let obj: Py<PyAny> = match &ty.kind {
        ast::ScalarTypeKind::Bit(ty) => {
            Py::new(py, BitType::init(span, opt_expr(py, ty.size.as_ref())?))?.into_any()
        }
        ast::ScalarTypeKind::Int(ty) => {
            Py::new(py, IntType::init(span, opt_expr(py, ty.size.as_ref())?))?.into_any()
        }
        ast::ScalarTypeKind::Uint(ty) => {
            Py::new(py, UintType::init(span, opt_expr(py, ty.size.as_ref())?))?.into_any()
        }
        ast::ScalarTypeKind::Float(ty) => {
            Py::new(py, FloatType::init(span, opt_expr(py, ty.size.as_ref())?))?.into_any()
        }
        ast::ScalarTypeKind::Angle(ty) => {
            Py::new(py, AngleType::init(span, opt_expr(py, ty.size.as_ref())?))?.into_any()
        }
        ast::ScalarTypeKind::Complex(ty) => {
            let base_type = match &ty.base_size {
                Some(base) => Some(build_float_type(py, base)?),
                None => None,
            };
            Py::new(py, ComplexType::init(span, base_type))?.into_any()
        }
        ast::ScalarTypeKind::BoolType => Py::new(py, BoolType::init(span))?.into_any(),
        ast::ScalarTypeKind::Duration => Py::new(py, DurationType::init(span))?.into_any(),
        ast::ScalarTypeKind::Stretch => Py::new(py, StretchType::init(span))?.into_any(),
        ast::ScalarTypeKind::Err => Py::new(py, ErrorType::init(span))?.into_any(),
    };
    Ok(obj)
}

fn build_float_type(py: Python<'_>, ty: &ast::FloatType) -> PyResult<Py<PyAny>> {
    let size = opt_expr(py, ty.size.as_ref())?;
    let init = FloatType::init(Span::from(ty.span), size);
    Ok(Py::new(py, init)?.into_any())
}

fn build_array_base_type(
    py: Python<'_>,
    kind: &ast::ArrayBaseTypeKind,
    span: qdk_openqasm::span::Span,
) -> PyResult<Py<PyAny>> {
    let py_span = Span::from(span);
    let obj: Py<PyAny> = match kind {
        ast::ArrayBaseTypeKind::Int(ty) => {
            Py::new(py, IntType::init(py_span, opt_expr(py, ty.size.as_ref())?))?.into_any()
        }
        ast::ArrayBaseTypeKind::Uint(ty) => {
            Py::new(py, UintType::init(py_span, opt_expr(py, ty.size.as_ref())?))?.into_any()
        }
        ast::ArrayBaseTypeKind::Float(ty) => Py::new(
            py,
            FloatType::init(py_span, opt_expr(py, ty.size.as_ref())?),
        )?
        .into_any(),
        ast::ArrayBaseTypeKind::Angle(ty) => Py::new(
            py,
            AngleType::init(py_span, opt_expr(py, ty.size.as_ref())?),
        )?
        .into_any(),
        ast::ArrayBaseTypeKind::Complex(ty) => {
            let base_type = match &ty.base_size {
                Some(base) => Some(build_float_type(py, base)?),
                None => None,
            };
            Py::new(py, ComplexType::init(py_span, base_type))?.into_any()
        }
        ast::ArrayBaseTypeKind::BoolType => Py::new(py, BoolType::init(py_span))?.into_any(),
        ast::ArrayBaseTypeKind::Duration => Py::new(py, DurationType::init(py_span))?.into_any(),
    };
    Ok(obj)
}

fn build_array_reference_type(py: Python<'_>, ty: &ast::ArrayReferenceType) -> PyResult<Py<PyAny>> {
    let obj: Py<PyAny> = match ty {
        ast::ArrayReferenceType::Static(ty) => {
            let base_type = build_array_base_type(py, &ty.base_type, ty.span)?;
            let dimensions = expr_list(py, &ty.dimensions)?;
            let init = StaticArrayReferenceType::init(
                Span::from(ty.span),
                base_type,
                dimensions,
                (&ty.mutability).into(),
            );
            Py::new(py, init)?.into_any()
        }
        ast::ArrayReferenceType::Dyn(ty) => {
            let base_type = build_array_base_type(py, &ty.base_type, ty.span)?;
            let num_dimensions = build_expr(py, &ty.dimensions)?;
            let init = DynArrayReferenceType::init(
                Span::from(ty.span),
                base_type,
                num_dimensions,
                (&ty.mutability).into(),
            );
            Py::new(py, init)?.into_any()
        }
    };
    Ok(obj)
}

fn modifier_list(
    py: Python<'_>,
    modifiers: &[ast::QuantumGateModifier],
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(modifiers.len());
    for modifier in modifiers {
        out.push(build_modifier(py, modifier)?);
    }
    Ok(out)
}

fn build_modifier(py: Python<'_>, modifier: &ast::QuantumGateModifier) -> PyResult<Py<PyAny>> {
    let span = Span::from(modifier.span);
    let name = GateModifierName::from(&modifier.kind);
    let argument = match &modifier.kind {
        ast::GateModifierKind::Inv => None,
        ast::GateModifierKind::Pow(expr) => Some(build_expr(py, expr)?),
        ast::GateModifierKind::Ctrl(expr) | ast::GateModifierKind::NegCtrl(expr) => {
            opt_expr(py, expr.as_ref())?
        }
    };
    QuantumGateModifier::build(py, span, name, argument)
}

fn gate_operand_list(py: Python<'_>, operands: &[ast::GateOperand]) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(operands.len());
    for operand in operands {
        collect_gate_operand(py, &mut out, operand)?;
    }
    Ok(out)
}

fn collect_gate_operand(
    py: Python<'_>,
    out: &mut Vec<Py<PyAny>>,
    operand: &ast::GateOperand,
) -> PyResult<()> {
    match &operand.kind {
        ast::GateOperandKind::IdentOrIndexedIdent(ident) => {
            out.push(build_ident_or_indexed(py, ident)?);
        }
        ast::GateOperandKind::HardwareQubit(hw) => out.push(build_hardware_qubit(py, hw)?),
        ast::GateOperandKind::Err => {}
    }
    Ok(())
}

fn build_index(py: Python<'_>, index: &ast::Index) -> PyResult<Py<PyAny>> {
    match index {
        ast::Index::DiscreteSet(set) => {
            let values = expr_list(py, &set.values)?;
            Ok(Py::new(py, DiscreteSet::init(Span::from(set.span), values))?.into_any())
        }
        ast::Index::IndexList(list) => {
            let mut values = Vec::with_capacity(list.values.len());
            for item in &list.values {
                match item {
                    ast::IndexListItem::RangeDefinition(range) => {
                        values.push(build_range(py, range)?);
                    }
                    ast::IndexListItem::Expr(expr) => values.push(build_expr(py, expr)?),
                    ast::IndexListItem::Err => {}
                }
            }
            Ok(Py::new(py, IndexList::init(Span::from(list.span), values))?.into_any())
        }
    }
}

fn build_range(py: Python<'_>, range: &ast::Range) -> PyResult<Py<PyAny>> {
    let start = opt_expr(py, range.start.as_ref())?;
    let step = opt_expr(py, range.step.as_ref())?;
    let end = opt_expr(py, range.end.as_ref())?;
    Ok(Py::new(
        py,
        RangeDefinition::init(Span::from(range.span), start, step, end),
    )?
    .into_any())
}

fn build_enumerable_set(py: Python<'_>, set: &ast::EnumerableSet) -> PyResult<Py<PyAny>> {
    match set {
        ast::EnumerableSet::DiscreteSet(set) => {
            let values = expr_list(py, &set.values)?;
            Ok(Py::new(py, DiscreteSet::init(Span::from(set.span), values))?.into_any())
        }
        ast::EnumerableSet::Range(range) => build_range(py, range),
        ast::EnumerableSet::Expr(expr) => build_expr(py, expr),
    }
}

// ----------------------------------------------------------------------------
// Literal-value projection
// ----------------------------------------------------------------------------

/// Builds the literal node for a `Lit` expression.
///
/// Each `ast::LiteralKind` variant maps to its own class so callers dispatch on
/// the node type instead of a string tag.
fn build_literal(py: Python<'_>, span: Span, lit: &ast::LiteralKind) -> PyResult<Py<PyAny>> {
    use ast::LiteralKind as Kind;
    let obj: Py<PyAny> = match lit {
        Kind::Array(exprs) => {
            let values = expr_list(py, exprs)?;
            Py::new(py, ArrayLiteral::init(span, values))?.into_any()
        }
        Kind::Bool(value) => Py::new(py, BooleanLiteral::init(span, *value))?.into_any(),
        Kind::Int(value) => {
            Py::new(py, IntegerLiteral::init(span, (*value).into_py_any(py)?))?.into_any()
        }
        Kind::BigInt(value) => {
            let value = bigint_to_py(py, &value.to_str_radix(10))?;
            Py::new(py, IntegerLiteral::init(span, value))?.into_any()
        }
        Kind::Float(value) => Py::new(py, FloatLiteral::init(span, *value))?.into_any(),
        Kind::Imaginary(value) => Py::new(py, ImaginaryLiteral::init(span, *value))?.into_any(),
        Kind::String(value) => {
            Py::new(py, StringLiteral::init(span, value.to_string()))?.into_any()
        }
        Kind::Duration(value, unit) => {
            Py::new(py, DurationLiteral::init(span, *value, unit.into()))?.into_any()
        }
        Kind::Bitstring(value, width) => {
            let value = bigint_to_py(py, &value.to_str_radix(10))?;
            Py::new(py, BitstringLiteral::init(span, value, *width))?.into_any()
        }
    };
    Ok(obj)
}

fn bigint_to_py(py: Python<'_>, decimal: &str) -> PyResult<Py<PyAny>> {
    Ok(py
        .import("builtins")?
        .getattr("int")?
        .call1((decimal,))?
        .unbind())
}
