// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Rich, read-only Python projections of the *syntactic* `OpenQASM` AST.
//!
//! Where [`super::semantic`] projects the resolved semantic tree, this module
//! projects the raw parse tree produced by [`qdk_openqasm::parse_source`]. The
//! syntactic tree carries no resolved type, const-value, or symbol information,
//! so its nodes extend [`Expression`] / [`Statement`] directly (a three-level
//! `QASMNode -> Expression|Statement -> concrete` chain) rather than through the
//! semantic `SemExpr` / `SemStmt` bases.
//!
//! Concrete per-variant leaf classes are generated by the [`qasm_node!`] macro
//! (`@sexpr` / `@sstmt` categories) and expose *named*, typed accessors for
//! their children (for example `BinaryExpression.lhs` / `.rhs` / `.op`) plus a
//! uniform `children()` method for generic traversal. There is intentionally no
//! `kind` discriminant; callers dispatch via `isinstance` and
//! `type(node).__name__`.
//!
//! Class names follow the [`openqasm3` reference AST][openqasm3] wherever an
//! equivalent class exists (for example `BinaryExpression`, `QuantumGate`,
//! `ClassicalDeclaration`, `ForInLoop`, `Box`, `SwitchStatement`). Variants with
//! no `openqasm3` equivalent take a descriptive QDK name (for example
//! `ErrorExpression`, `ErrorStatement`, `ParenExpression`, `CompoundAssignment`).
//!
//! All projections are eagerly materialized into owned, frozen values (scalars
//! plus `Py<PyAny>` references to already-built children), so they are
//! `Send + Sync` and hold no borrow into the Rust parse result.
//!
//! [openqasm3]: https://github.com/openqasm/openqasm/tree/main/source/openqasm
//!
//! ## Syntactic name to variant table
//!
//! The mapping below is the single source of truth for the Python class names
//! and the syntactic AST variants they project. It is kept in sync with
//! `qdk_openqasm::parser::ast`.
//!
//! Statements (`StmtKind` -> class):
//! * `Alias` -> `AliasStatement`
//! * `Assign` -> `ClassicalAssignment`
//! * `AssignOp` -> `CompoundAssignment`
//! * `Barrier` -> `QuantumBarrier`
//! * `Box` -> `Box`
//! * `Break` -> `BreakStatement`
//! * `Block` -> `CompoundStatement`
//! * `Cal` -> `CalibrationStatement`
//! * `CalibrationGrammar` -> `CalibrationGrammarDeclaration`
//! * `ClassicalDecl` -> `ClassicalDeclaration`
//! * `ConstDecl` -> `ConstantDeclaration`
//! * `Continue` -> `ContinueStatement`
//! * `Def` -> `SubroutineDefinition`
//! * `DefCal` -> `CalibrationDefinition`
//! * `Delay` -> `DelayInstruction`
//! * `End` -> `EndStatement`
//! * `ExprStmt` -> `ExpressionStatement`
//! * `ExternDecl` -> `ExternDeclaration`
//! * `For` -> `ForInLoop`
//! * `If` -> `BranchingStatement`
//! * `GateCall` -> `QuantumGate`
//! * `GPhase` -> `QuantumPhase`
//! * `Include` -> `Include`
//! * `IODeclaration` -> `IODeclaration`
//! * `Measure` -> `QuantumMeasurementStatement`
//! * `Pragma` -> `Pragma`
//! * `QuantumGateDefinition` -> `QuantumGateDefinition`
//! * `QuantumDecl` -> `QubitDeclaration`
//! * `Reset` -> `QuantumReset`
//! * `Return` -> `ReturnStatement`
//! * `Switch` -> `SwitchStatement`
//! * `WhileLoop` -> `WhileLoop`
//! * `Err` -> `ErrorStatement`
//!
//! Expressions (`ExprKind` -> class):
//! * `Err` -> `ErrorExpression`
//! * `Ident` -> `Identifier`
//! * `UnaryOp` -> `UnaryExpression`
//! * `BinaryOp` -> `BinaryExpression`
//! * `Lit` -> `LiteralExpression`
//! * `FunctionCall` -> `FunctionCall`
//! * `Cast` -> `Cast`
//! * `IndexExpr` -> `IndexExpression`
//! * `Paren` -> `ParenExpression`
//! * `DurationOf` -> `DurationOf`
//!
//! Auxiliary syntactic nodes with no direct `ExprKind` / `StmtKind` variant:
//! * An indexed identifier (`a[i]` in an l-value position) -> `IndexedIdentifier`
//! * A hardware-qubit gate operand (`$0`) -> `HardwareQubit`
//! * A concatenation r-value (`a ++ b`) -> `Concatenation`
//! * A measurement r-value (`measure q`) -> `QuantumMeasurement`
//! * A gate modifier (`ctrl @`, `pow(2) @`) -> `QuantumGateModifier`

use crate::openqasm::nodes::{Annotation, Expression, QASMNode, Statement};
use crate::openqasm::source::SourceDocument;
use crate::openqasm::span::Span;
use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::PyComplex;
use qdk_openqasm::parser::ast::{self, PathKind, Program as SyntaxProgram};

// ----------------------------------------------------------------------------
// Category bases
// ----------------------------------------------------------------------------

/// Builds the initializer chain `QASMNode -> Expression`.
fn syntax_expr_base(span: Span) -> PyClassInitializer<Expression> {
    PyClassInitializer::from(QASMNode { span }).add_subclass(Expression)
}

/// Builds the initializer chain `QASMNode -> Statement`.
fn syntax_stmt_base(span: Span, annotations: Vec<Py<Annotation>>) -> PyClassInitializer<Statement> {
    PyClassInitializer::from(QASMNode { span }).add_subclass(Statement { annotations })
}

// ----------------------------------------------------------------------------
// Program root
// ----------------------------------------------------------------------------

/// The root of a parsed `OpenQASM` program.
#[pyclass(extends = QASMNode, frozen, module = "qdk._native")]
pub(crate) struct Program {
    statements: Vec<Py<PyAny>>,
    version: Option<String>,
    document: Py<SourceDocument>,
}

impl Program {
    pub(crate) fn source_document(&self, py: Python<'_>) -> Py<SourceDocument> {
        self.document.clone_ref(py)
    }
}

#[pymethods]
impl Program {
    /// The top-level statements of the program, in source order.
    #[getter]
    fn statements(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        self.statements
            .iter()
            .map(|stmt| stmt.clone_ref(py))
            .collect()
    }

    /// The declared `OpenQASM` version, if any (for example `"3.0"`).
    #[getter]
    fn version(&self) -> Option<String> {
        self.version.clone()
    }

    /// The immutable source document for this parse snapshot.
    #[getter]
    fn document(&self, py: Python<'_>) -> Py<SourceDocument> {
        self.document.clone_ref(py)
    }

    /// The program's child nodes: its top-level statements.
    fn children(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        self.statements
            .iter()
            .map(|stmt| stmt.clone_ref(py))
            .collect()
    }

    fn __repr__(&self) -> String {
        format!(
            "Program(statements=[{} items], version={:?})",
            self.statements.len(),
            self.version
        )
    }
}

/// A quantum gate modifier (for example `ctrl @`, `inv @`, or `pow(2) @`).
///
/// This extends [`QASMNode`] directly, mirroring the `openqasm3`
/// `QuantumGateModifier` node, which is neither an expression nor a statement.
#[pyclass(extends = QASMNode, frozen, module = "qdk._native")]
pub(crate) struct QuantumGateModifier {
    /// The modifier keyword: `"inv"`, `"pow"`, `"ctrl"`, or `"negctrl"`.
    #[pyo3(get)]
    modifier: String,
    /// The modifier's argument expression, if any (the exponent for `pow` or the
    /// optional control count for `ctrl` / `negctrl`).
    #[pyo3(get)]
    argument: Option<Py<PyAny>>,
}

#[pymethods]
impl QuantumGateModifier {
    /// The modifier's child nodes: its argument expression, if present.
    fn children(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        match &self.argument {
            Some(argument) => vec![argument.clone_ref(py)],
            None => Vec::new(),
        }
    }

    fn __repr__(&self) -> String {
        format!("QuantumGateModifier(modifier={:?})", self.modifier)
    }
}

impl QuantumGateModifier {
    fn build(
        py: Python<'_>,
        span: Span,
        modifier: String,
        argument: Option<Py<PyAny>>,
    ) -> PyResult<Py<PyAny>> {
        let init = PyClassInitializer::from(QASMNode { span })
            .add_subclass(QuantumGateModifier { modifier, argument });
        Ok(Py::new(py, init)?.into_any())
    }
}

// ----------------------------------------------------------------------------
// Expression leaf nodes
// ----------------------------------------------------------------------------

qasm_node!(@sexpr Identifier {
    name: val String,
});
qasm_node!(@sexpr IndexedIdentifier {
    name: node,
    indices: list,
});
qasm_node!(@sexpr HardwareQubit {
    name: val String,
});
qasm_node!(@sexpr ErrorExpression {});
qasm_node!(@sexpr UnaryExpression {
    op: val String,
    operand: node,
});
qasm_node!(@sexpr BinaryExpression {
    op: val String,
    lhs: node,
    rhs: node,
});
qasm_node!(@sexpr LiteralExpression {
    value: val Option<Py<PyAny>>,
    elements: list,
    kind: val String,
});
qasm_node!(@sexpr FunctionCall {
    name: node,
    args: list,
});
qasm_node!(@sexpr Cast {
    type_name: val String,
    type_expressions: list,
    operand: node,
});
qasm_node!(@sexpr IndexExpression {
    collection: node,
    indices: list,
});
qasm_node!(@sexpr ParenExpression {
    operand: node,
});
qasm_node!(@sexpr DurationOf {
    body: list,
});
qasm_node!(@sexpr Concatenation {
    operands: list,
});
qasm_node!(@sexpr QuantumMeasurement {
    qubits: list,
});
qasm_node!(@saux RangeDefinition {
    start: opt,
    step: opt,
    end: opt,
});
qasm_node!(@saux DiscreteSet {
    values: list,
});
qasm_node!(@saux IndexList {
    values: list,
});
qasm_node!(@saux SwitchCase {
    labels: list,
    body: list,
});
qasm_node!(@saux SubroutineParameter {
    identifier: node,
    type_name: val String,
    type_expressions: list,
});

// ----------------------------------------------------------------------------
// Statement leaf nodes
// ----------------------------------------------------------------------------

qasm_node!(@sstmt QubitDeclaration {
    qubit: node,
    size: opt,
});
qasm_node!(@sstmt AliasStatement {
    target: node,
    exprs: list,
});
qasm_node!(@sstmt ClassicalAssignment {
    lhs: node,
    rhs: node,
});
qasm_node!(@sstmt CompoundAssignment {
    op: val String,
    lhs: node,
    rhs: node,
});
qasm_node!(@sstmt QuantumBarrier {
    qubits: list,
});
qasm_node!(@sstmt Box {
    duration: opt,
    body: list,
});
qasm_node!(@sstmt BreakStatement {});
qasm_node!(@sstmt CompoundStatement {
    statements: list,
});
qasm_node!(@sstmt CalibrationStatement {
    body: val String,
});
qasm_node!(@sstmt CalibrationGrammarDeclaration {
    name: val String,
});
qasm_node!(@sstmt ClassicalDeclaration {
    type_name: val String,
    type_expressions: list,
    identifier: node,
    init_expr: opt,
});
qasm_node!(@sstmt ConstantDeclaration {
    type_name: val String,
    type_expressions: list,
    identifier: node,
    init_expr: node,
});
qasm_node!(@sstmt ContinueStatement {});
qasm_node!(@sstmt SubroutineDefinition {
    name: node,
    params: list,
    return_type_name: val Option<String>,
    return_type_expressions: list,
    body: list,
});
qasm_node!(@sstmt CalibrationDefinition {
    body: val String,
});
qasm_node!(@sstmt DelayInstruction {
    duration: node,
    qubits: list,
});
qasm_node!(@sstmt EndStatement {});
qasm_node!(@sstmt ExpressionStatement {
    expr: node,
});
qasm_node!(@sstmt ExternDeclaration {
    name: node,
    param_type_names: val Vec<String>,
    param_type_expressions: list,
    return_type_name: val Option<String>,
    return_type_expressions: list,
});
qasm_node!(@sstmt ForInLoop {
    type_name: val String,
    type_expressions: list,
    identifier: node,
    iterable: node,
    body: node,
});
qasm_node!(@sstmt BranchingStatement {
    condition: node,
    if_body: node,
    else_body: opt,
});
qasm_node!(@sstmt QuantumGate {
    name: node,
    modifiers: list,
    args: list,
    qubits: list,
    duration: opt,
});
qasm_node!(@sstmt QuantumPhase {
    modifiers: list,
    args: list,
    qubits: list,
    duration: opt,
});
qasm_node!(@sstmt Include {
    filename: val String,
});
qasm_node!(@sstmt IODeclaration {
    io_keyword: val String,
    type_name: val String,
    type_expressions: list,
    identifier: node,
});
qasm_node!(@sstmt QuantumMeasurementStatement {
    qubits: list,
    target: opt,
});
qasm_node!(@sstmt Pragma {
    name: val Option<String>,
    value: val Option<String>,
});
qasm_node!(@sstmt QuantumGateDefinition {
    name: node,
    params: val Vec<String>,
    qubits: val Vec<String>,
    body: list,
});
qasm_node!(@sstmt QuantumReset {
    qubits: list,
});
qasm_node!(@sstmt ReturnStatement {
    value: opt,
});
/// A read-only OpenQASM `SwitchStatement` node.
#[pyclass(extends = Statement, frozen, module = "qdk._native")]
pub(crate) struct SwitchStatement {
    #[pyo3(get)]
    target: Py<PyAny>,
    #[pyo3(get)]
    cases: Vec<Py<PyAny>>,
    default: Option<Vec<Py<PyAny>>>,
}

#[pymethods]
impl SwitchStatement {
    #[getter]
    fn default(&self, py: Python<'_>) -> Option<Vec<Py<PyAny>>> {
        self.default
            .as_ref()
            .map(|body| body.iter().map(|stmt| stmt.clone_ref(py)).collect())
    }

    fn children(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        let default_len = self.default.as_ref().map_or(0, Vec::len);
        let mut children = Vec::with_capacity(1 + self.cases.len() + default_len);
        children.push(self.target.clone_ref(py));
        children.extend(self.cases.iter().map(|case| case.clone_ref(py)));
        if let Some(default) = &self.default {
            children.extend(default.iter().map(|stmt| stmt.clone_ref(py)));
        }
        children
    }
}

impl SwitchStatement {
    fn init(
        span: Span,
        annotations: Vec<Py<Annotation>>,
        target: Py<PyAny>,
        cases: Vec<Py<PyAny>>,
        default: Option<Vec<Py<PyAny>>>,
    ) -> PyClassInitializer<Self> {
        syntax_stmt_base(span, annotations).add_subclass(Self {
            target,
            cases,
            default,
        })
    }
}
qasm_node!(@sstmt WhileLoop {
    condition: node,
    body: node,
});
qasm_node!(@sstmt ErrorStatement {});

// ----------------------------------------------------------------------------
// Registration
// ----------------------------------------------------------------------------

macro_rules! register_syntax_nodes {
    ($m:ident; $($ty:ty),* $(,)?) => {
        $($m.add_class::<$ty>()?;)*
    };
}

/// Registers all syntactic node classes with the native module.
pub(crate) fn register_syntax_nodes(m: &Bound<'_, PyModule>) -> PyResult<()> {
    register_syntax_nodes!(m;
        Program,
        QuantumGateModifier,
        Identifier,
        IndexedIdentifier,
        HardwareQubit,
        ErrorExpression,
        UnaryExpression,
        BinaryExpression,
        LiteralExpression,
        FunctionCall,
        Cast,
        IndexExpression,
        ParenExpression,
        DurationOf,
        Concatenation,
        QuantumMeasurement,
        RangeDefinition,
        DiscreteSet,
        IndexList,
        SwitchCase,
        SubroutineParameter,
        QubitDeclaration,
        AliasStatement,
        ClassicalAssignment,
        CompoundAssignment,
        QuantumBarrier,
        Box,
        BreakStatement,
        CompoundStatement,
        CalibrationStatement,
        CalibrationGrammarDeclaration,
        ClassicalDeclaration,
        ConstantDeclaration,
        ContinueStatement,
        SubroutineDefinition,
        CalibrationDefinition,
        DelayInstruction,
        EndStatement,
        ExpressionStatement,
        ExternDeclaration,
        ForInLoop,
        BranchingStatement,
        QuantumGate,
        QuantumPhase,
        Include,
        IODeclaration,
        QuantumMeasurementStatement,
        Pragma,
        QuantumGateDefinition,
        QuantumReset,
        ReturnStatement,
        SwitchStatement,
        WhileLoop,
        ErrorStatement,
    );
    Ok(())
}

// ----------------------------------------------------------------------------
// Syntax AST -> Python node tree
// ----------------------------------------------------------------------------

/// Builds the Python [`Program`] root from a parsed syntax program.
///
/// When `program` is `None` (for example when the source failed to parse into a
/// tree at all), an empty program is returned so callers still receive a
/// well-formed root alongside the diagnostics.
pub(crate) fn build_program(
    py: Python<'_>,
    program: Option<&SyntaxProgram>,
    document: Py<SourceDocument>,
) -> PyResult<Py<Program>> {
    let (span, statements, version) = match program {
        Some(program) => {
            let mut statements = Vec::with_capacity(program.statements.len());
            for stmt in &program.statements {
                statements.push(build_stmt(py, stmt)?);
            }
            let version = program.version.as_ref().map(ToString::to_string);
            (Span::from(program.span), statements, version)
        }
        None => (Span { lo: 0, hi: 0 }, Vec::new(), None),
    };

    let init = PyClassInitializer::from(QASMNode { span }).add_subclass(Program {
        statements,
        version,
        document,
    });
    Py::new(py, init)
}

#[allow(clippy::too_many_lines)]
fn build_stmt(py: Python<'_>, stmt: &ast::Stmt) -> PyResult<Py<PyAny>> {
    let span = Span::from(stmt.span);
    let annotations = build_annotations(py, &stmt.annotations)?;
    let obj: Py<PyAny> = match stmt.kind.as_ref() {
        ast::StmtKind::Alias(s) => {
            let target = build_ident_or_indexed(py, &s.ident)?;
            let exprs = expr_list(py, &s.exprs)?;
            Py::new(py, AliasStatement::init(span, annotations, target, exprs))?.into_any()
        }
        ast::StmtKind::Assign(s) => {
            let lhs = build_ident_or_indexed(py, &s.lhs)?;
            let rhs = build_value_expr(py, &s.rhs)?;
            Py::new(py, ClassicalAssignment::init(span, annotations, lhs, rhs))?.into_any()
        }
        ast::StmtKind::AssignOp(s) => {
            let lhs = build_ident_or_indexed(py, &s.lhs)?;
            let rhs = build_value_expr(py, &s.rhs)?;
            Py::new(
                py,
                CompoundAssignment::init(span, annotations, s.op.to_string(), lhs, rhs),
            )?
            .into_any()
        }
        ast::StmtKind::Barrier(s) => {
            let qubits = gate_operand_list(py, &s.qubits)?;
            Py::new(py, QuantumBarrier::init(span, annotations, qubits))?.into_any()
        }
        ast::StmtKind::Box(s) => {
            let duration = opt_expr(py, s.duration.as_ref())?;
            let body = stmt_list(py, &s.body)?;
            Py::new(py, Box::init(span, annotations, duration, body))?.into_any()
        }
        ast::StmtKind::Break(_) => Py::new(py, BreakStatement::init(span, annotations))?.into_any(),
        ast::StmtKind::Block(s) => {
            let statements = stmt_list(py, &s.stmts)?;
            Py::new(py, CompoundStatement::init(span, annotations, statements))?.into_any()
        }
        ast::StmtKind::Cal(s) => Py::new(
            py,
            CalibrationStatement::init(span, annotations, s.content.to_string()),
        )?
        .into_any(),
        ast::StmtKind::CalibrationGrammar(s) => Py::new(
            py,
            CalibrationGrammarDeclaration::init(span, annotations, s.name.to_string()),
        )?
        .into_any(),
        ast::StmtKind::ClassicalDecl(s) => {
            let ty = type_definition_parts(py, &s.ty)?;
            let identifier = build_identifier(py, &s.identifier)?;
            let init_expr = match s.init_expr.as_deref() {
                Some(init) => Some(build_value_expr(py, init)?),
                None => None,
            };
            Py::new(
                py,
                ClassicalDeclaration::init(
                    span,
                    annotations,
                    ty.name,
                    ty.expressions,
                    identifier,
                    init_expr,
                ),
            )?
            .into_any()
        }
        ast::StmtKind::ConstDecl(s) => {
            let ty = type_definition_parts(py, &s.ty)?;
            let identifier = build_identifier(py, &s.identifier)?;
            let init_expr = build_value_expr(py, &s.init_expr)?;
            Py::new(
                py,
                ConstantDeclaration::init(
                    span,
                    annotations,
                    ty.name,
                    ty.expressions,
                    identifier,
                    init_expr,
                ),
            )?
            .into_any()
        }
        ast::StmtKind::Continue(_) => {
            Py::new(py, ContinueStatement::init(span, annotations))?.into_any()
        }
        ast::StmtKind::Def(s) => {
            let name = build_identifier(py, &s.name)?;
            let mut params = Vec::with_capacity(s.params.len());
            for param in &s.params {
                let identifier = build_identifier(py, &param.ident)?;
                let (type_name, type_expressions) =
                    def_parameter_type_parts(py, param.ty.as_ref())?;
                params.push(
                    Py::new(
                        py,
                        SubroutineParameter::init(
                            Span::from(param.span),
                            identifier,
                            type_name,
                            type_expressions,
                        ),
                    )?
                    .into_any(),
                );
            }
            let return_ty = s
                .return_type
                .as_ref()
                .map(|ty| scalar_type_parts(py, ty))
                .transpose()?;
            let (return_type_name, return_type_expressions) = return_ty
                .map(|ty| (Some(ty.name), ty.expressions))
                .unwrap_or_default();
            let body = stmt_list(py, &s.body.stmts)?;
            Py::new(
                py,
                SubroutineDefinition::init(
                    span,
                    annotations,
                    name,
                    params,
                    return_type_name,
                    return_type_expressions,
                    body,
                ),
            )?
            .into_any()
        }
        ast::StmtKind::DefCal(s) => Py::new(
            py,
            CalibrationDefinition::init(span, annotations, s.content.to_string()),
        )?
        .into_any(),
        ast::StmtKind::Delay(s) => {
            let duration = build_expr(py, &s.duration)?;
            let qubits = gate_operand_list(py, &s.qubits)?;
            Py::new(
                py,
                DelayInstruction::init(span, annotations, duration, qubits),
            )?
            .into_any()
        }
        ast::StmtKind::End(_) => Py::new(py, EndStatement::init(span, annotations))?.into_any(),
        ast::StmtKind::ExprStmt(s) => {
            let expr = build_expr(py, &s.expr)?;
            Py::new(py, ExpressionStatement::init(span, annotations, expr))?.into_any()
        }
        ast::StmtKind::ExternDecl(s) => {
            let name = build_identifier(py, &s.ident)?;
            let mut param_type_names = Vec::with_capacity(s.params.len());
            let mut param_type_expressions = Vec::new();
            for param in &s.params {
                let ty = extern_parameter_type_parts(py, param)?;
                param_type_names.push(ty.name);
                param_type_expressions.extend(ty.expressions);
            }
            let return_ty = s
                .return_type
                .as_ref()
                .map(|ty| scalar_type_parts(py, ty))
                .transpose()?;
            let (return_type_name, return_type_expressions) = return_ty
                .map(|ty| (Some(ty.name), ty.expressions))
                .unwrap_or_default();
            Py::new(
                py,
                ExternDeclaration::init(
                    span,
                    annotations,
                    name,
                    param_type_names,
                    param_type_expressions,
                    return_type_name,
                    return_type_expressions,
                ),
            )?
            .into_any()
        }
        ast::StmtKind::For(s) => {
            let ty = scalar_type_parts(py, &s.ty)?;
            let identifier = build_identifier(py, &s.ident)?;
            let iterable = build_enumerable_set(py, &s.set_declaration)?;
            let body = build_stmt(py, &s.body)?;
            Py::new(
                py,
                ForInLoop::init(
                    span,
                    annotations,
                    ty.name,
                    ty.expressions,
                    identifier,
                    iterable,
                    body,
                ),
            )?
            .into_any()
        }
        ast::StmtKind::If(s) => {
            let condition = build_expr(py, &s.condition)?;
            let if_body = build_stmt(py, &s.if_body)?;
            let else_body = match &s.else_body {
                Some(else_body) => Some(build_stmt(py, else_body)?),
                None => None,
            };
            Py::new(
                py,
                BranchingStatement::init(span, annotations, condition, if_body, else_body),
            )?
            .into_any()
        }
        ast::StmtKind::GateCall(s) => {
            let name = build_identifier(py, &s.name)?;
            let modifiers = modifier_list(py, &s.modifiers)?;
            let args = expr_list(py, &s.args)?;
            let qubits = gate_operand_list(py, &s.qubits)?;
            let duration = opt_expr(py, s.duration.as_ref())?;
            Py::new(
                py,
                QuantumGate::init(span, annotations, name, modifiers, args, qubits, duration),
            )?
            .into_any()
        }
        ast::StmtKind::GPhase(s) => {
            let modifiers = modifier_list(py, &s.modifiers)?;
            let args = expr_list(py, &s.args)?;
            let qubits = gate_operand_list(py, &s.qubits)?;
            let duration = opt_expr(py, s.duration.as_ref())?;
            Py::new(
                py,
                QuantumPhase::init(span, annotations, modifiers, args, qubits, duration),
            )?
            .into_any()
        }
        ast::StmtKind::Include(s) => {
            Py::new(py, Include::init(span, annotations, s.filename.to_string()))?.into_any()
        }
        ast::StmtKind::IODeclaration(s) => {
            let ty = type_definition_parts(py, &s.ty)?;
            let identifier = build_identifier(py, &s.ident)?;
            Py::new(
                py,
                IODeclaration::init(
                    span,
                    annotations,
                    s.io_identifier.to_string(),
                    ty.name,
                    ty.expressions,
                    identifier,
                ),
            )?
            .into_any()
        }
        ast::StmtKind::Measure(s) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &s.measurement.operand)?;
            let target = match &s.target {
                Some(target) => Some(build_ident_or_indexed(py, target)?),
                None => None,
            };
            Py::new(
                py,
                QuantumMeasurementStatement::init(span, annotations, qubits, target),
            )?
            .into_any()
        }
        ast::StmtKind::Pragma(s) => {
            let name = s.identifier.as_ref().map(PathKind::as_string);
            let value = s.value.as_ref().map(ToString::to_string);
            Py::new(py, Pragma::init(span, annotations, name, value))?.into_any()
        }
        ast::StmtKind::QuantumGateDefinition(s) => {
            let name = build_identifier(py, &s.ident)?;
            let params = s
                .params
                .iter()
                .filter_map(|item| item.item_as_ref().map(|ident| ident.name.to_string()))
                .collect();
            let qubits = s
                .qubits
                .iter()
                .filter_map(|item| item.item_as_ref().map(|ident| ident.name.to_string()))
                .collect();
            let body = stmt_list(py, &s.body.stmts)?;
            Py::new(
                py,
                QuantumGateDefinition::init(span, annotations, name, params, qubits, body),
            )?
            .into_any()
        }
        ast::StmtKind::QuantumDecl(s) => {
            let qubit = build_identifier(py, &s.qubit)?;
            let size = opt_expr(py, s.ty.size.as_ref())?;
            Py::new(py, QubitDeclaration::init(span, annotations, qubit, size))?.into_any()
        }
        ast::StmtKind::Reset(s) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &s.operand)?;
            Py::new(py, QuantumReset::init(span, annotations, qubits))?.into_any()
        }
        ast::StmtKind::Return(s) => {
            let value = match s.expr.as_deref() {
                Some(expr) => Some(build_value_expr(py, expr)?),
                None => None,
            };
            Py::new(py, ReturnStatement::init(span, annotations, value))?.into_any()
        }
        ast::StmtKind::Switch(s) => {
            let target = build_expr(py, &s.target)?;
            let mut cases = Vec::with_capacity(s.cases.len());
            for case in &s.cases {
                let labels = expr_list(py, &case.labels)?;
                let body = stmt_list(py, &case.block.stmts)?;
                cases.push(
                    Py::new(py, SwitchCase::init(Span::from(case.span), labels, body))?.into_any(),
                );
            }
            let default = s
                .default
                .as_ref()
                .map(|block| stmt_list(py, &block.stmts))
                .transpose()?;
            Py::new(
                py,
                SwitchStatement::init(span, annotations, target, cases, default),
            )?
            .into_any()
        }
        ast::StmtKind::WhileLoop(s) => {
            let condition = build_expr(py, &s.while_condition)?;
            let body = build_stmt(py, &s.body)?;
            Py::new(py, WhileLoop::init(span, annotations, condition, body))?.into_any()
        }
        ast::StmtKind::Err => Py::new(py, ErrorStatement::init(span, annotations))?.into_any(),
    };
    Ok(obj)
}

fn build_annotations(
    py: Python<'_>,
    annotations: &[ast::Annotation],
) -> PyResult<Vec<Py<Annotation>>> {
    annotations
        .iter()
        .map(|annotation| {
            Py::new(
                py,
                Annotation::init(
                    Span::from(annotation.span),
                    annotation.identifier.as_string(),
                    annotation.value.as_ref().map(ToString::to_string),
                    annotation.value_span.map(Span::from),
                ),
            )
        })
        .collect()
}

fn build_expr(py: Python<'_>, expr: &ast::Expr) -> PyResult<Py<PyAny>> {
    let span = Span::from(expr.span);
    let obj: Py<PyAny> = match expr.kind.as_ref() {
        ast::ExprKind::Err => Py::new(py, ErrorExpression::init(span))?.into_any(),
        ast::ExprKind::Ident(ident) => build_identifier(py, ident)?,
        ast::ExprKind::UnaryOp(e) => {
            let operand = build_expr(py, &e.expr)?;
            Py::new(py, UnaryExpression::init(span, e.op.to_string(), operand))?.into_any()
        }
        ast::ExprKind::BinaryOp(e) => {
            let lhs = build_expr(py, &e.lhs)?;
            let rhs = build_expr(py, &e.rhs)?;
            Py::new(py, BinaryExpression::init(span, e.op.to_string(), lhs, rhs))?.into_any()
        }
        ast::ExprKind::Lit(lit) => {
            let (value, elements, kind) = literal_parts(py, &lit.kind)?;
            Py::new(py, LiteralExpression::init(span, value, elements, kind))?.into_any()
        }
        ast::ExprKind::FunctionCall(e) => {
            let name = build_identifier(py, &e.name)?;
            let args = expr_list(py, &e.args)?;
            Py::new(py, FunctionCall::init(span, name, args))?.into_any()
        }
        ast::ExprKind::Cast(e) => {
            let ty = type_definition_parts(py, &e.ty)?;
            let operand = build_expr(py, &e.arg)?;
            Py::new(py, Cast::init(span, ty.name, ty.expressions, operand))?.into_any()
        }
        ast::ExprKind::IndexExpr(e) => {
            let collection = build_expr(py, &e.collection)?;
            let indices = vec![build_index(py, &e.index)?];
            Py::new(py, IndexExpression::init(span, collection, indices))?.into_any()
        }
        ast::ExprKind::Paren(inner) => {
            let operand = build_expr(py, inner)?;
            Py::new(py, ParenExpression::init(span, operand))?.into_any()
        }
        ast::ExprKind::DurationOf(d) => {
            let body = stmt_list(py, &d.scope.stmts)?;
            Py::new(py, DurationOf::init(span, body))?.into_any()
        }
    };
    Ok(obj)
}

/// Builds an [`Identifier`] expression node as an owned `Py<PyAny>`.
fn build_identifier(py: Python<'_>, ident: &ast::Ident) -> PyResult<Py<PyAny>> {
    let init = Identifier::init(Span::from(ident.span), ident.name.to_string());
    Ok(Py::new(py, init)?.into_any())
}

/// Builds either an [`Identifier`] or an [`IndexedIdentifier`] node.
fn build_ident_or_indexed(py: Python<'_>, ident: &ast::IdentOrIndexedIdent) -> PyResult<Py<PyAny>> {
    match ident {
        ast::IdentOrIndexedIdent::Ident(ident) => build_identifier(py, ident),
        ast::IdentOrIndexedIdent::IndexedIdent(indexed) => {
            let name = build_identifier(py, &indexed.ident)?;
            let mut indices = Vec::with_capacity(indexed.indices.len());
            for index in &indexed.indices {
                indices.push(build_index(py, index)?);
            }
            let init = IndexedIdentifier::init(Span::from(indexed.span), name, indices);
            Ok(Py::new(py, init)?.into_any())
        }
    }
}

/// Builds the r-value of an alias, declaration, assignment, or return statement.
fn build_value_expr(py: Python<'_>, value: &ast::ValueExpr) -> PyResult<Py<PyAny>> {
    match value {
        ast::ValueExpr::Expr(expr) => build_expr(py, expr),
        ast::ValueExpr::Concat(concat) => {
            let operands = expr_list(py, &concat.operands)?;
            let init = Concatenation::init(Span::from(concat.span), operands);
            Ok(Py::new(py, init)?.into_any())
        }
        ast::ValueExpr::Measurement(measure) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &measure.operand)?;
            let init = QuantumMeasurement::init(Span::from(measure.span), qubits);
            Ok(Py::new(py, init)?.into_any())
        }
    }
}

/// Builds a [`HardwareQubit`] gate-operand node as an owned `Py<PyAny>`.
fn build_hardware_qubit(py: Python<'_>, hw: &ast::HardwareQubit) -> PyResult<Py<PyAny>> {
    let init = HardwareQubit::init(Span::from(hw.span), hw.name.to_string());
    Ok(Py::new(py, init)?.into_any())
}

// ----------------------------------------------------------------------------
// Child-collection helpers
// ----------------------------------------------------------------------------

fn expr_list(py: Python<'_>, exprs: &[ast::Expr]) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(exprs.len());
    for expr in exprs {
        out.push(build_expr(py, expr)?);
    }
    Ok(out)
}

fn stmt_list(py: Python<'_>, stmts: &[ast::Stmt]) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(stmts.len());
    for stmt in stmts {
        out.push(build_stmt(py, stmt)?);
    }
    Ok(out)
}

fn opt_expr(py: Python<'_>, expr: Option<&ast::Expr>) -> PyResult<Option<Py<PyAny>>> {
    match expr {
        Some(expr) => Ok(Some(build_expr(py, expr)?)),
        None => Ok(None),
    }
}

struct TypeProjection {
    name: String,
    expressions: Vec<Py<PyAny>>,
}

fn type_definition_parts(py: Python<'_>, ty: &ast::TypeDef) -> PyResult<TypeProjection> {
    match ty {
        ast::TypeDef::Scalar(ty) => scalar_type_parts(py, ty),
        ast::TypeDef::Array(ty) => {
            let base = array_base_type_parts(py, &ty.base_type)?;
            let dimensions = expression_list_parts(py, &ty.dimensions)?;
            Ok(TypeProjection {
                name: format!("array[{}, {}]", base.name, dimensions.names.join(", ")),
                expressions: base
                    .expressions
                    .into_iter()
                    .chain(dimensions.expressions)
                    .collect(),
            })
        }
        ast::TypeDef::ArrayReference(ty) => array_reference_type_parts(py, ty),
    }
}

fn extern_parameter_type_parts(
    py: Python<'_>,
    ty: &ast::ExternParameter,
) -> PyResult<TypeProjection> {
    match ty {
        ast::ExternParameter::Scalar(ty, _) => scalar_type_parts(py, ty),
        ast::ExternParameter::ArrayReference(ty, _) => array_reference_type_parts(py, ty),
    }
}

fn def_parameter_type_parts(
    py: Python<'_>,
    ty: &ast::DefParameterType,
) -> PyResult<(String, Vec<Py<PyAny>>)> {
    let projection = match ty {
        ast::DefParameterType::Qubit(ty) => size_designator_parts(py, "qubit", ty.size.as_ref())?,
        ast::DefParameterType::Scalar(ty) => scalar_type_parts(py, ty)?,
        ast::DefParameterType::ArrayReference(ty) => array_reference_type_parts(py, ty)?,
    };
    Ok((projection.name, projection.expressions))
}

fn scalar_type_parts(py: Python<'_>, ty: &ast::ScalarType) -> PyResult<TypeProjection> {
    let kind = &ty.kind;
    let (name, size) = match kind {
        ast::ScalarTypeKind::Bit(ty) => ("bit", ty.size.as_ref()),
        ast::ScalarTypeKind::Int(ty) => ("int", ty.size.as_ref()),
        ast::ScalarTypeKind::Uint(ty) => ("uint", ty.size.as_ref()),
        ast::ScalarTypeKind::Float(ty) => ("float", ty.size.as_ref()),
        ast::ScalarTypeKind::Angle(ty) => ("angle", ty.size.as_ref()),
        ast::ScalarTypeKind::Complex(ty) => {
            let Some(base) = &ty.base_size else {
                return Ok(TypeProjection {
                    name: "complex".to_string(),
                    expressions: Vec::new(),
                });
            };
            let base = size_designator_parts(py, "float", base.size.as_ref())?;
            return Ok(TypeProjection {
                name: format!("complex[{}]", base.name),
                expressions: base.expressions,
            });
        }
        ast::ScalarTypeKind::BoolType => ("bool", None),
        ast::ScalarTypeKind::Duration => ("duration", None),
        ast::ScalarTypeKind::Stretch => ("stretch", None),
        ast::ScalarTypeKind::Err => ("error", None),
    };
    size_designator_parts(py, name, size)
}

fn array_base_type_parts(
    py: Python<'_>,
    kind: &ast::ArrayBaseTypeKind,
) -> PyResult<TypeProjection> {
    let name = match kind {
        ast::ArrayBaseTypeKind::Int(ty) => {
            return size_designator_parts(py, "int", ty.size.as_ref());
        }
        ast::ArrayBaseTypeKind::Uint(ty) => {
            return size_designator_parts(py, "uint", ty.size.as_ref());
        }
        ast::ArrayBaseTypeKind::Float(ty) => {
            return size_designator_parts(py, "float", ty.size.as_ref());
        }
        ast::ArrayBaseTypeKind::Complex(ty) => {
            let Some(base) = &ty.base_size else {
                return Ok(TypeProjection {
                    name: "complex".to_string(),
                    expressions: Vec::new(),
                });
            };
            let base = size_designator_parts(py, "float", base.size.as_ref())?;
            return Ok(TypeProjection {
                name: format!("complex[{}]", base.name),
                expressions: base.expressions,
            });
        }
        ast::ArrayBaseTypeKind::Angle(ty) => {
            return size_designator_parts(py, "angle", ty.size.as_ref());
        }
        ast::ArrayBaseTypeKind::BoolType => "bool",
        ast::ArrayBaseTypeKind::Duration => "duration",
    };
    Ok(TypeProjection {
        name: name.to_string(),
        expressions: Vec::new(),
    })
}

fn array_reference_type_parts(
    py: Python<'_>,
    ty: &ast::ArrayReferenceType,
) -> PyResult<TypeProjection> {
    let (mutability, base_type, dimension_exprs, dynamic) = match ty {
        ast::ArrayReferenceType::Static(ty) => (
            access_control_name(&ty.mutability),
            &ty.base_type,
            ty.dimensions.as_ref(),
            false,
        ),
        ast::ArrayReferenceType::Dyn(ty) => (
            access_control_name(&ty.mutability),
            &ty.base_type,
            std::slice::from_ref(&ty.dimensions),
            true,
        ),
    };
    let base = array_base_type_parts(py, base_type)?;
    let dimensions = expression_list_parts(py, dimension_exprs)?;
    let dimension_names = if dynamic {
        format!("#dim = {}", dimensions.names[0])
    } else {
        dimensions.names.join(", ")
    };
    Ok(TypeProjection {
        name: format!("{mutability} array[{}, {dimension_names}]", base.name),
        expressions: base
            .expressions
            .into_iter()
            .chain(dimensions.expressions)
            .collect(),
    })
}

fn size_designator_parts(
    py: Python<'_>,
    name: &str,
    size: Option<&ast::Expr>,
) -> PyResult<TypeProjection> {
    let Some(size) = size else {
        return Ok(TypeProjection {
            name: name.to_string(),
            expressions: Vec::new(),
        });
    };
    Ok(TypeProjection {
        name: format!("{name}[{}]", canonical_expression(size)),
        expressions: vec![build_expr(py, size)?],
    })
}

struct ExpressionListProjection {
    names: Vec<String>,
    expressions: Vec<Py<PyAny>>,
}

fn expression_list_parts(
    py: Python<'_>,
    expressions: &[ast::Expr],
) -> PyResult<ExpressionListProjection> {
    let mut projection = ExpressionListProjection {
        names: Vec::with_capacity(expressions.len()),
        expressions: Vec::with_capacity(expressions.len()),
    };
    for expression in expressions {
        projection.names.push(canonical_expression(expression));
        projection.expressions.push(build_expr(py, expression)?);
    }
    Ok(projection)
}

fn canonical_expression(expression: &ast::Expr) -> String {
    qdk_openqasm::unparse::expression(expression).unwrap_or_else(|_| "error".to_string())
}

fn access_control_name(access: &ast::AccessControl) -> &'static str {
    match access {
        ast::AccessControl::ReadOnly => "readonly",
        ast::AccessControl::Mutable => "mutable",
    }
}

fn modifier_list(
    py: Python<'_>,
    modifiers: &[ast::QuantumGateModifier],
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(modifiers.len());
    for modifier in modifiers {
        out.push(build_modifier(py, modifier)?);
    }
    Ok(out)
}

fn build_modifier(py: Python<'_>, modifier: &ast::QuantumGateModifier) -> PyResult<Py<PyAny>> {
    let span = Span::from(modifier.span);
    let (kind, argument) = match &modifier.kind {
        ast::GateModifierKind::Inv => ("inv".to_string(), None),
        ast::GateModifierKind::Pow(expr) => ("pow".to_string(), Some(build_expr(py, expr)?)),
        ast::GateModifierKind::Ctrl(expr) => ("ctrl".to_string(), opt_expr(py, expr.as_ref())?),
        ast::GateModifierKind::NegCtrl(expr) => {
            ("negctrl".to_string(), opt_expr(py, expr.as_ref())?)
        }
    };
    QuantumGateModifier::build(py, span, kind, argument)
}

fn gate_operand_list(py: Python<'_>, operands: &[ast::GateOperand]) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(operands.len());
    for operand in operands {
        collect_gate_operand(py, &mut out, operand)?;
    }
    Ok(out)
}

fn collect_gate_operand(
    py: Python<'_>,
    out: &mut Vec<Py<PyAny>>,
    operand: &ast::GateOperand,
) -> PyResult<()> {
    match &operand.kind {
        ast::GateOperandKind::IdentOrIndexedIdent(ident) => {
            out.push(build_ident_or_indexed(py, ident)?);
        }
        ast::GateOperandKind::HardwareQubit(hw) => out.push(build_hardware_qubit(py, hw)?),
        ast::GateOperandKind::Err => {}
    }
    Ok(())
}

fn build_index(py: Python<'_>, index: &ast::Index) -> PyResult<Py<PyAny>> {
    match index {
        ast::Index::DiscreteSet(set) => {
            let values = expr_list(py, &set.values)?;
            Ok(Py::new(py, DiscreteSet::init(Span::from(set.span), values))?.into_any())
        }
        ast::Index::IndexList(list) => {
            let mut values = Vec::with_capacity(list.values.len());
            for item in &list.values {
                match item {
                    ast::IndexListItem::RangeDefinition(range) => {
                        values.push(build_range(py, range)?);
                    }
                    ast::IndexListItem::Expr(expr) => values.push(build_expr(py, expr)?),
                    ast::IndexListItem::Err => {}
                }
            }
            Ok(Py::new(py, IndexList::init(Span::from(list.span), values))?.into_any())
        }
    }
}

fn build_range(py: Python<'_>, range: &ast::Range) -> PyResult<Py<PyAny>> {
    let start = opt_expr(py, range.start.as_ref())?;
    let step = opt_expr(py, range.step.as_ref())?;
    let end = opt_expr(py, range.end.as_ref())?;
    Ok(Py::new(
        py,
        RangeDefinition::init(Span::from(range.span), start, step, end),
    )?
    .into_any())
}

fn build_enumerable_set(py: Python<'_>, set: &ast::EnumerableSet) -> PyResult<Py<PyAny>> {
    match set {
        ast::EnumerableSet::DiscreteSet(set) => {
            let values = expr_list(py, &set.values)?;
            Ok(Py::new(py, DiscreteSet::init(Span::from(set.span), values))?.into_any())
        }
        ast::EnumerableSet::Range(range) => build_range(py, range),
        ast::EnumerableSet::Expr(expr) => build_expr(py, expr),
    }
}

// ----------------------------------------------------------------------------
// Literal-value projection
// ----------------------------------------------------------------------------

/// The projected value, element children, and kind tag of a literal expression.
///
/// Scalar literals carry a Python value and no elements; array literals carry no
/// scalar value and expose their element expressions as children. The `kind` tag
/// names the underlying [`ast::LiteralKind`] variant.
type LiteralParts = (Option<Py<PyAny>>, Vec<Py<PyAny>>, String);

fn literal_parts(py: Python<'_>, lit: &ast::LiteralKind) -> PyResult<LiteralParts> {
    use ast::LiteralKind as Kind;
    let parts = match lit {
        Kind::Array(exprs) => {
            let mut elements = Vec::with_capacity(exprs.len());
            for expr in exprs {
                elements.push(build_expr(py, expr)?);
            }
            (None, elements, "Array".to_string())
        }
        Kind::Bool(value) => (
            Some((*value).into_py_any(py)?),
            Vec::new(),
            "Bool".to_string(),
        ),
        Kind::Int(value) => (
            Some((*value).into_py_any(py)?),
            Vec::new(),
            "Int".to_string(),
        ),
        Kind::Float(value) => (
            Some((*value).into_py_any(py)?),
            Vec::new(),
            "Float".to_string(),
        ),
        Kind::Imaginary(value) => (
            Some(PyComplex::from_doubles(py, 0.0, *value).into_any().unbind()),
            Vec::new(),
            "Imaginary".to_string(),
        ),
        Kind::String(value) => (
            Some(value.to_string().into_py_any(py)?),
            Vec::new(),
            "String".to_string(),
        ),
        Kind::Duration(value, unit) => (
            Some(format!("{value}{unit}").into_py_any(py)?),
            Vec::new(),
            "Duration".to_string(),
        ),
        Kind::Bitstring(value, width) => {
            let width = *width as usize;
            (
                Some(format!("{:0>width$}", value.to_str_radix(2)).into_py_any(py)?),
                Vec::new(),
                "Bitstring".to_string(),
            )
        }
        Kind::BigInt(value) => (
            Some(bigint_to_py(py, &value.to_str_radix(10))?),
            Vec::new(),
            "BigInt".to_string(),
        ),
    };
    Ok(parts)
}

fn bigint_to_py(py: Python<'_>, decimal: &str) -> PyResult<Py<PyAny>> {
    Ok(py
        .import("builtins")?
        .getattr("int")?
        .call1((decimal,))?
        .unbind())
}
