// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Rich, read-only Python projections of the semantic `OpenQASM` AST.
//!
//! Where [`super::nodes`] projects the *syntactic* tree, this module projects
//! the *semantic* tree produced by [`qdk_openqasm::analyze_source`]. The
//! semantic tree carries resolved type and const-value information. Each class
//! keeps a `Sem`-prefixed Rust identifier but is presented to Python under a
//! clean, un-prefixed name inside the `qdk._native._semantic` submodule (for
//! example Rust `SemGateCall` -> Python `GateCall`). Isolating the family in a
//! submodule lets it use the un-prefixed names without colliding with the
//! syntax layer's `openqasm3`-parity names in the flat `qdk._native` module.
//!
//! * [`SemExpr`] (Python `Expr`) is the base of every semantic expression. It
//!   extends [`Expression`] (and therefore `QASMNode`) and adds `ty`,
//!   `const_value`, and `symbol` accessors.
//! * [`SemStmt`] (Python `Stmt`) is the base of every semantic statement. It
//!   extends [`Statement`] (and therefore `QASMNode`) and adds an `annotations`
//!   accessor.
//! * [`SemProgram`] (Python `Program`) is the root of a semantic program.
//!
//! Concrete per-variant leaf classes are generated by the [`qasm_node!`] macro
//! and expose *named*, typed accessors for their children (for example
//! `SemBinaryOpExpr.lhs` / `.rhs` / `.op`) plus a uniform `children()` method
//! for generic traversal. There is intentionally no `kind` discriminant;
//! callers dispatch via `isinstance` and `type(node).__name__`.
//!
//! The resolved [`SymbolTable`] is projected as [`SemSymbolTable`], an iterable
//! collection of [`SemSymbol`] views, and types are projected as opaque
//! [`SemType`] values.
//!
//! All projections are eagerly materialized into owned, frozen values (scalars
//! plus `Py<PyAny>` references to already-built children), so they are
//! `Send + Sync` and hold no borrow into the Rust analysis result.
//!
//! ## Semantic name to variant table
//!
//! The mapping below is the single source of truth for the semantic AST
//! variants, their `Sem`-prefixed Rust identifiers, and the clean Python names
//! they present in the `qdk._native._semantic` submodule. It is kept in sync
//! with `qdk_openqasm::semantic::ast`.
//!
//! Statements (`StmtKind` -> Rust ident -> Python name):
//! * `Alias` -> `SemAliasDecl` -> `AliasDecl`
//! * `Assign` -> `SemAssign` -> `Assign`
//! * `Barrier` -> `SemBarrier` -> `Barrier`
//! * `Box` -> `SemBox` -> `Box`
//! * `Block` -> `SemBlock` -> `Block`
//! * `Break` -> `SemBreak` -> `Break`
//! * `Calibration` -> `SemCalibration` -> `Calibration`
//! * `CalibrationGrammar` -> `SemCalibrationGrammar` -> `CalibrationGrammar`
//! * `ClassicalDecl` -> `SemClassicalDecl` -> `ClassicalDecl`
//! * `Continue` -> `SemContinue` -> `Continue`
//! * `Def` -> `SemDef` -> `Def`
//! * `DefCal` -> `SemDefCal` -> `DefCal`
//! * `Delay` -> `SemDelay` -> `Delay`
//! * `End` -> `SemEnd` -> `End`
//! * `ExprStmt` -> `SemExprStmt` -> `ExprStmt`
//! * `ExternDecl` -> `SemExternDecl` -> `ExternDecl`
//! * `For` -> `SemForLoop` -> `ForLoop`
//! * `GateCall` -> `SemGateCall` -> `GateCall`
//! * `If` -> `SemIfStmt` -> `IfStmt`
//! * `Include` -> `SemInclude` -> `Include`
//! * `IndexedAssign` -> `SemIndexedAssign` -> `IndexedAssign`
//! * `InputDeclaration` -> `SemInputDeclaration` -> `InputDeclaration`
//! * `OutputDeclaration` -> `SemOutputDeclaration` -> `OutputDeclaration`
//! * `MeasureArrow` -> `SemMeasureArrow` -> `MeasureArrow`
//! * `Pragma` -> `SemPragma` -> `Pragma`
//! * `QuantumGateDefinition` -> `SemGateDefinition` -> `GateDefinition`
//! * `QubitDecl` -> `SemQubitDecl` -> `QubitDecl`
//! * `QubitArrayDecl` -> `SemQubitArrayDecl` -> `QubitArrayDecl`
//! * `Reset` -> `SemReset` -> `Reset`
//! * `Return` -> `SemReturn` -> `Return`
//! * `Switch` -> `SemSwitch` -> `Switch`
//! * `WhileLoop` -> `SemWhileLoop` -> `WhileLoop`
//! * `Err` -> `SemErrStmt` -> `ErrStmt`
//!
//! Expressions (`ExprKind` -> Rust ident -> Python name):
//! * `Err` -> `SemErrExpr` -> `ErrExpr`
//! * `ResolvedIdent` -> `SemResolvedIdent` -> `ResolvedIdent`
//! * `CapturedResolvedIdent` -> `SemCapturedResolvedIdent` -> `CapturedResolvedIdent`
//! * `UnaryOp` -> `SemUnaryOpExpr` -> `UnaryOpExpr`
//! * `BinaryOp` -> `SemBinaryOpExpr` -> `BinaryOpExpr`
//! * `Lit` -> `SemLiteral` -> `Literal`
//! * `ResolvedFunctionCall` -> `SemFunctionCall` -> `FunctionCall`
//! * `BuiltinFunctionCall` -> `SemBuiltinFunctionCall` -> `BuiltinFunctionCall`
//! * `Cast` -> `SemCast` -> `Cast`
//! * `IndexedExpr` -> `SemIndexedExpr` -> `IndexedExpr`
//! * `Paren` -> `SemParen` -> `Paren`
//! * `Measure` -> `SemMeasure` -> `Measure`
//! * `RuntimeSizeof` -> `SemRuntimeSizeof` -> `RuntimeSizeof`
//! * `EvaluatedDurationof` -> `SemEvaluatedDurationof` -> `EvaluatedDurationof`
//! * `Concat` -> `SemConcat` -> `Concat`
//!
//! The shared category bases and projections are `SemExpr` -> `Expr`,
//! `SemStmt` -> `Stmt`, `SemProgram` -> `Program`, `SemType` -> `Type`,
//! `SemSymbol` -> `Symbol`, and `SemSymbolTable` -> `SymbolTable`.
//!
//! Gate operands of the hardware-qubit form are projected as
//! [`SemHardwareQubit`] (Python `HardwareQubit`) so that no operand is silently
//! dropped.

use crate::qasm_ast::nodes::{Expression, QASMNode, Statement};
use crate::qasm_ast::span::Span;
use pyo3::IntoPyObjectExt;
use pyo3::prelude::*;
use pyo3::types::{PyComplex, PyList};
use qdk_openqasm::parser::ast::PathKind;
use qdk_openqasm::semantic::ast::{self as sem, ExprKind, LiteralKind, StmtKind};
use qdk_openqasm::semantic::symbols::{Symbol, SymbolId, SymbolTable};
use qdk_openqasm::semantic::types::Type as CoreType;

// ----------------------------------------------------------------------------
// Type / Symbol / SymbolTable projections
// ----------------------------------------------------------------------------

/// An opaque, read-only view of a resolved semantic type.
///
/// The `name` is the type's textual rendering (for example `"int[32]"` or
/// `"qubit"`), `is_const` reflects whether the type is compile-time constant,
/// and `width` is the type's bit width when it has one.
#[pyclass(name = "Type", module = "qdk._native._semantic", frozen)]
pub(crate) struct SemType {
    #[pyo3(get)]
    name: String,
    #[pyo3(get)]
    is_const: bool,
    #[pyo3(get)]
    width: Option<u32>,
}

impl SemType {
    fn from_core(py: Python<'_>, ty: &CoreType) -> PyResult<Py<SemType>> {
        Py::new(
            py,
            SemType {
                name: ty.to_string(),
                is_const: ty.is_const(),
                width: ty.width(),
            },
        )
    }
}

#[pymethods]
impl SemType {
    fn __str__(&self) -> String {
        self.name.clone()
    }

    fn __repr__(&self) -> String {
        format!("Type({:?}, is_const={})", self.name, self.is_const)
    }
}

/// A read-only view of a resolved symbol.
#[pyclass(name = "Symbol", module = "qdk._native._semantic", frozen)]
pub(crate) struct SemSymbol {
    /// The symbol's unique id within the [`SemSymbolTable`].
    #[pyo3(get)]
    id: u32,
    /// The symbol's name.
    #[pyo3(get)]
    name: String,
    /// The span where the symbol is declared.
    #[pyo3(get)]
    span: Span,
    /// The symbol's resolved type.
    #[pyo3(get)]
    ty: Py<SemType>,
    /// The symbol's I/O kind (`"Default"`, `"Input"`, or `"Output"`).
    #[pyo3(get)]
    io_kind: String,
    /// The symbol's const-evaluated value, if it is a constant.
    #[pyo3(get)]
    const_value: Option<Py<PyAny>>,
}

#[pymethods]
impl SemSymbol {
    fn __repr__(&self) -> String {
        format!("Symbol(id={}, name={:?})", self.id, self.name)
    }
}

/// An iterable, read-only projection of the resolved symbol table.
#[pyclass(name = "SymbolTable", module = "qdk._native._semantic", frozen)]
pub(crate) struct SemSymbolTable {
    symbols: Vec<Py<SemSymbol>>,
}

#[pymethods]
impl SemSymbolTable {
    /// The number of symbols in the table.
    fn __len__(&self) -> usize {
        self.symbols.len()
    }

    /// Iterates over the [`SemSymbol`] views in the table.
    fn __iter__(&self, py: Python<'_>) -> PyResult<Py<PyAny>> {
        let list = PyList::new(py, self.symbols.iter().map(|symbol| symbol.clone_ref(py)))?;
        Ok(list.as_any().try_iter()?.into_any().unbind())
    }

    /// Returns the symbol with the given id, or `None`.
    fn get(&self, py: Python<'_>, id: u32) -> Option<Py<SemSymbol>> {
        self.symbols
            .iter()
            .find(|symbol| symbol.borrow(py).id == id)
            .map(|symbol| symbol.clone_ref(py))
    }

    /// Returns the first symbol with the given name, or `None`.
    fn lookup(&self, py: Python<'_>, name: &str) -> Option<Py<SemSymbol>> {
        self.symbols
            .iter()
            .find(|symbol| symbol.borrow(py).name == name)
            .map(|symbol| symbol.clone_ref(py))
    }

    /// All [`SemSymbol`] views in the table, in id order.
    fn symbols(&self, py: Python<'_>) -> Vec<Py<SemSymbol>> {
        self.symbols
            .iter()
            .map(|symbol| symbol.clone_ref(py))
            .collect()
    }

    fn __repr__(&self) -> String {
        format!("SymbolTable([{} symbols])", self.symbols.len())
    }
}

fn build_sem_symbol(py: Python<'_>, id: u32, symbol: &Symbol) -> PyResult<Py<SemSymbol>> {
    Py::new(
        py,
        SemSymbol {
            id,
            name: symbol.name.clone(),
            span: symbol.span.into(),
            ty: SemType::from_core(py, &symbol.ty)?,
            io_kind: symbol.io_kind.to_string(),
            const_value: literal_value(py, symbol.get_const_value().as_ref())?,
        },
    )
}

/// Builds the iterable [`SemSymbolTable`] projection from the resolved table.
///
/// Symbol ids are assigned sequentially as symbols are inserted, and the
/// underlying storage never leaves gaps, so a symbol's insertion index equals
/// its id.
pub(crate) fn build_symbol_table(
    py: Python<'_>,
    symbols: &SymbolTable,
) -> PyResult<Py<SemSymbolTable>> {
    let mut entries = Vec::new();
    for (index, symbol) in symbols.symbols().enumerate() {
        let id = u32::try_from(index).expect("symbol id should fit into u32");
        entries.push(build_sem_symbol(py, id, symbol.as_ref())?);
    }
    Py::new(py, SemSymbolTable { symbols: entries })
}

fn build_symbol(py: Python<'_>, symbols: &SymbolTable, id: SymbolId) -> PyResult<Py<SemSymbol>> {
    build_sem_symbol(py, id.into(), symbols[id].as_ref())
}

fn symbol_name(symbols: &SymbolTable, id: SymbolId) -> Option<String> {
    Some(symbols[id].name.clone())
}

// ----------------------------------------------------------------------------
// Category bases
// ----------------------------------------------------------------------------

/// The abstract base of every semantic expression node.
///
/// This class has no Python constructor; it exists for `isinstance` dispatch and
/// to carry the resolved `ty`, `const_value`, and (for resolved identifiers)
/// `symbol` shared by all semantic expressions.
#[pyclass(extends = Expression, subclass, frozen, name = "Expr", module = "qdk._native._semantic")]
pub(crate) struct SemExpr {
    /// The resolved type of the expression.
    #[pyo3(get)]
    ty: Py<SemType>,
    /// The const-evaluated value of the expression, if any.
    #[pyo3(get)]
    const_value: Option<Py<PyAny>>,
    /// The resolved symbol for identifier expressions, if any.
    #[pyo3(get)]
    symbol: Option<Py<SemSymbol>>,
}

/// The abstract base of every semantic statement node.
///
/// This class has no Python constructor; it exists for `isinstance` dispatch and
/// to carry the `annotations` shared by all semantic statements.
#[pyclass(extends = Statement, subclass, frozen, name = "Stmt", module = "qdk._native._semantic")]
pub(crate) struct SemStmt {
    /// The statement's annotation identifiers, in source order.
    #[pyo3(get)]
    annotations: Vec<String>,
}

/// Builds the initializer chain `QASMNode -> Expression -> SemExpr`.
fn sem_expr_base(
    span: Span,
    ty: Py<SemType>,
    const_value: Option<Py<PyAny>>,
    symbol: Option<Py<SemSymbol>>,
) -> PyClassInitializer<SemExpr> {
    PyClassInitializer::from(QASMNode { span })
        .add_subclass(Expression)
        .add_subclass(SemExpr {
            ty,
            const_value,
            symbol,
        })
}

/// Builds the initializer chain `QASMNode -> Statement -> SemStmt`.
fn sem_stmt_base(span: Span, annotations: Vec<String>) -> PyClassInitializer<SemStmt> {
    PyClassInitializer::from(QASMNode { span })
        .add_subclass(Statement)
        .add_subclass(SemStmt { annotations })
}

// ----------------------------------------------------------------------------
// Program root
// ----------------------------------------------------------------------------

/// The root of a semantic `OpenQASM` program.
#[pyclass(extends = QASMNode, frozen, name = "Program", module = "qdk._native._semantic")]
pub(crate) struct SemProgram {
    /// The declared `OpenQASM` version, if any (for example `"3.0"`).
    #[pyo3(get)]
    version: Option<String>,
    /// The program's top-level pragmas, in source order.
    #[pyo3(get)]
    pragmas: Vec<Py<PyAny>>,
    /// The program's top-level statements, in source order.
    #[pyo3(get)]
    statements: Vec<Py<PyAny>>,
}

#[pymethods]
impl SemProgram {
    /// The program's child nodes: pragmas followed by statements.
    fn children(&self, py: Python<'_>) -> Vec<Py<PyAny>> {
        let mut out = Vec::with_capacity(self.pragmas.len() + self.statements.len());
        out.extend(self.pragmas.iter().map(|node| node.clone_ref(py)));
        out.extend(self.statements.iter().map(|node| node.clone_ref(py)));
        out
    }

    fn __repr__(&self) -> String {
        format!("Program(statements=[{} items])", self.statements.len())
    }
}

/// A hardware-qubit gate operand (for example `$0`).
///
/// This extends [`Expression`] rather than [`SemExpr`] because a hardware qubit
/// carries no resolved type or const value; it is a physical qubit reference.
///
/// The Rust identifier stays `SemHardwareQubit`, but the class is presented to
/// Python as `HardwareQubit` in the `qdk._native._semantic` submodule so the
/// semantic family can use clean, un-prefixed names without colliding with the
/// syntax layer in `qdk._native`.
#[pyclass(
    extends = Expression,
    frozen,
    name = "HardwareQubit",
    module = "qdk._native._semantic"
)]
pub(crate) struct SemHardwareQubit {
    /// The hardware qubit's identifier text (for example `"$0"`).
    #[pyo3(get)]
    name: String,
}

#[pymethods]
impl SemHardwareQubit {
    #[allow(clippy::unused_self)]
    fn children(&self) -> Vec<Py<PyAny>> {
        Vec::new()
    }

    fn __repr__(&self) -> String {
        format!("HardwareQubit(name={:?})", self.name)
    }
}

// ----------------------------------------------------------------------------
// Expression leaf nodes
// ----------------------------------------------------------------------------

qasm_node!(@expr SemErrExpr = "ErrExpr" {});
qasm_node!(@expr SemResolvedIdent = "ResolvedIdent" {
    name: val Option<String>,
    symbol_id: val u32,
});
qasm_node!(@expr SemCapturedResolvedIdent = "CapturedResolvedIdent" {
    name: val Option<String>,
    symbol_id: val u32,
});
qasm_node!(@expr SemUnaryOpExpr = "UnaryOpExpr" {
    op: val String,
    operand: node,
});
qasm_node!(@expr SemBinaryOpExpr = "BinaryOpExpr" {
    op: val String,
    lhs: node,
    rhs: node,
});
qasm_node!(@expr SemLiteral = "Literal" {
    value: val Option<Py<PyAny>>,
    elements: list,
});
qasm_node!(@expr SemFunctionCall = "FunctionCall" {
    name: val Option<String>,
    callee_id: val u32,
    args: list,
});
qasm_node!(@expr SemBuiltinFunctionCall = "BuiltinFunctionCall" {
    name: val String,
    args: list,
});
qasm_node!(@expr SemCast = "Cast" {
    operand: node,
    ty_exprs: list,
    kind: val String,
});
qasm_node!(@expr SemIndexedExpr = "IndexedExpr" {
    collection: node,
    indices: list,
});
qasm_node!(@expr SemParen = "Paren" {
    operand: node,
});
qasm_node!(@expr SemMeasure = "Measure" {
    qubits: list,
});
qasm_node!(@expr SemRuntimeSizeof = "RuntimeSizeof" {
    array: node,
    dimension: node,
    array_rank: val u32,
});
qasm_node!(@expr SemEvaluatedDurationof = "EvaluatedDurationof" {
    body: list,
});
qasm_node!(@expr SemConcat = "Concat" {
    operands: list,
});

// ----------------------------------------------------------------------------
// Statement leaf nodes
// ----------------------------------------------------------------------------

qasm_node!(@stmt SemAliasDecl = "AliasDecl" {
    name: val Option<String>,
    exprs: list,
});
qasm_node!(@stmt SemAssign = "Assign" {
    lhs: node,
    rhs: node,
});
qasm_node!(@stmt SemBarrier = "Barrier" {
    qubits: list,
});
qasm_node!(@stmt SemBox = "Box" {
    duration: opt,
    body: list,
});
qasm_node!(@stmt SemBlock = "Block" {
    statements: list,
});
qasm_node!(@stmt SemBreak = "Break" {});
qasm_node!(@stmt SemCalibration = "Calibration" {
    content: val String,
});
qasm_node!(@stmt SemCalibrationGrammar = "CalibrationGrammar" {
    name: val String,
});
qasm_node!(@stmt SemClassicalDecl = "ClassicalDecl" {
    name: val Option<String>,
    ty_exprs: list,
    init_expr: node,
});
qasm_node!(@stmt SemContinue = "Continue" {});
qasm_node!(@stmt SemDef = "Def" {
    name: val Option<String>,
    param_types: list,
    return_types: list,
    body: list,
});
qasm_node!(@stmt SemDefCal = "DefCal" {
    content: val String,
});
qasm_node!(@stmt SemDelay = "Delay" {
    duration: node,
    qubits: list,
});
qasm_node!(@stmt SemEnd = "End" {});
qasm_node!(@stmt SemExprStmt = "ExprStmt" {
    expr: node,
});
qasm_node!(@stmt SemExternDecl = "ExternDecl" {
    name: val Option<String>,
    ty_exprs: list,
    return_types: list,
});
qasm_node!(@stmt SemForLoop = "ForLoop" {
    name: val Option<String>,
    ty_exprs: list,
    iterable: list,
    body: node,
});
qasm_node!(@stmt SemGateCall = "GateCall" {
    name: val Option<String>,
    modifiers: list,
    args: list,
    qubits: list,
    duration: opt,
});
qasm_node!(@stmt SemIfStmt = "IfStmt" {
    condition: node,
    then_block: node,
    else_block: opt,
});
qasm_node!(@stmt SemInclude = "Include" {
    filename: val String,
});
qasm_node!(@stmt SemIndexedAssign = "IndexedAssign" {
    lhs: node,
    indices: list,
    rhs: node,
});
qasm_node!(@stmt SemInputDeclaration = "InputDeclaration" {
    name: val Option<String>,
    ty_exprs: list,
});
qasm_node!(@stmt SemOutputDeclaration = "OutputDeclaration" {
    name: val Option<String>,
    ty_exprs: list,
    init_expr: node,
});
qasm_node!(@stmt SemMeasureArrow = "MeasureArrow" {
    qubits: list,
    target: opt,
});
qasm_node!(@stmt SemPragma = "Pragma" {
    name: val Option<String>,
    value: val Option<String>,
});
qasm_node!(@stmt SemGateDefinition = "GateDefinition" {
    name: val Option<String>,
    params: val Vec<String>,
    qubits: val Vec<String>,
    body: list,
});
qasm_node!(@stmt SemQubitDecl = "QubitDecl" {
    name: val Option<String>,
});
qasm_node!(@stmt SemQubitArrayDecl = "QubitArrayDecl" {
    name: val Option<String>,
    size: node,
});
qasm_node!(@stmt SemReset = "Reset" {
    qubits: list,
});
qasm_node!(@stmt SemReturn = "Return" {
    value: opt,
});
qasm_node!(@stmt SemSwitch = "Switch" {
    target: node,
    labels: list,
    body: list,
    default: list,
});
qasm_node!(@stmt SemWhileLoop = "WhileLoop" {
    condition: node,
    body: node,
});
qasm_node!(@stmt SemErrStmt = "ErrStmt" {});

// ----------------------------------------------------------------------------
// Registration
// ----------------------------------------------------------------------------

macro_rules! register_semantic_nodes {
    ($m:ident; $($ty:ty),* $(,)?) => {
        $($m.add_class::<$ty>()?;)*
    };
}

/// Registers all semantic node classes with the given module.
///
/// The classes are registered into the `qdk._native._semantic` submodule (not
/// the flat `qdk._native` module), so their clean, un-prefixed Python names do
/// not collide with the syntax layer.
pub(crate) fn register_semantic_nodes(m: &Bound<'_, PyModule>) -> PyResult<()> {
    register_semantic_nodes!(m;
        SemType,
        SemSymbol,
        SemSymbolTable,
        SemExpr,
        SemStmt,
        SemProgram,
        SemHardwareQubit,
        SemErrExpr,
        SemResolvedIdent,
        SemCapturedResolvedIdent,
        SemUnaryOpExpr,
        SemBinaryOpExpr,
        SemLiteral,
        SemFunctionCall,
        SemBuiltinFunctionCall,
        SemCast,
        SemIndexedExpr,
        SemParen,
        SemMeasure,
        SemRuntimeSizeof,
        SemEvaluatedDurationof,
        SemConcat,
        SemAliasDecl,
        SemAssign,
        SemBarrier,
        SemBox,
        SemBlock,
        SemBreak,
        SemCalibration,
        SemCalibrationGrammar,
        SemClassicalDecl,
        SemContinue,
        SemDef,
        SemDefCal,
        SemDelay,
        SemEnd,
        SemExprStmt,
        SemExternDecl,
        SemForLoop,
        SemGateCall,
        SemIfStmt,
        SemInclude,
        SemIndexedAssign,
        SemInputDeclaration,
        SemOutputDeclaration,
        SemMeasureArrow,
        SemPragma,
        SemGateDefinition,
        SemQubitDecl,
        SemQubitArrayDecl,
        SemReset,
        SemReturn,
        SemSwitch,
        SemWhileLoop,
        SemErrStmt,
    );
    Ok(())
}

// ----------------------------------------------------------------------------
// Semantic AST -> Python node tree
// ----------------------------------------------------------------------------

/// Builds the semantic [`SemProgram`] root from an analyzed program.
pub(crate) fn build_program(
    py: Python<'_>,
    program: &sem::Program,
    symbols: &SymbolTable,
) -> PyResult<Py<SemProgram>> {
    let mut statements = Vec::with_capacity(program.statements.len());
    for stmt in &program.statements {
        statements.push(build_stmt(py, stmt, symbols)?);
    }
    let mut pragmas = Vec::with_capacity(program.pragmas.len());
    for pragma in &program.pragmas {
        pragmas.push(build_pragma(py, pragma)?);
    }
    let version = program.version.map(|version| version.to_string());
    let init = PyClassInitializer::from(QASMNode {
        span: Span { lo: 0, hi: 0 },
    })
    .add_subclass(SemProgram {
        version,
        pragmas,
        statements,
    });
    Py::new(py, init)
}

fn build_pragma(py: Python<'_>, pragma: &sem::Pragma) -> PyResult<Py<PyAny>> {
    let name = pragma.identifier.as_ref().map(PathKind::as_string);
    let value = pragma.value.as_ref().map(ToString::to_string);
    let init = SemPragma::init(Span::from(pragma.span), Vec::new(), name, value);
    Ok(Py::new(py, init)?.into_any())
}

#[allow(clippy::too_many_lines)]
fn build_stmt(py: Python<'_>, stmt: &sem::Stmt, symbols: &SymbolTable) -> PyResult<Py<PyAny>> {
    let span = Span::from(stmt.span);
    let annotations: Vec<String> = stmt
        .annotations
        .iter()
        .map(|annotation| annotation.identifier.as_string())
        .collect();

    let obj: Py<PyAny> = match stmt.kind.as_ref() {
        StmtKind::Alias(s) => {
            let exprs = expr_list(py, &s.exprs, symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(py, SemAliasDecl::init(span, annotations, name, exprs))?.into_any()
        }
        StmtKind::Assign(s) => {
            let lhs = build_expr(py, &s.lhs, symbols)?;
            let rhs = build_expr(py, &s.rhs, symbols)?;
            Py::new(py, SemAssign::init(span, annotations, lhs, rhs))?.into_any()
        }
        StmtKind::Barrier(s) => {
            let qubits = gate_operand_list(py, &s.qubits, symbols)?;
            Py::new(py, SemBarrier::init(span, annotations, qubits))?.into_any()
        }
        StmtKind::Box(s) => {
            let duration = build_opt_expr(py, s.duration.as_deref(), symbols)?;
            let body = stmt_list(py, &s.body, symbols)?;
            Py::new(py, SemBox::init(span, annotations, duration, body))?.into_any()
        }
        StmtKind::Block(s) => {
            let statements = stmt_list(py, &s.stmts, symbols)?;
            Py::new(py, SemBlock::init(span, annotations, statements))?.into_any()
        }
        StmtKind::Break(_) => Py::new(py, SemBreak::init(span, annotations))?.into_any(),
        StmtKind::Calibration(s) => Py::new(
            py,
            SemCalibration::init(span, annotations, s.content.to_string()),
        )?
        .into_any(),
        StmtKind::CalibrationGrammar(s) => Py::new(
            py,
            SemCalibrationGrammar::init(span, annotations, s.name.to_string()),
        )?
        .into_any(),
        StmtKind::ClassicalDecl(s) => {
            let ty_exprs = expr_list(py, &s.ty_exprs, symbols)?;
            let init_expr = build_expr(py, &s.init_expr, symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(
                py,
                SemClassicalDecl::init(span, annotations, name, ty_exprs, init_expr),
            )?
            .into_any()
        }
        StmtKind::Continue(_) => Py::new(py, SemContinue::init(span, annotations))?.into_any(),
        StmtKind::Def(s) => {
            let mut param_types = Vec::new();
            for param in &s.params {
                for ty_expr in &param.ty_exprs {
                    param_types.push(build_expr(py, ty_expr, symbols)?);
                }
            }
            let return_types = expr_list(py, &s.return_ty_exprs, symbols)?;
            let body = stmt_list(py, &s.body.stmts, symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(
                py,
                SemDef::init(span, annotations, name, param_types, return_types, body),
            )?
            .into_any()
        }
        StmtKind::DefCal(s) => Py::new(
            py,
            SemDefCal::init(span, annotations, s.content.to_string()),
        )?
        .into_any(),
        StmtKind::Delay(s) => {
            let duration = build_expr(py, &s.duration, symbols)?;
            let qubits = gate_operand_list(py, &s.qubits, symbols)?;
            Py::new(py, SemDelay::init(span, annotations, duration, qubits))?.into_any()
        }
        StmtKind::End(_) => Py::new(py, SemEnd::init(span, annotations))?.into_any(),
        StmtKind::ExprStmt(s) => {
            let expr = build_expr(py, &s.expr, symbols)?;
            Py::new(py, SemExprStmt::init(span, annotations, expr))?.into_any()
        }
        StmtKind::ExternDecl(s) => {
            let ty_exprs = expr_list(py, &s.ty_exprs, symbols)?;
            let return_types = expr_list(py, &s.return_ty_exprs, symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(
                py,
                SemExternDecl::init(span, annotations, name, ty_exprs, return_types),
            )?
            .into_any()
        }
        StmtKind::For(s) => {
            let ty_exprs = expr_list(py, &s.ty_exprs, symbols)?;
            let mut iterable = Vec::new();
            collect_enumerable_set(py, &mut iterable, &s.set_declaration, symbols)?;
            let body = build_stmt(py, &s.body, symbols)?;
            let name = symbol_name(symbols, s.loop_variable);
            Py::new(
                py,
                SemForLoop::init(span, annotations, name, ty_exprs, iterable, body),
            )?
            .into_any()
        }
        StmtKind::GateCall(s) => {
            let mut modifiers = Vec::new();
            for modifier in &s.modifiers {
                collect_modifier(py, &mut modifiers, modifier, symbols)?;
            }
            let args = expr_list(py, &s.args, symbols)?;
            let qubits = gate_operand_list(py, &s.qubits, symbols)?;
            let duration = build_opt_expr(py, s.duration.as_deref(), symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(
                py,
                SemGateCall::init(span, annotations, name, modifiers, args, qubits, duration),
            )?
            .into_any()
        }
        StmtKind::If(s) => {
            let condition = build_expr(py, &s.condition, symbols)?;
            let then_block = build_stmt(py, &s.if_body, symbols)?;
            let else_block = match &s.else_body {
                Some(else_body) => Some(build_stmt(py, else_body, symbols)?),
                None => None,
            };
            Py::new(
                py,
                SemIfStmt::init(span, annotations, condition, then_block, else_block),
            )?
            .into_any()
        }
        StmtKind::Include(s) => Py::new(
            py,
            SemInclude::init(span, annotations, s.filename.to_string()),
        )?
        .into_any(),
        StmtKind::IndexedAssign(s) => {
            let lhs = build_expr(py, &s.lhs, symbols)?;
            let mut indices = Vec::new();
            for index in &s.indices {
                collect_index(py, &mut indices, index, symbols)?;
            }
            let rhs = build_expr(py, &s.rhs, symbols)?;
            Py::new(
                py,
                SemIndexedAssign::init(span, annotations, lhs, indices, rhs),
            )?
            .into_any()
        }
        StmtKind::InputDeclaration(s) => {
            let ty_exprs = expr_list(py, &s.ty_exprs, symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(
                py,
                SemInputDeclaration::init(span, annotations, name, ty_exprs),
            )?
            .into_any()
        }
        StmtKind::OutputDeclaration(s) => {
            let ty_exprs = expr_list(py, &s.ty_exprs, symbols)?;
            let init_expr = build_expr(py, &s.init_expr, symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(
                py,
                SemOutputDeclaration::init(span, annotations, name, ty_exprs, init_expr),
            )?
            .into_any()
        }
        StmtKind::MeasureArrow(s) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &s.measurement.operand, symbols)?;
            let target = match &s.target {
                Some(target) => Some(build_expr(py, target, symbols)?),
                None => None,
            };
            Py::new(py, SemMeasureArrow::init(span, annotations, qubits, target))?.into_any()
        }
        StmtKind::Pragma(s) => {
            let name = s.identifier.as_ref().map(PathKind::as_string);
            let value = s.value.as_ref().map(ToString::to_string);
            Py::new(py, SemPragma::init(span, annotations, name, value))?.into_any()
        }
        StmtKind::QuantumGateDefinition(s) => {
            let params = s
                .params
                .iter()
                .map(|id| symbol_name(symbols, *id).unwrap_or_default())
                .collect();
            let qubits = s
                .qubits
                .iter()
                .map(|id| symbol_name(symbols, *id).unwrap_or_default())
                .collect();
            let body = stmt_list(py, &s.body.stmts, symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(
                py,
                SemGateDefinition::init(span, annotations, name, params, qubits, body),
            )?
            .into_any()
        }
        StmtKind::QubitDecl(s) => {
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(py, SemQubitDecl::init(span, annotations, name))?.into_any()
        }
        StmtKind::QubitArrayDecl(s) => {
            let size = build_expr(py, &s.size, symbols)?;
            let name = symbol_name(symbols, s.symbol_id);
            Py::new(py, SemQubitArrayDecl::init(span, annotations, name, size))?.into_any()
        }
        StmtKind::Reset(s) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &s.operand, symbols)?;
            Py::new(py, SemReset::init(span, annotations, qubits))?.into_any()
        }
        StmtKind::Return(s) => {
            let value = build_opt_expr(py, s.expr.as_deref(), symbols)?;
            Py::new(py, SemReturn::init(span, annotations, value))?.into_any()
        }
        StmtKind::Switch(s) => {
            let target = build_expr(py, &s.target, symbols)?;
            let mut labels = Vec::new();
            let mut body = Vec::new();
            for case in &s.cases {
                for label in &case.labels {
                    labels.push(build_expr(py, label, symbols)?);
                }
                for case_stmt in &case.block.stmts {
                    body.push(build_stmt(py, case_stmt, symbols)?);
                }
            }
            let mut default = Vec::new();
            if let Some(default_block) = &s.default {
                for default_stmt in &default_block.stmts {
                    default.push(build_stmt(py, default_stmt, symbols)?);
                }
            }
            Py::new(
                py,
                SemSwitch::init(span, annotations, target, labels, body, default),
            )?
            .into_any()
        }
        StmtKind::WhileLoop(s) => {
            let condition = build_expr(py, &s.condition, symbols)?;
            let body = build_stmt(py, &s.body, symbols)?;
            Py::new(py, SemWhileLoop::init(span, annotations, condition, body))?.into_any()
        }
        StmtKind::Err => Py::new(py, SemErrStmt::init(span, annotations))?.into_any(),
    };
    Ok(obj)
}

#[allow(clippy::too_many_lines)]
fn build_expr(py: Python<'_>, expr: &sem::Expr, symbols: &SymbolTable) -> PyResult<Py<PyAny>> {
    let span = Span::from(expr.span);
    let ty = SemType::from_core(py, &expr.ty)?;
    let const_value = literal_value(py, expr.const_value.as_ref())?;

    let obj: Py<PyAny> = match expr.kind.as_ref() {
        ExprKind::Err => Py::new(py, SemErrExpr::init(span, ty, const_value, None))?.into_any(),
        ExprKind::ResolvedIdent(id) => {
            let symbol = Some(build_symbol(py, symbols, *id)?);
            let name = symbol_name(symbols, *id);
            Py::new(
                py,
                SemResolvedIdent::init(span, ty, const_value, symbol, name, (*id).into()),
            )?
            .into_any()
        }
        ExprKind::CapturedResolvedIdent(id) => {
            let symbol = Some(build_symbol(py, symbols, *id)?);
            let name = symbol_name(symbols, *id);
            Py::new(
                py,
                SemCapturedResolvedIdent::init(span, ty, const_value, symbol, name, (*id).into()),
            )?
            .into_any()
        }
        ExprKind::UnaryOp(e) => {
            let operand = build_expr(py, &e.expr, symbols)?;
            Py::new(
                py,
                SemUnaryOpExpr::init(span, ty, const_value, None, e.op.to_string(), operand),
            )?
            .into_any()
        }
        ExprKind::BinaryOp(e) => {
            let lhs = build_expr(py, &e.lhs, symbols)?;
            let rhs = build_expr(py, &e.rhs, symbols)?;
            Py::new(
                py,
                SemBinaryOpExpr::init(span, ty, const_value, None, e.op.to_string(), lhs, rhs),
            )?
            .into_any()
        }
        ExprKind::Lit(lit) => {
            let (value, elements) = literal_expr_parts(py, lit, symbols)?;
            Py::new(
                py,
                SemLiteral::init(span, ty, const_value, None, value, elements),
            )?
            .into_any()
        }
        ExprKind::ResolvedFunctionCall(e) => {
            let args = expr_list(py, &e.args, symbols)?;
            let symbol = Some(build_symbol(py, symbols, e.callee_id)?);
            let name = symbol_name(symbols, e.callee_id);
            Py::new(
                py,
                SemFunctionCall::init(
                    span,
                    ty,
                    const_value,
                    symbol,
                    name,
                    e.callee_id.into(),
                    args,
                ),
            )?
            .into_any()
        }
        ExprKind::BuiltinFunctionCall(e) => {
            let args = expr_list(py, &e.args, symbols)?;
            Py::new(
                py,
                SemBuiltinFunctionCall::init(span, ty, const_value, None, e.name.to_string(), args),
            )?
            .into_any()
        }
        ExprKind::Cast(e) => {
            let operand = build_expr(py, &e.expr, symbols)?;
            let ty_exprs = expr_list(py, &e.ty_exprs, symbols)?;
            Py::new(
                py,
                SemCast::init(
                    span,
                    ty,
                    const_value,
                    None,
                    operand,
                    ty_exprs,
                    e.kind.to_string(),
                ),
            )?
            .into_any()
        }
        ExprKind::IndexedExpr(e) => {
            let collection = build_expr(py, &e.collection, symbols)?;
            let mut indices = Vec::new();
            collect_index(py, &mut indices, &e.index, symbols)?;
            Py::new(
                py,
                SemIndexedExpr::init(span, ty, const_value, None, collection, indices),
            )?
            .into_any()
        }
        ExprKind::Paren(inner) => {
            let operand = build_expr(py, inner, symbols)?;
            Py::new(py, SemParen::init(span, ty, const_value, None, operand))?.into_any()
        }
        ExprKind::Measure(e) => {
            let mut qubits = Vec::new();
            collect_gate_operand(py, &mut qubits, &e.operand, symbols)?;
            Py::new(py, SemMeasure::init(span, ty, const_value, None, qubits))?.into_any()
        }
        ExprKind::RuntimeSizeof(e) => {
            let array = build_expr(py, &e.array, symbols)?;
            let dimension = build_expr(py, &e.dimension, symbols)?;
            Py::new(
                py,
                SemRuntimeSizeof::init(span, ty, const_value, None, array, dimension, e.array_rank),
            )?
            .into_any()
        }
        ExprKind::EvaluatedDurationof(e) => {
            let body = stmt_list(py, &e.scope.stmts, symbols)?;
            Py::new(
                py,
                SemEvaluatedDurationof::init(span, ty, const_value, None, body),
            )?
            .into_any()
        }
        ExprKind::Concat(e) => {
            let operands = expr_list(py, &e.operands, symbols)?;
            Py::new(py, SemConcat::init(span, ty, const_value, None, operands))?.into_any()
        }
    };
    Ok(obj)
}

// ----------------------------------------------------------------------------
// Child-collection helpers
// ----------------------------------------------------------------------------

fn expr_list(
    py: Python<'_>,
    exprs: &[sem::Expr],
    symbols: &SymbolTable,
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(exprs.len());
    for expr in exprs {
        out.push(build_expr(py, expr, symbols)?);
    }
    Ok(out)
}

fn stmt_list(
    py: Python<'_>,
    stmts: &[sem::Stmt],
    symbols: &SymbolTable,
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(stmts.len());
    for stmt in stmts {
        out.push(build_stmt(py, stmt, symbols)?);
    }
    Ok(out)
}

fn build_opt_expr(
    py: Python<'_>,
    expr: Option<&sem::Expr>,
    symbols: &SymbolTable,
) -> PyResult<Option<Py<PyAny>>> {
    match expr {
        Some(expr) => Ok(Some(build_expr(py, expr, symbols)?)),
        None => Ok(None),
    }
}

fn gate_operand_list(
    py: Python<'_>,
    operands: &[sem::GateOperand],
    symbols: &SymbolTable,
) -> PyResult<Vec<Py<PyAny>>> {
    let mut out = Vec::with_capacity(operands.len());
    for operand in operands {
        collect_gate_operand(py, &mut out, operand, symbols)?;
    }
    Ok(out)
}

fn collect_gate_operand(
    py: Python<'_>,
    out: &mut Vec<Py<PyAny>>,
    operand: &sem::GateOperand,
    symbols: &SymbolTable,
) -> PyResult<()> {
    match &operand.kind {
        sem::GateOperandKind::Expr(expr) => out.push(build_expr(py, expr, symbols)?),
        sem::GateOperandKind::HardwareQubit(hw) => out.push(build_hardware_qubit(py, hw)?),
        sem::GateOperandKind::Err => {}
    }
    Ok(())
}

fn build_hardware_qubit(py: Python<'_>, hw: &sem::HardwareQubit) -> PyResult<Py<PyAny>> {
    let init = PyClassInitializer::from(QASMNode {
        span: Span::from(hw.span),
    })
    .add_subclass(Expression)
    .add_subclass(SemHardwareQubit {
        name: hw.name.to_string(),
    });
    Ok(Py::new(py, init)?.into_any())
}

fn collect_index(
    py: Python<'_>,
    out: &mut Vec<Py<PyAny>>,
    index: &sem::Index,
    symbols: &SymbolTable,
) -> PyResult<()> {
    match index {
        sem::Index::Expr(expr) => out.push(build_expr(py, expr, symbols)?),
        sem::Index::Range(range) => collect_range(py, out, range, symbols)?,
    }
    Ok(())
}

fn collect_range(
    py: Python<'_>,
    out: &mut Vec<Py<PyAny>>,
    range: &sem::Range,
    symbols: &SymbolTable,
) -> PyResult<()> {
    if let Some(start) = &range.start {
        out.push(build_expr(py, start, symbols)?);
    }
    if let Some(step) = &range.step {
        out.push(build_expr(py, step, symbols)?);
    }
    if let Some(end) = &range.end {
        out.push(build_expr(py, end, symbols)?);
    }
    Ok(())
}

fn collect_enumerable_set(
    py: Python<'_>,
    out: &mut Vec<Py<PyAny>>,
    set: &sem::EnumerableSet,
    symbols: &SymbolTable,
) -> PyResult<()> {
    match set {
        sem::EnumerableSet::Set(set) => {
            for value in &set.values {
                out.push(build_expr(py, value, symbols)?);
            }
        }
        sem::EnumerableSet::Range(range) => collect_range(py, out, range, symbols)?,
        sem::EnumerableSet::Expr(expr) => out.push(build_expr(py, expr, symbols)?),
    }
    Ok(())
}

fn collect_modifier(
    py: Python<'_>,
    out: &mut Vec<Py<PyAny>>,
    modifier: &sem::QuantumGateModifier,
    symbols: &SymbolTable,
) -> PyResult<()> {
    match &modifier.kind {
        sem::GateModifierKind::Inv => {}
        sem::GateModifierKind::Pow(expr)
        | sem::GateModifierKind::Ctrl(expr)
        | sem::GateModifierKind::NegCtrl(expr) => out.push(build_expr(py, expr, symbols)?),
    }
    Ok(())
}

// ----------------------------------------------------------------------------
// Literal-value projection
// ----------------------------------------------------------------------------

/// The projected value and element children of a literal expression.
///
/// Scalar literals carry a Python value and no elements; array literals carry no
/// scalar value and expose their element expressions as children.
type LiteralParts = (Option<Py<PyAny>>, Vec<Py<PyAny>>);

fn literal_expr_parts(
    py: Python<'_>,
    lit: &LiteralKind,
    symbols: &SymbolTable,
) -> PyResult<LiteralParts> {
    match lit {
        LiteralKind::Array(array) => {
            let mut elements = Vec::with_capacity(array.data.len());
            for item in &array.data {
                elements.push(build_expr(py, item, symbols)?);
            }
            Ok((None, elements))
        }
        other => Ok((literal_kind_value(py, other)?, Vec::new())),
    }
}

fn literal_value(py: Python<'_>, lit: Option<&LiteralKind>) -> PyResult<Option<Py<PyAny>>> {
    match lit {
        Some(lit) => literal_kind_value(py, lit),
        None => Ok(None),
    }
}

fn literal_kind_value(py: Python<'_>, lit: &LiteralKind) -> PyResult<Option<Py<PyAny>>> {
    let value: Py<PyAny> = match lit {
        LiteralKind::Array(_) => return Ok(None),
        LiteralKind::Bool(b) | LiteralKind::Bit(b) => (*b).into_py_any(py)?,
        LiteralKind::Int(i) => (*i).into_py_any(py)?,
        LiteralKind::Float(f) => (*f).into_py_any(py)?,
        LiteralKind::Complex(value) => PyComplex::from_doubles(py, value.real, value.imag)
            .into_any()
            .unbind(),
        LiteralKind::Angle(angle) => angle.to_string().into_py_any(py)?,
        LiteralKind::Duration(duration) => duration.to_string().into_py_any(py)?,
        LiteralKind::Bitstring(value, width) => {
            let width = *width as usize;
            format!("{:0>width$}", value.to_str_radix(2)).into_py_any(py)?
        }
        LiteralKind::BigInt(value) => bigint_to_py(py, &value.to_str_radix(10))?,
    };
    Ok(Some(value))
}

fn bigint_to_py(py: Python<'_>, decimal: &str) -> PyResult<Py<PyAny>> {
    Ok(py
        .import("builtins")?
        .getattr("int")?
        .call1((decimal,))?
        .unbind())
}
