# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Standalone parser and semantic analyzer for OpenQASM 3.

This package exposes the ``parse``, ``analyze``, and ``tokenize`` entry points
together with a rich, typed AST node hierarchy (syntactic and semantic), an
``OpenQASM 3`` source emitter (``unparse``), and ``ast``-style visitors.
"""

from __future__ import annotations

from ._native import (
    # Entry points
    parse,
    analyze,
    tokenize,
    unparse,
    # Result wrappers
    ParseResult,
    SemanticResult,
    # Diagnostics
    Diagnostic,
    Label,
    Severity,
    # Tokens / shared primitives
    Token,
    TokenKind,
    Span,
    # Syntactic backbone and kinds
    Program,
    Stmt,
    Expr,
    StmtKind,
    ExprKind,
    # Syntactic statement nodes
    AliasStmt,
    AssignStmt,
    AssignOpStmt,
    BarrierStmt,
    BoxStmt,
    BreakStmt,
    BlockStmt,
    CalStmt,
    CalibrationGrammarStmt,
    ClassicalDeclStmt,
    ConstDeclStmt,
    ContinueStmt,
    DefStmt,
    DefCalStmt,
    DelayStmt,
    EndStmt,
    ExprStmt,
    ExternDeclStmt,
    ForStmt,
    IfStmt,
    GateCallStmt,
    GPhaseStmt,
    IncludeStmt,
    IODeclarationStmt,
    MeasureStmt,
    PragmaStmt,
    QuantumGateDefinitionStmt,
    QuantumDeclStmt,
    ResetStmt,
    ReturnStmt,
    SwitchStmt,
    WhileLoopStmt,
    ErrStmt,
    # Syntactic expression nodes
    ErrExpr,
    IdentExpr,
    UnaryOpExpr,
    BinaryOpExpr,
    LitExpr,
    FunctionCallExpr,
    CastExpr,
    IndexExpr,
    ParenExpr,
    DurationOfExpr,
    # Semantic backbone and kinds
    SemProgram,
    SemStmt,
    SemExpr,
    SemStmtKind,
    SemExprKind,
    # Semantic symbol surface
    Type,
    Symbol,
    SymbolTable,
    # Semantic statement nodes
    SemAliasStmt,
    SemAssignStmt,
    SemBarrierStmt,
    SemBoxStmt,
    SemBlockStmt,
    SemBreakStmt,
    SemCalibrationStmt,
    SemCalibrationGrammarStmt,
    SemClassicalDeclStmt,
    SemContinueStmt,
    SemDefStmt,
    SemDefCalStmt,
    SemDelayStmt,
    SemEndStmt,
    SemExprStmt,
    SemExternDeclStmt,
    SemForStmt,
    SemGateCallStmt,
    SemIfStmt,
    SemIncludeStmt,
    SemIndexedClassicalTypeAssignStmt,
    SemInputDeclarationStmt,
    SemOutputDeclarationStmt,
    SemMeasureArrowStmt,
    SemPragmaStmt,
    SemQuantumGateDefinitionStmt,
    SemQubitDeclStmt,
    SemQubitArrayDeclStmt,
    SemResetStmt,
    SemReturnStmt,
    SemSwitchStmt,
    SemWhileLoopStmt,
    SemErrStmt,
    # Semantic expression nodes
    SemErrExpr,
    SemCapturedIdentExpr,
    SemIdentExpr,
    SemUnaryOpExpr,
    SemBinaryOpExpr,
    SemLitExpr,
    SemFunctionCallExpr,
    SemBuiltinFunctionCallExpr,
    SemCastExpr,
    SemIndexedExpr,
    SemParenExpr,
    SemMeasureExpr,
    SemSizeofCallExpr,
    SemDurationofCallExpr,
    SemConcatExpr,
)

from .visitors import SemanticVisitor, SyntaxRewriter, SyntaxVisitor

__all__ = [
    # Entry points
    "parse",
    "analyze",
    "tokenize",
    "unparse",
    # Result wrappers
    "ParseResult",
    "SemanticResult",
    # Diagnostics
    "Diagnostic",
    "Label",
    "Severity",
    # Tokens / shared primitives
    "Token",
    "TokenKind",
    "Span",
    # Syntactic backbone and kinds
    "Program",
    "Stmt",
    "Expr",
    "StmtKind",
    "ExprKind",
    # Syntactic statement nodes
    "AliasStmt",
    "AssignStmt",
    "AssignOpStmt",
    "BarrierStmt",
    "BoxStmt",
    "BreakStmt",
    "BlockStmt",
    "CalStmt",
    "CalibrationGrammarStmt",
    "ClassicalDeclStmt",
    "ConstDeclStmt",
    "ContinueStmt",
    "DefStmt",
    "DefCalStmt",
    "DelayStmt",
    "EndStmt",
    "ExprStmt",
    "ExternDeclStmt",
    "ForStmt",
    "IfStmt",
    "GateCallStmt",
    "GPhaseStmt",
    "IncludeStmt",
    "IODeclarationStmt",
    "MeasureStmt",
    "PragmaStmt",
    "QuantumGateDefinitionStmt",
    "QuantumDeclStmt",
    "ResetStmt",
    "ReturnStmt",
    "SwitchStmt",
    "WhileLoopStmt",
    "ErrStmt",
    # Syntactic expression nodes
    "ErrExpr",
    "IdentExpr",
    "UnaryOpExpr",
    "BinaryOpExpr",
    "LitExpr",
    "FunctionCallExpr",
    "CastExpr",
    "IndexExpr",
    "ParenExpr",
    "DurationOfExpr",
    # Semantic backbone and kinds
    "SemProgram",
    "SemStmt",
    "SemExpr",
    "SemStmtKind",
    "SemExprKind",
    # Semantic symbol surface
    "Type",
    "Symbol",
    "SymbolTable",
    # Semantic statement nodes
    "SemAliasStmt",
    "SemAssignStmt",
    "SemBarrierStmt",
    "SemBoxStmt",
    "SemBlockStmt",
    "SemBreakStmt",
    "SemCalibrationStmt",
    "SemCalibrationGrammarStmt",
    "SemClassicalDeclStmt",
    "SemContinueStmt",
    "SemDefStmt",
    "SemDefCalStmt",
    "SemDelayStmt",
    "SemEndStmt",
    "SemExprStmt",
    "SemExternDeclStmt",
    "SemForStmt",
    "SemGateCallStmt",
    "SemIfStmt",
    "SemIncludeStmt",
    "SemIndexedClassicalTypeAssignStmt",
    "SemInputDeclarationStmt",
    "SemOutputDeclarationStmt",
    "SemMeasureArrowStmt",
    "SemPragmaStmt",
    "SemQuantumGateDefinitionStmt",
    "SemQubitDeclStmt",
    "SemQubitArrayDeclStmt",
    "SemResetStmt",
    "SemReturnStmt",
    "SemSwitchStmt",
    "SemWhileLoopStmt",
    "SemErrStmt",
    # Semantic expression nodes
    "SemErrExpr",
    "SemCapturedIdentExpr",
    "SemIdentExpr",
    "SemUnaryOpExpr",
    "SemBinaryOpExpr",
    "SemLitExpr",
    "SemFunctionCallExpr",
    "SemBuiltinFunctionCallExpr",
    "SemCastExpr",
    "SemIndexedExpr",
    "SemParenExpr",
    "SemMeasureExpr",
    "SemSizeofCallExpr",
    "SemDurationofCallExpr",
    "SemConcatExpr",
    # Visitors
    "SyntaxVisitor",
    "SemanticVisitor",
    "SyntaxRewriter",
]
