# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Type stubs for the ``qdk_openqasm_parser._native`` extension module."""

from enum import IntEnum
from typing import Any, Iterator, Optional

# ---------------------------------------------------------------------------
# Shared primitives
# ---------------------------------------------------------------------------

class Span:
    lo: int
    hi: int

class Severity(IntEnum):
    Error = ...
    Warning = ...
    Advice = ...

class Label:
    span: Span
    message: Optional[str]

class Diagnostic:
    message: str
    severity: Severity
    code: Optional[str]
    labels: list[Label]
    related: list["Diagnostic"]

class TokenKind:
    @property
    def name(self) -> str: ...
    def __str__(self) -> str: ...

class Token:
    kind: TokenKind
    span: Span

# ---------------------------------------------------------------------------
# Result wrappers
# ---------------------------------------------------------------------------

class ParseResult:
    diagnostics: list[Diagnostic]
    has_errors: bool
    @property
    def program(self) -> "Program": ...

class SemanticResult:
    diagnostics: list[Diagnostic]
    has_errors: bool
    @property
    def program(self) -> "SemProgram": ...
    @property
    def symbols(self) -> "SymbolTable": ...

# ---------------------------------------------------------------------------
# Syntactic AST
# ---------------------------------------------------------------------------

class StmtKind(IntEnum):
    Alias = ...
    Assign = ...
    AssignOp = ...
    Barrier = ...
    Box = ...
    Break = ...
    Block = ...
    Cal = ...
    CalibrationGrammar = ...
    ClassicalDecl = ...
    ConstDecl = ...
    Continue = ...
    Def = ...
    DefCal = ...
    Delay = ...
    End = ...
    ExprStmt = ...
    ExternDecl = ...
    For = ...
    If = ...
    GateCall = ...
    GPhase = ...
    Include = ...
    IODeclaration = ...
    Measure = ...
    Pragma = ...
    QuantumGateDefinition = ...
    QuantumDecl = ...
    Reset = ...
    Return = ...
    Switch = ...
    WhileLoop = ...
    Err = ...

class ExprKind(IntEnum):
    Err = ...
    Ident = ...
    UnaryOp = ...
    BinaryOp = ...
    Lit = ...
    FunctionCall = ...
    Cast = ...
    IndexExpr = ...
    Paren = ...
    DurationOf = ...

class Program:
    span: Span
    version: Optional[tuple[int, Optional[int]]]
    statements: list[Any]
    def children(self) -> list[Any]: ...
    def accept(self, visitor: Any) -> Any: ...

class Stmt:
    span: Span
    kind: StmtKind
    name: Optional[str]
    annotations: list[str]
    def children(self) -> list[Any]: ...
    def accept(self, visitor: Any) -> Any: ...

class Expr:
    span: Span
    kind: ExprKind
    name: Optional[str]
    op: Optional[str]
    value: Optional[Any]
    def children(self) -> list[Any]: ...
    def accept(self, visitor: Any) -> Any: ...

class AliasStmt(Stmt): ...
class AssignStmt(Stmt): ...
class AssignOpStmt(Stmt): ...
class BarrierStmt(Stmt): ...
class BoxStmt(Stmt): ...
class BreakStmt(Stmt): ...
class BlockStmt(Stmt): ...
class CalStmt(Stmt): ...
class CalibrationGrammarStmt(Stmt): ...
class ClassicalDeclStmt(Stmt): ...
class ConstDeclStmt(Stmt): ...
class ContinueStmt(Stmt): ...
class DefStmt(Stmt): ...
class DefCalStmt(Stmt): ...
class DelayStmt(Stmt): ...
class EndStmt(Stmt): ...
class ExprStmt(Stmt): ...
class ExternDeclStmt(Stmt): ...
class ForStmt(Stmt): ...
class IfStmt(Stmt): ...
class GateCallStmt(Stmt): ...
class GPhaseStmt(Stmt): ...
class IncludeStmt(Stmt): ...
class IODeclarationStmt(Stmt): ...
class MeasureStmt(Stmt): ...
class PragmaStmt(Stmt): ...
class QuantumGateDefinitionStmt(Stmt): ...
class QuantumDeclStmt(Stmt): ...
class ResetStmt(Stmt): ...
class ReturnStmt(Stmt): ...
class SwitchStmt(Stmt): ...
class WhileLoopStmt(Stmt): ...
class ErrStmt(Stmt): ...
class ErrExpr(Expr): ...
class IdentExpr(Expr): ...
class UnaryOpExpr(Expr): ...
class BinaryOpExpr(Expr): ...
class LitExpr(Expr): ...
class FunctionCallExpr(Expr): ...
class CastExpr(Expr): ...
class IndexExpr(Expr): ...
class ParenExpr(Expr): ...
class DurationOfExpr(Expr): ...

# ---------------------------------------------------------------------------
# Semantic AST
# ---------------------------------------------------------------------------

class SemStmtKind(IntEnum): ...
class SemExprKind(IntEnum): ...

class Type:
    name: str
    is_const: bool
    def __str__(self) -> str: ...

class Symbol:
    id: int
    name: str
    span: Span
    ty: Type

class SymbolTable:
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Symbol]: ...
    def get(self, id: int) -> Optional[Symbol]: ...
    def lookup(self, name: str) -> Optional[Symbol]: ...

class SemProgram:
    version: Optional[tuple[int, Optional[int]]]
    pragmas: list[str]
    statements: list[Any]
    def children(self) -> list[Any]: ...
    def accept(self, visitor: Any) -> Any: ...

class SemStmt:
    span: Span
    kind: SemStmtKind
    name: Optional[str]
    annotations: list[str]
    def children(self) -> list[Any]: ...
    def accept(self, visitor: Any) -> Any: ...

class SemExpr:
    span: Span
    kind: SemExprKind
    name: Optional[str]
    op: Optional[str]
    value: Optional[Any]
    ty: Type
    const_value: Optional[Any]
    symbol_id: Optional[int]
    def children(self) -> list[Any]: ...
    def accept(self, visitor: Any) -> Any: ...

class SemAliasStmt(SemStmt): ...
class SemAssignStmt(SemStmt): ...
class SemBarrierStmt(SemStmt): ...
class SemBoxStmt(SemStmt): ...
class SemBlockStmt(SemStmt): ...
class SemBreakStmt(SemStmt): ...
class SemCalibrationStmt(SemStmt): ...
class SemCalibrationGrammarStmt(SemStmt): ...
class SemClassicalDeclStmt(SemStmt): ...
class SemContinueStmt(SemStmt): ...
class SemDefStmt(SemStmt): ...
class SemDefCalStmt(SemStmt): ...
class SemDelayStmt(SemStmt): ...
class SemEndStmt(SemStmt): ...
class SemExprStmt(SemStmt): ...
class SemExternDeclStmt(SemStmt): ...
class SemForStmt(SemStmt): ...
class SemGateCallStmt(SemStmt): ...
class SemIfStmt(SemStmt): ...
class SemIncludeStmt(SemStmt): ...
class SemIndexedClassicalTypeAssignStmt(SemStmt): ...
class SemInputDeclarationStmt(SemStmt): ...
class SemOutputDeclarationStmt(SemStmt): ...
class SemMeasureArrowStmt(SemStmt): ...
class SemPragmaStmt(SemStmt): ...
class SemQuantumGateDefinitionStmt(SemStmt): ...
class SemQubitDeclStmt(SemStmt): ...
class SemQubitArrayDeclStmt(SemStmt): ...
class SemResetStmt(SemStmt): ...
class SemReturnStmt(SemStmt): ...
class SemSwitchStmt(SemStmt): ...
class SemWhileLoopStmt(SemStmt): ...
class SemErrStmt(SemStmt): ...
class SemErrExpr(SemExpr): ...
class SemCapturedIdentExpr(SemExpr): ...
class SemIdentExpr(SemExpr): ...
class SemUnaryOpExpr(SemExpr): ...
class SemBinaryOpExpr(SemExpr): ...
class SemLitExpr(SemExpr): ...
class SemFunctionCallExpr(SemExpr): ...
class SemBuiltinFunctionCallExpr(SemExpr): ...
class SemCastExpr(SemExpr): ...
class SemIndexedExpr(SemExpr): ...
class SemParenExpr(SemExpr): ...
class SemMeasureExpr(SemExpr): ...
class SemSizeofCallExpr(SemExpr): ...
class SemDurationofCallExpr(SemExpr): ...
class SemConcatExpr(SemExpr): ...

# ---------------------------------------------------------------------------
# Entry points
# ---------------------------------------------------------------------------

def parse(
    source: str,
    *,
    path: str = ...,
    includes: Any | None = ...,
) -> ParseResult: ...
def analyze(
    source: str,
    *,
    path: str = ...,
    includes: Any | None = ...,
) -> SemanticResult: ...
def tokenize(source: str) -> list[Token]: ...
def unparse(program: Program) -> str: ...
