[package]
name = "qsharp"
version = "0.0.0"
description = "Q# Python Bindings"
authors = ["Microsoft"]
homepage = "https://github.com/microsoft/qsharp"
repository = "https://github.com/microsoft/qsharp"
edition = "2021"
license = "MIT"

[dependencies]
pyo3 = { version = "0.18", features = ["abi3-py37", "extension-module"] }

qsc_ast = { path = "../../compiler/qsc_ast" }
qsc_eval = { path = "../../compiler/qsc_eval" }
qsc_frontend = { path = "../../compiler/qsc_frontend" }
qsc_passes = { path = "../../compiler/qsc_passes" }
num-bigint = { workspace = true }
num-complex = { workspace = true }

ouroboros = "0.15.6"

[lib]
crate-type = ["cdylib"]

[package.metadata.maturin]
name = "qsharp._native"
