[package]
name = "qsc_eval"
version = "0.0.0"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miette = { workspace = true }
num-bigint = { workspace = true }
num-complex = { workspace = true }
ouroboros = { workspace = true }
qir-backend = { git = "https://github.com/qir-alliance/qir-runner", rev = "8a7ee42401ef23092c5ecd5e92877948f4b8e017" }
qir-stdlib = { git = "https://github.com/qir-alliance/qir-runner", rev = "8a7ee42401ef23092c5ecd5e92877948f4b8e017" }
qsc_data_structures = { path = "../qsc_data_structures" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_hir = { path = "../qsc_hir" }
qsc_passes = { path = "../qsc_passes" }
rand =  { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
indoc = { workspace = true }
