[package]
name = "qsc_eval"
version = "0.0.0"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
qsc_ast = { path = "../qsc_ast" }
qsc_frontend = { path = "../qsc_frontend" }
qir-backend = { git = "https://github.com/qir-alliance/qir-runner", tag = "v0.1.0" }
qir-stdlib = { git = "https://github.com/qir-alliance/qir-runner", tag = "v0.1.0" }
num-bigint = "0.4.3"
miette = "5.6.0"
thiserror = "1.0.39"

[dev-dependencies]
expect-test = "1.4.0"
indoc = "2.0.0"

