[package]
name = "qsc_eval"
version = "0.0.0"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miette = { workspace = true }
num-bigint = { workspace = true }
num-complex = { workspace = true }
qir-backend = { git = "https://github.com/qir-alliance/qir-runner", rev = "7141d6ebc0a573dfe2871a362b46d98dfe6f751c" }
qir-stdlib = { git = "https://github.com/qir-alliance/qir-runner", rev = "7141d6ebc0a573dfe2871a362b46d98dfe6f751c" }
qsc_data_structures = { path = "../qsc_data_structures" }
qsc_hir = { path = "../qsc_hir" }
rand =  { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
indoc = { workspace = true }
qsc_frontend = { path = "../qsc_frontend" }
qsc_passes = { path = "../qsc_passes" }
