[package]
name = "qsc_eval"
version = "0.0.0"
edition = "2021"

[dependencies]
qsc_ast = { path = "../qsc_ast" }
qsc_frontend = { path = "../qsc_frontend" }
qir-backend = { git = "https://github.com/qir-alliance/qir-runner", rev = "67c2902cd8682976aa7e5b71087a9a03a8889999" }
qir-stdlib = { git = "https://github.com/qir-alliance/qir-runner", rev = "67c2902cd8682976aa7e5b71087a9a03a8889999", features = ["disable-range-support"] }
