[package]
name = "qsc_eval"
version = "0.0.0"

authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
qir-backend = { git = "https://github.com/qir-alliance/qir-runner", rev = "bd05b59e38b70a162d29ddab7332ca19a5bddbde" }
qsc_ast = { path = "../qsc_ast" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_passes = { path = "../qsc_passes" }
qir-stdlib = { git = "https://github.com/qir-alliance/qir-runner", rev = "bd05b59e38b70a162d29ddab7332ca19a5bddbde" }
miette = { workspace = true }
num-bigint = { workspace = true }
num-complex = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
expect-test = { workspace = true }
indoc = { workspace = true }
