name: qdk-publish-$(BuildId)

# Run on merges to main to ensure that the latest code
# is always able to be published.
trigger: none
pr: none

variables:
  CARGO_TERM_COLOR: always
  QDK_LIB_OVERRIDE_MICROSOFT_QDK: $(Build.SourcesDirectory)
  RUST_TOOLCHAIN_VERSION: "1.95"
  # CFS requires that we have a .npmrc next to each package.json.  If we set this variable, it will
  # synthesize everything it requires during the pipeline run, leaving our external contributors
  # free to continue using the default npmjs.org registry.
  # (To learn more, search eng.ms for AZURE_ARTIFACTS_FEED.)
  #
  # Caveat: the synthesized .npmrc file doesn't seem to contain the necessary token, so we'll have to
  # use the npmAuthenticate task explicitly.
  AZURE_ARTIFACTS_FEED: https://pkgs.dev.azure.com/ms-azurequantum/AzureQuantum/_packaging/azure-quantum/npm/registry/

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release
  containers:
    - container: qdkImage
      image: qdkacr-cfgqhwddajdaebhg.azurecr.io/qdk-image:cc4-amd64
      endpoint: qdkacr

parameters:
  - name: matrix
    type: object
    default:
      - name: linux_x86_64
        poolName: "Azure-Pipelines-DevTools-GPU"
        imageName: "ubuntu-2204-qdk-gpu"
        os: linux
        arch: x86_64
        envVars:
          QDK_GPU_TESTS: "1"

# variables set by pipeline
# - BASE_IMAGE
# - BUILD_NUMBER
# - BUILD_TYPE
# - cratesIoFeedOverride
# - OwnerPersonalAlias
# - toolchainFeed

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: "Azure-Pipelines-DevTools-EO"
        image: windows-2025
        os: windows
      sbom:
        continueOnError: false
    stages:
      - stage: build
        displayName: Build
        jobs:
          - ${{ each target in parameters.matrix }}:
              - job: Python_${{ target.name }}_job
                pool:
                  name: ${{ target.poolName }}
                  image: ${{ target.imageName }}
                  os: ${{ target.os }}
                container: qdkImage
                timeoutInMinutes: 90
                templateContext:
                  outputs:
                    - output: pipelineArtifact
                      displayName: "Upload Python Artifacts Linux"
                      condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
                      targetPath: $(System.DefaultWorkingDirectory)/target/wheels
                      artifactName: Wheels.Linux.${{ target.arch }}
                steps:
                  - checkout: self

                  - script: |
                      set -euxo pipefail

                      cat /etc/redhat-release
                      uname -m
                      python --version
                      llvm-config --version
                    displayName: Verify Environment

                  - script: |
                      set -euxo pipefail

                      mkdir -p target/wheels
                      echo "Mock wheel content" > target/wheels/mock_wheel.whl
                      ls -l target/wheels/*
                    displayName: Create mock wheel
