[package]
name = "qsc_partial_eval"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
miette = { workspace = true }
qsc_eval = { path = "../qsc_eval" }
qsc_fir = { path = "../qsc_fir" }
qsc_rca = { path = "../qsc_rca" }
qsc_rir = { path = "../qsc_rir" }

[dev-dependencies]
expect-test = { workspace = true }

[lints]
workspace = true

[lib]
doctest = false
