[package]
name = "qsc_qasm"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
bitflags = { workspace = true }
enum-iterator = { workspace = true }
indenter = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
miette = { workspace = true }
qsc_ast = { path = "../qsc_ast" }
qsc_data_structures = { path = "../qsc_data_structures" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_hir = { path = "../qsc_hir" }
qsc_parse = { path = "../qsc_parse" }
qsc_passes = { path = "../qsc_passes" }
rustc-hash = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
criterion = { workspace = true, features = ["cargo_bench_support"] }
difference = { workspace = true }
expect-test = { workspace = true }
indoc = { workspace = true }
miette = { workspace = true, features = ["fancy"] }
# Self import adding fs feature so that we can test
# loading qasm from file.
qsc = { path = "../qsc" }
qsc_codegen = { path = "../qsc_codegen" }

[lints]
workspace = true

[lib]
bench = false

[[bench]]
name = "rgqft_multiplier"
harness = false
