name: DevSkim

on:
  pull_request:
    branches: [main]
  merge_group:
  workflow_dispatch:
  schedule:
    # set schedule to run at 2AM PT on Saturdays
    - cron: "0 9 * * Sat"

jobs:
  lint:
    name: DevSkim
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write

      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Run DevSkim scanner
        uses: microsoft/DevSkim-Action@4b5047945a44163b94642a1cecc0d93a3f428cc6 # v1.0.16

      - name: Upload DevSkim scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@c4dd10e44af883a891fe31ced449bcb4a6728b9b # v3.37.6
        with:
          sarif_file: devskim-results.sarif
