[package]
name = "qsc_linter"

version.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
indenter = { workspace = true }
num-bigint = { workspace = true }
qsc = { path = "../qsc" }
qsc_ast = { path = "../qsc_ast" }
qsc_fir = { path = "../qsc_fir" }
qsc_hir = { path = "../qsc_hir" }
qsc_frontend = { path = "../qsc_frontend" }
qsc_parse = { path = "../qsc_parse" }
qsc_passes = { path = "../qsc_passes" }
qsc_data_structures = { path = "../qsc_data_structures" }
rustc-hash = { workspace = true }

[lib]
doctest = false
